/* ============================================================
   exams.js — ĐỀ KIỂM TRA (tĩnh). Tự chấm tại trình duyệt → tức thì.

   CÁCH THÊM ĐỀ / CÂU HỎI:
   - Thêm object vào EXAMS[<mã môn>]:
       { examId:'ma-de', title:'Tên đề', durationMin:15, questions:[ ... ] }
   - Mỗi câu (trắc nghiệm 1 đáp án):
       { stem:'Đề bài (LaTeX $...$)', options:['A','B','C','D'], answer:<chỉ số đúng 0..3>,
         explanation:'Lời giải ngắn' }
   ============================================================ */

const EXAMS = {
  TOAN: [
    {
      examId: 'toan-c1', title: 'Đạo hàm & Khảo sát hàm số', durationMin: 15,
      questions: [
        { stem: 'Hàm số $y=x^3-3x$ đồng biến trên khoảng nào?',
          options: ['$(-1;1)$', '$(-\\infty;-1)$ và $(1;+\\infty)$', '$(0;+\\infty)$', '$\\mathbb{R}$'],
          answer: 1, explanation: '$y\'=3x^2-3>0 \\Leftrightarrow x<-1$ hoặc $x>1$.' },
        { stem: 'Số điểm cực trị của hàm $y=x^4-2x^2$ là?',
          options: ['$0$', '$1$', '$2$', '$3$'],
          answer: 3, explanation: '$y\'=4x^3-4x=4x(x-1)(x+1)$ có 3 nghiệm ⇒ 3 cực trị.' },
        { stem: 'Giá trị lớn nhất của $y=-x^2+4x$ trên $\\mathbb{R}$ là?',
          options: ['$2$', '$4$', '$0$', '$8$'],
          answer: 1, explanation: '$y\'=-2x+4=0 \\Leftrightarrow x=2$, $y(2)=4$.' },
        { stem: 'Tiệm cận ngang của đồ thị $y=\\dfrac{2x+1}{x-1}$ là?',
          options: ['$x=1$', '$y=2$', '$y=1$', '$x=2$'],
          answer: 1, explanation: '$\\lim\\limits_{x\\to\\pm\\infty}y=\\dfrac{2}{1}=2$.' },
        { stem: 'Đạo hàm của $y=\\ln x$ là?',
          options: ['$x$', '$\\dfrac{1}{x}$', '$\\dfrac{1}{x^2}$', '$\\ln x$'],
          answer: 1, explanation: '$(\\ln x)\'=\\dfrac{1}{x}$.' },
      ],
    },
    {
      examId: 'toan-tp-xs', title: 'Tích phân & Xác suất', durationMin: 15,
      questions: [
        { stem: 'Tính $\\displaystyle\\int_0^1 2x\\,dx$.',
          options: ['$1$', '$2$', '$\\dfrac{1}{2}$', '$0$'],
          answer: 0, explanation: '$[x^2]_0^1=1$.' },
        { stem: 'Họ nguyên hàm của $f(x)=x^2$ là?',
          options: ['$x^3+C$', '$\\dfrac{x^3}{3}+C$', '$2x+C$', '$3x^2+C$'],
          answer: 1, explanation: '$\\int x^2dx=\\dfrac{x^3}{3}+C$.' },
        { stem: 'Thể tích khối tròn xoay khi quay $y=\\sqrt{x}$ quanh $Ox$ từ $0$ đến $4$ là?',
          options: ['$4\\pi$', '$8\\pi$', '$16\\pi$', '$2\\pi$'],
          answer: 1, explanation: '$V=\\pi\\int_0^4 x\\,dx=8\\pi$.' },
        { stem: 'Cho $P(A\\cap B)=0{,}2$, $P(B)=0{,}5$. Tính $P(A\\mid B)$.',
          options: ['$0{,}1$', '$0{,}4$', '$0{,}25$', '$0{,}7$'],
          answer: 1, explanation: '$P(A\\mid B)=\\dfrac{0{,}2}{0{,}5}=0{,}4$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi}\\sin x\\,dx$.',
          options: ['$0$', '$1$', '$2$', '$-2$'],
          answer: 2, explanation: '$[-\\cos x]_0^{\\pi}=1+1=2$.' },
      ],
    },
    {
      examId: 'kt45-1', title: 'Kiểm tra 45′ #1 — Đạo hàm & Khảo sát hàm số', durationMin: 45,
      questions: [
        { stem: 'Hàm số $y=x^3-3x^2$ đồng biến trên khoảng nào?', options: ['$(0;2)$', '$(-\\infty;0)$ và $(2;+\\infty)$', '$(2;+\\infty)$', '$\\mathbb{R}$'], answer: 1, explanation: '$y\'=3x^2-6x=3x(x-2)>0\\Leftrightarrow x<0$ hoặc $x>2$.' },
        { stem: 'Giá trị cực đại của $y=-x^2+2x$ là?', options: ['$1$', '$2$', '$0$', '$-1$'], answer: 0, explanation: '$y\'=-2x+2=0\\Rightarrow x=1,\\ y(1)=1$.' },
        { stem: 'Số điểm cực trị của $y=x^3+x$ là?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 0, explanation: '$y\'=3x^2+1>0\\ \\forall x$ ⇒ không có cực trị.' },
        { stem: 'GTNN của $y=x^2-4x+5$ trên $\\mathbb{R}$ là?', options: ['$1$', '$5$', '$0$', '$-1$'], answer: 0, explanation: '$y=(x-2)^2+1\\ge 1$.' },
        { stem: 'Tiệm cận đứng của $y=\\dfrac{x+1}{x-2}$ là?', options: ['$x=2$', '$y=2$', '$x=-1$', '$y=1$'], answer: 0, explanation: 'Mẫu $=0\\Leftrightarrow x=2$.' },
        { stem: 'Hàm $y=x^4-2x^2+1$ có mấy điểm cực trị?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 3, explanation: '$y\'=4x^3-4x=4x(x-1)(x+1)$ có 3 nghiệm.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{2x-3}{x+1}$ là?', options: ['$y=2$', '$x=-1$', '$y=-3$', '$x=2$'], answer: 0, explanation: '$\\lim\\limits_{x\\to\\pm\\infty}y=2$.' },
        { stem: 'Hàm số $y=x^3$ đồng biến trên?', options: ['$(0;+\\infty)$', '$\\mathbb{R}$', '$(-\\infty;0)$', 'không khoảng nào'], answer: 1, explanation: '$y\'=3x^2\\ge 0$, bằng 0 tại 1 điểm ⇒ đồng biến trên $\\mathbb{R}$.' },
        { stem: 'Đạo hàm của $y=e^x$ là?', options: ['$x e^{x-1}$', '$e^x$', '$\\dfrac{1}{x}$', '$x$'], answer: 1, explanation: '$(e^x)\'=e^x$.' },
        { stem: 'GTLN của $y=x^3-3x$ trên $[0;2]$ là?', options: ['$0$', '$-2$', '$2$', '$6$'], answer: 2, explanation: '$y\'=3x^2-3=0\\Rightarrow x=1$; $y(0)=0, y(1)=-2, y(2)=2$.' },
      ],
    },
    {
      examId: 'kt45-2', title: 'Kiểm tra 45′ #2 — Nguyên hàm & Tích phân', durationMin: 45,
      questions: [
        { stem: 'Họ nguyên hàm $\\displaystyle\\int x^3\\,dx$ bằng?', options: ['$\\dfrac{x^4}{4}+C$', '$3x^2+C$', '$x^4+C$', '$4x^3+C$'], answer: 0, explanation: '$\\int x^n dx=\\dfrac{x^{n+1}}{n+1}+C$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 x^2\\,dx$.', options: ['$\\dfrac{1}{3}$', '$1$', '$\\dfrac{1}{2}$', '$3$'], answer: 0, explanation: '$[x^3/3]_0^1=1/3$.' },
        { stem: '$\\displaystyle\\int \\dfrac{1}{x}\\,dx$ bằng?', options: ['$\\ln|x|+C$', '$-\\dfrac{1}{x^2}+C$', '$x+C$', '$\\dfrac{1}{x^2}$'], answer: 0, explanation: '$\\int\\frac{1}{x}dx=\\ln|x|+C$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi}\\sin x\\,dx$.', options: ['$0$', '$1$', '$2$', '$-1$'], answer: 2, explanation: '$[-\\cos x]_0^\\pi=2$.' },
        { stem: '$\\displaystyle\\int e^x\\,dx$ bằng?', options: ['$e^x+C$', '$xe^{x-1}$', '$\\ln x+C$', '$e^x$'], answer: 0, explanation: '$\\int e^x dx=e^x+C$.' },
        { stem: 'Tính $\\displaystyle\\int_1^2 2x\\,dx$.', options: ['$3$', '$4$', '$1$', '$2$'], answer: 0, explanation: '$[x^2]_1^2=3$.' },
        { stem: 'Diện tích hình phẳng giới hạn $y=x^2$, $Ox$, $x=0$, $x=3$ là?', options: ['$9$', '$3$', '$27$', '$6$'], answer: 0, explanation: '$\\int_0^3 x^2 dx=9$.' },
        { stem: '$\\displaystyle\\int \\cos x\\,dx$ bằng?', options: ['$\\sin x+C$', '$-\\sin x+C$', '$\\cos x$', '$-\\cos x+C$'], answer: 0, explanation: '$\\int\\cos x dx=\\sin x+C$.' },
        { stem: 'Thể tích khối tròn xoay quay $y=x$ quanh $Ox$ từ $0$ đến $1$ là?', options: ['$\\dfrac{\\pi}{3}$', '$\\pi$', '$\\dfrac{\\pi}{2}$', '$\\dfrac{2\\pi}{3}$'], answer: 0, explanation: '$V=\\pi\\int_0^1 x^2 dx=\\dfrac{\\pi}{3}$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (2x+1)\\,dx$.', options: ['$2$', '$1$', '$3$', '$0$'], answer: 0, explanation: '$[x^2+x]_0^1=2$.' },
      ],
    },
    {
      examId: 'kt45-3', title: 'Kiểm tra 45′ #3 — Vectơ & tọa độ Oxyz', durationMin: 45,
      questions: [
        { stem: 'Cho $A(1;2;3)$, $B(3;0;1)$. Tọa độ $\\vec{AB}$ là?', options: ['$(2;-2;-2)$', '$(-2;2;2)$', '$(4;2;4)$', '$(2;2;2)$'], answer: 0, explanation: '$\\vec{AB}=B-A=(2;-2;-2)$.' },
        { stem: 'Độ dài của $\\vec{u}=(2;1;2)$ là?', options: ['$3$', '$5$', '$9$', '$\\sqrt{5}$'], answer: 0, explanation: '$|\\vec{u}|=\\sqrt{4+1+4}=3$.' },
        { stem: 'Trung điểm của $A(0;0;0)$ và $B(2;4;6)$ là?', options: ['$(1;2;3)$', '$(2;4;6)$', '$(1;1;1)$', '$(0;2;3)$'], answer: 0, explanation: 'Trung điểm $=\\left(\\tfrac{0+2}{2};\\tfrac{0+4}{2};\\tfrac{0+6}{2}\\right)$.' },
        { stem: 'Tích vô hướng $\\vec{u}\\cdot\\vec{v}$ với $\\vec{u}=(1;2;3)$, $\\vec{v}=(2;0;-1)$ là?', options: ['$-1$', '$5$', '$1$', '$2$'], answer: 0, explanation: '$2+0-3=-1$.' },
        { stem: 'Vectơ nào vuông góc với $\\vec{u}=(2;1;2)$?', options: ['$(1;-2;0)$', '$(1;1;1)$', '$(0;0;1)$', '$(1;0;1)$'], answer: 0, explanation: '$(2)(1)+(1)(-2)+(2)(0)=0$.' },
        { stem: 'Trọng tâm tam giác $A(1;1;1)$, $B(2;2;2)$, $C(3;3;3)$ là?', options: ['$(2;2;2)$', '$(6;6;6)$', '$(1;1;1)$', '$(3;3;3)$'], answer: 0, explanation: '$G=\\left(\\tfrac{1+2+3}{3};\\dots\\right)=(2;2;2)$.' },
        { stem: 'Góc giữa $\\vec{u}=(1;0;0)$ và $\\vec{v}=(0;1;0)$ là?', options: ['$90^\\circ$', '$0^\\circ$', '$45^\\circ$', '$180^\\circ$'], answer: 0, explanation: '$\\vec{u}\\cdot\\vec{v}=0$.' },
        { stem: 'Điểm nào nằm trên trục $Ox$?', options: ['$(3;0;0)$', '$(0;3;0)$', '$(0;0;3)$', '$(1;1;1)$'], answer: 0, explanation: 'Trên $Ox$: $y=z=0$.' },
        { stem: 'Điểm đối xứng của $A(2;-1;0)$ qua gốc $O$ là?', options: ['$(-2;1;0)$', '$(2;1;0)$', '$(-2;-1;0)$', '$(2;-1;0)$'], answer: 0, explanation: 'Đổi dấu các tọa độ.' },
        { stem: 'Hai vectơ $\\vec{u}=(1;1;1)$, $\\vec{v}=(2;2;2)$ có quan hệ gì?', options: ['Cùng phương ($\\vec{v}=2\\vec{u}$)', 'Vuông góc', 'Không cùng phương', 'Bằng nhau'], answer: 0, explanation: '$\\vec{v}=2\\vec{u}$.' },
      ],
    },
    {
      examId: 'kt45-4', title: 'Kiểm tra 45′ #4 — Mặt phẳng, đường thẳng, mặt cầu', durationMin: 45,
      questions: [
        { stem: 'Vectơ pháp tuyến của mặt phẳng $2x-3y+z-1=0$ là?', options: ['$(2;-3;1)$', '$(2;3;1)$', '$(2;-3;-1)$', '$(-1;2;-3)$'], answer: 0, explanation: 'Hệ số của $x,y,z$.' },
        { stem: 'Khoảng cách từ $O$ đến mặt phẳng $x+y+z-3=0$ là?', options: ['$\\sqrt{3}$', '$3$', '$1$', '$\\sqrt{2}$'], answer: 0, explanation: '$d=\\dfrac{|-3|}{\\sqrt{3}}=\\sqrt{3}$.' },
        { stem: 'Bán kính mặt cầu $(x-1)^2+(y+2)^2+z^2=9$ là?', options: ['$3$', '$9$', '$\\sqrt{3}$', '$1$'], answer: 0, explanation: '$R=\\sqrt{9}=3$.' },
        { stem: 'Tâm mặt cầu $x^2+y^2+z^2-2x-4y+1=0$ là?', options: ['$(1;2;0)$', '$(-1;-2;0)$', '$(2;4;0)$', '$(1;2;1)$'], answer: 0, explanation: '$I(a;b;c)$ với $a=1,b=2,c=0$.' },
        { stem: 'Vectơ chỉ phương của $d:\\dfrac{x-1}{2}=\\dfrac{y}{-1}=\\dfrac{z+2}{3}$ là?', options: ['$(2;-1;3)$', '$(1;0;-2)$', '$(2;1;3)$', '$(-2;1;3)$'], answer: 0, explanation: 'Mẫu số là tọa độ VTCP.' },
        { stem: 'Mặt phẳng qua $O$ với pháp tuyến $(1;2;2)$ có phương trình?', options: ['$x+2y+2z=0$', '$x+2y+2z-1=0$', '$2x+y+2z=0$', '$x+y+z=0$'], answer: 0, explanation: 'Qua $O$ ⇒ $D=0$.' },
        { stem: 'Điểm $M(1;1;1)$ có thuộc mặt phẳng $x+y+z-3=0$ không?', options: ['Có', 'Không', 'Không xác định', 'Chỉ khi đổi dấu'], answer: 0, explanation: '$1+1+1-3=0$.' },
        { stem: 'Khoảng cách từ $M(1;0;0)$ đến mặt phẳng $2x+2y+z+4=0$ là?', options: ['$2$', '$6$', '$3$', '$1$'], answer: 0, explanation: '$\\dfrac{|2+0+0+4|}{\\sqrt{4+4+1}}=\\dfrac{6}{3}=2$.' },
        { stem: 'Bán kính mặt cầu $x^2+y^2+z^2=16$ là?', options: ['$4$', '$16$', '$8$', '$2$'], answer: 0, explanation: '$R=\\sqrt{16}=4$.' },
        { stem: 'Vectơ pháp tuyến của mặt phẳng $3x-4z+5=0$ là?', options: ['$(3;0;-4)$', '$(3;-4;0)$', '$(3;-4;5)$', '$(3;0;4)$'], answer: 0, explanation: 'Thiếu $y$ ⇒ hệ số $y=0$.' },
      ],
    },
    {
      examId: 'kt45-5', title: 'Kiểm tra 45′ #5 — Xác suất có điều kiện & Thống kê', durationMin: 45,
      questions: [
        { stem: 'Cho $P(A\\cap B)=0{,}2$, $P(B)=0{,}4$. Tính $P(A\\mid B)$.', options: ['$0{,}5$', '$0{,}8$', '$0{,}08$', '$0{,}2$'], answer: 0, explanation: '$\\dfrac{0{,}2}{0{,}4}=0{,}5$.' },
        { stem: '$A,B$ độc lập, $P(A)=0{,}3$, $P(B)=0{,}5$. Tính $P(A\\cap B)$.', options: ['$0{,}15$', '$0{,}8$', '$0{,}2$', '$0{,}5$'], answer: 0, explanation: '$P(A)P(B)=0{,}15$.' },
        { stem: 'Khoảng biến thiên của mẫu $2,5,9,12$ là?', options: ['$10$', '$7$', '$2$', '$12$'], answer: 0, explanation: '$12-2=10$.' },
        { stem: 'Gieo một xúc xắc. Xác suất "số chẵn" biết "số $\\ge 3$" là?', options: ['$\\dfrac{1}{2}$', '$\\dfrac{1}{3}$', '$\\dfrac{1}{4}$', '$\\dfrac{2}{3}$'], answer: 0, explanation: '$B=\\{3,4,5,6\\}, A\\cap B=\\{4,6\\}\\Rightarrow 2/4$.' },
        { stem: 'Phương sai và độ lệch chuẩn đo đại lượng nào?', options: ['Độ phân tán của dữ liệu', 'Giá trị trung bình', 'Giá trị lớn nhất', 'Trung vị'], answer: 0, explanation: 'Đo mức độ phân tán quanh trung bình.' },
        { stem: 'Phương sai của mẫu $4,4,4,4$ là?', options: ['$0$', '$4$', '$16$', '$1$'], answer: 0, explanation: 'Mọi giá trị bằng trung bình ⇒ phương sai $=0$.' },
        { stem: 'Cho $P(A\\cap B)=0{,}1$, $P(A\\mid B)=0{,}5$. Tính $P(B)$.', options: ['$0{,}2$', '$0{,}05$', '$0{,}5$', '$0{,}6$'], answer: 0, explanation: '$P(B)=\\dfrac{0{,}1}{0{,}5}=0{,}2$.' },
        { stem: 'Khoảng tứ phân vị $\\Delta_Q$ của mẫu $1,3,5,7,9$ là?', options: ['$6$', '$4$', '$8$', '$2$'], answer: 0, explanation: '$Q_1=2, Q_3=8 \\Rightarrow \\Delta_Q=6$.' },
        { stem: 'Nếu $P(A\\mid B)=P(A)$ thì hai biến cố $A,B$?', options: ['Độc lập', 'Xung khắc', 'Đối nhau', 'Bằng nhau'], answer: 0, explanation: 'Định nghĩa biến cố độc lập.' },
        { stem: 'Độ lệch chuẩn $s$ bằng?', options: ['Căn bậc hai của phương sai', 'Bình phương phương sai', 'Trung bình', 'Phương sai'], answer: 0, explanation: '$s=\\sqrt{s^2}$.' },
      ],
    },
    {
      examId: 'kt45-6', title: 'Kiểm tra 45′ #6 — Khảo sát hàm số (tổng hợp)', durationMin: 45,
      questions: [
        { stem: 'Điểm cực tiểu của $y=x^3-3x+2$ có hoành độ?', options: ['$x=-1$', '$x=1$', '$x=0$', '$x=2$'], answer: 1, explanation: '$y\'=3x^2-3=0\\Rightarrow x=\\pm1$; $y\'\'(1)=6>0$ ⇒ cực tiểu tại $x=1$.' },
        { stem: 'Phương trình $y\'=0$ của $y=x^4-8x^2$ có mấy nghiệm?', options: ['$2$', '$4$', '$3$', '$1$'], answer: 2, explanation: '$y\'=4x^3-16x=4x(x^2-4)\\Rightarrow x=0,\\pm2$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{x-1}{x+1}$ là?', options: ['$y=1$', '$y=-1$', '$x=1$', '$x=-1$'], answer: 0, explanation: '$\\lim\\limits_{x\\to\\pm\\infty}y=1$.' },
        { stem: 'Đồ thị $y=x^3$ có điểm uốn tại?', options: ['$x=1$', '$x=-1$', '$x=2$', '$x=0$'], answer: 3, explanation: '$y\'\'=6x=0\\Rightarrow x=0$.' },
        { stem: 'GTLN của $y=4-x^2$ trên $\\mathbb{R}$ là?', options: ['$0$', '$4$', '$2$', '$-4$'], answer: 1, explanation: 'Đạt tại $x=0$, $y=4$.' },
        { stem: 'Đạo hàm của $y=2x^3-3x^2+1$ là?', options: ['$6x^2-6$', '$2x^2-3x$', '$6x^2-6x$', '$6x^2-3$'], answer: 2, explanation: '$y\'=6x^2-6x$.' },
        { stem: 'Hàm số nào nghịch biến trên $\\mathbb{R}$?', options: ['$y=x^3$', '$y=x^2$', '$y=x^4$', '$y=-x^3-x$'], answer: 3, explanation: '$y\'=-3x^2-1<0\\ \\forall x$.' },
        { stem: 'Tiệm cận đứng của $y=\\dfrac{1}{x-3}$ là?', options: ['$x=3$', '$x=-3$', '$y=3$', '$y=0$'], answer: 0, explanation: 'Mẫu $=0\\Leftrightarrow x=3$.' },
        { stem: 'Hàm $y=x^2-2x+3$ đạt cực tiểu tại?', options: ['$x=0$', '$x=2$', '$x=1$', '$x=-1$'], answer: 2, explanation: '$y\'=2x-2=0\\Rightarrow x=1$.' },
        { stem: 'Đồ thị hàm bậc ba cắt trục hoành tối đa mấy điểm?', options: ['$2$', '$3$', '$1$', 'vô số'], answer: 1, explanation: 'Phương trình bậc ba có tối đa 3 nghiệm.' },
      ],
    },
    {
      examId: 'kt45-7', title: 'Kiểm tra 45′ #7 — Nguyên hàm & Tích phân (nâng cao)', durationMin: 45,
      questions: [
        { stem: '$\\displaystyle\\int (2x+3)\\,dx$ bằng?', options: ['$2x+3$', '$2$', '$x^2+3x+C$', '$x^2+3$'], answer: 2, explanation: '$\\int(2x+3)dx=x^2+3x+C$.' },
        { stem: 'Tính $\\displaystyle\\int_0^2 x\\,dx$.', options: ['$2$', '$4$', '$1$', '$\\tfrac12$'], answer: 0, explanation: '$[x^2/2]_0^2=2$.' },
        { stem: '$\\displaystyle\\int \\sin(2x)\\,dx$ bằng?', options: ['$\\tfrac12\\cos 2x+C$', '$-\\cos 2x+C$', '$2\\cos 2x$', '$-\\tfrac12\\cos 2x+C$'], answer: 3, explanation: '$\\int\\sin 2x\\,dx=-\\tfrac12\\cos 2x+C$.' },
        { stem: 'Tính $\\displaystyle\\int_1^e \\dfrac{1}{x}\\,dx$.', options: ['$e$', '$1$', '$0$', '$e-1$'], answer: 1, explanation: '$[\\ln x]_1^e=1$.' },
        { stem: '$\\displaystyle\\int (3x^2-2x)\\,dx$ bằng?', options: ['$x^3-x^2+C$', '$6x-2$', '$3x^3-2x^2$', '$x^3-2x$'], answer: 0, explanation: '$x^3-x^2+C$.' },
        { stem: 'Diện tích hình phẳng dưới $y=x^3$ trên $[0;2]$ là?', options: ['$8$', '$2$', '$4$', '$16$'], answer: 2, explanation: '$\\int_0^2 x^3 dx=[x^4/4]_0^2=4$.' },
        { stem: '$\\displaystyle\\int e^{-x}\\,dx$ bằng?', options: ['$e^{-x}+C$', '$-e^{-x}+C$', '$-e^{x}$', '$e^{-x}$'], answer: 1, explanation: '$\\int e^{-x}dx=-e^{-x}+C$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 4x^3\\,dx$.', options: ['$4$', '$\\tfrac12$', '$2$', '$1$'], answer: 3, explanation: '$[x^4]_0^1=1$.' },
        { stem: '$\\displaystyle\\int \\dfrac{1}{x^2}\\,dx$ bằng?', options: ['$-\\dfrac{1}{x}+C$', '$\\dfrac{1}{x}+C$', '$-\\dfrac{2}{x^3}$', '$\\ln x^2$'], answer: 0, explanation: '$\\int x^{-2}dx=-x^{-1}+C$.' },
        { stem: 'Thể tích khi quay $y=x^2$ quanh $Ox$ từ $0$ đến $1$ là?', options: ['$\\dfrac{\\pi}{3}$', '$\\pi$', '$\\dfrac{\\pi}{5}$', '$\\dfrac{2\\pi}{5}$'], answer: 2, explanation: '$V=\\pi\\int_0^1 x^4 dx=\\dfrac{\\pi}{5}$.' },
      ],
    },
    {
      examId: 'kt45-8', title: 'Kiểm tra 45′ #8 — Tổng hợp giữa kỳ', durationMin: 45,
      questions: [
        { stem: 'Hàm $y=x^2-4x+1$ đạt cực tiểu tại?', options: ['$x=-2$', '$x=2$', '$x=1$', '$x=4$'], answer: 1, explanation: '$y\'=2x-4=0\\Rightarrow x=2$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 3x^2\\,dx$.', options: ['$1$', '$3$', '$\\tfrac13$', '$2$'], answer: 0, explanation: '$[x^3]_0^1=1$.' },
        { stem: 'Cho $P(A\\cap B)=0{,}3$, $P(B)=0{,}6$. Tính $P(A\\mid B)$.', options: ['$0{,}18$', '$0{,}9$', '$0{,}5$', '$0{,}3$'], answer: 2, explanation: '$0{,}3/0{,}6=0{,}5$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{x-2}{x+3}$ là?', options: ['$y=-2$', '$x=-3$', '$y=2$', '$y=1$'], answer: 3, explanation: '$\\lim y=1$.' },
        { stem: 'Số điểm cực trị của $y=x^4-2x^2$ là?', options: ['$1$', '$3$', '$2$', '$0$'], answer: 1, explanation: '$y\'=4x(x^2-1)$ có 3 nghiệm.' },
        { stem: '$\\displaystyle\\int \\cos x\\,dx$ bằng?', options: ['$\\sin x+C$', '$-\\sin x+C$', '$\\cos x$', '$-\\cos x+C$'], answer: 0, explanation: '$\\int\\cos x dx=\\sin x+C$.' },
        { stem: 'Khoảng biến thiên của mẫu $3,8,15$ là?', options: ['$15$', '$3$', '$12$', '$8$'], answer: 2, explanation: '$15-3=12$.' },
        { stem: 'Khoảng cách từ $O$ đến mặt phẳng $x+2y+2z-6=0$ là?', options: ['$6$', '$3$', '$1$', '$2$'], answer: 3, explanation: '$\\dfrac{6}{\\sqrt{1+4+4}}=2$.' },
        { stem: 'Độ dài $\\vec{AB}$ với $A(0;0;0)$, $B(1;2;2)$ là?', options: ['$3$', '$5$', '$9$', '$\\sqrt5$'], answer: 0, explanation: '$\\sqrt{1+4+4}=3$.' },
        { stem: 'Cho $y=x^3-3x$. Giá trị $y(1)$ là?', options: ['$2$', '$-2$', '$0$', '$-4$'], answer: 1, explanation: '$1-3=-2$.' },
      ],
    },
    {
      examId: 'kt45-9', title: 'Kiểm tra 45′ #9 — Hình học tọa độ không gian', durationMin: 45,
      questions: [
        { stem: 'Vectơ pháp tuyến của mặt phẳng $(Oxy)$ (tức $z=0$) là?', options: ['$(1;0;0)$', '$(0;1;0)$', '$(0;0;1)$', '$(1;1;0)$'], answer: 2, explanation: 'Mặt phẳng $z=0$ có VTPT $(0;0;1)$.' },
        { stem: 'Giao điểm của $d:x=t,y=2t,z=3t$ với mặt phẳng $z=3$ là?', options: ['$(1;2;3)$', '$(0;0;3)$', '$(3;6;9)$', '$(1;1;1)$'], answer: 0, explanation: '$z=3t=3\\Rightarrow t=1$.' },
        { stem: 'Phương trình mặt cầu tâm $O$ bán kính $2$ là?', options: ['$x^2+y^2+z^2=2$', '$x^2+y^2+z^2=4$', '$x^2+y^2+z^2=1$', '$x^2+y^2+z^2=16$'], answer: 1, explanation: '$R^2=4$.' },
        { stem: 'Khoảng cách từ $M(2;0;0)$ đến gốc $O$ là?', options: ['$4$', '$1$', '$\\sqrt2$', '$2$'], answer: 3, explanation: '$OM=2$.' },
        { stem: 'Hai mặt phẳng $x+y+z=0$ và $2x+2y+2z=5$ có vị trí?', options: ['Song song', 'Cắt nhau', 'Trùng nhau', 'Vuông góc'], answer: 0, explanation: 'VTPT cùng phương, hằng số khác ⇒ song song.' },
        { stem: 'Vectơ pháp tuyến của $2x-y+2z-3=0$ là?', options: ['$(2;1;2)$', '$(2;-1;2)$', '$(2;-1;-2)$', '$(-2;1;2)$'], answer: 1, explanation: 'Hệ số $x,y,z$.' },
        { stem: 'Trung điểm của $A(1;3;5)$ và $B(3;1;-1)$ là?', options: ['$(4;4;4)$', '$(1;1;1)$', '$(2;2;2)$', '$(2;2;3)$'], answer: 2, explanation: '$\\left(\\tfrac{1+3}{2};\\tfrac{3+1}{2};\\tfrac{5-1}{2}\\right)$.' },
        { stem: 'Khoảng cách từ $O$ đến mặt phẳng $z=5$ là?', options: ['$5$', '$0$', '$1$', '$25$'], answer: 0, explanation: '$\\dfrac{|-5|}{1}=5$.' },
        { stem: 'Đường thẳng qua $O$ có VTCP $(1;1;1)$ có dạng tham số?', options: ['$x=1,y=1,z=1$', '$x=t,y=2t,z=3t$', '$x=0$', '$x=t,y=t,z=t$'], answer: 3, explanation: 'Qua $O$, VTCP $(1;1;1)$.' },
        { stem: 'Tâm mặt cầu $x^2+y^2+z^2-6z=0$ là?', options: ['$(0;0;-3)$', '$(0;0;3)$', '$(0;0;6)$', '$(0;3;0)$'], answer: 1, explanation: '$-2c=-6\\Rightarrow c=3$, $I(0;0;3)$.' },
      ],
    },
    {
      examId: 'kt45-10', title: 'Kiểm tra 45′ #10 — Tổng hợp cuối kỳ', durationMin: 45,
      questions: [
        { stem: 'Số điểm cực trị của $y=x^3-3x^2+4$ là?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 2, explanation: '$y\'=3x^2-6x=3x(x-2)$ có 2 nghiệm.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (x+1)\\,dx$.', options: ['$\\tfrac32$', '$1$', '$2$', '$\\tfrac12$'], answer: 0, explanation: '$[x^2/2+x]_0^1=\\tfrac32$.' },
        { stem: 'Cho $P(A)=0{,}6$, $P(B\\mid A)=0{,}5$. Tính $P(A\\cap B)$.', options: ['$0{,}6$', '$0{,}3$', '$1{,}1$', '$0{,}5$'], answer: 1, explanation: '$P(A)P(B\\mid A)=0{,}3$.' },
        { stem: 'GTNN của $y=x^2-6x+10$ trên $\\mathbb{R}$ là?', options: ['$10$', '$3$', '$0$', '$1$'], answer: 3, explanation: '$y=(x-3)^2+1\\ge 1$.' },
        { stem: 'Tiệm cận đứng của $y=\\dfrac{2x+1}{x-1}$ là?', options: ['$x=1$', '$y=2$', '$x=-1$', '$y=1$'], answer: 0, explanation: 'Mẫu $=0\\Leftrightarrow x=1$.' },
        { stem: '$\\displaystyle\\int \\sin x\\,dx$ bằng?', options: ['$\\cos x+C$', '$\\sin x+C$', '$-\\cos x+C$', '$-\\sin x+C$'], answer: 2, explanation: '$\\int\\sin x dx=-\\cos x+C$.' },
        { stem: 'Độ dài $\\vec{u}=(3;4;0)$ là?', options: ['$7$', '$5$', '$25$', '$\\sqrt7$'], answer: 1, explanation: '$\\sqrt{9+16}=5$.' },
        { stem: 'Trung vị của mẫu $2,4,6,8,10$ là?', options: ['$4$', '$8$', '$5$', '$6$'], answer: 3, explanation: 'Số ở giữa là $6$.' },
        { stem: 'Đạo hàm của $y=x^2$ là?', options: ['$2x$', '$x^2$', '$2$', '$x$'], answer: 0, explanation: '$(x^2)\'=2x$.' },
        { stem: 'Bán kính mặt cầu $(x-2)^2+y^2+z^2=9$ là?', options: ['$9$', '$\\sqrt3$', '$3$', '$6$'], answer: 2, explanation: '$R=\\sqrt9=3$.' },
      ],
    },
    {
      examId: 'hk-1', title: 'Đề thi Học kỳ #1 — Tổng hợp Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^3-3x^2$ đồng biến trên?', options: ['$(0;2)$', '$(-\\infty;0)$ và $(2;+\\infty)$', '$\\mathbb{R}$', '$(2;+\\infty)$'], answer: 1, explanation: '$y\'=3x(x-2)>0\\Leftrightarrow x<0$ hoặc $x>2$.' },
        { stem: 'Giá trị cực đại của $y=-x^2+4x-1$ là?', options: ['$1$', '$2$', '$3$', '$4$'], answer: 2, explanation: '$x=2\\Rightarrow y=3$.' },
        { stem: 'GTLN của $y=x^3-3x$ trên $[0;2]$ là?', options: ['$2$', '$0$', '$-2$', '$6$'], answer: 0, explanation: '$y(2)=2$ là lớn nhất.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 x^2\\,dx$.', options: ['$1$', '$3$', '$\\tfrac12$', '$\\tfrac13$'], answer: 3, explanation: '$[x^3/3]_0^1=\\tfrac13$.' },
        { stem: '$\\displaystyle\\int (2x+1)\\,dx$ bằng?', options: ['$2$', '$x^2+x+C$', '$2x^2+x$', '$x^2+1$'], answer: 1, explanation: '$x^2+x+C$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{3x-1}{x+2}$ là?', options: ['$y=3$', '$x=-2$', '$y=-1$', '$x=3$'], answer: 0, explanation: '$\\lim y=3$.' },
        { stem: 'Số điểm cực trị của $y=x^4-2x^2+1$ là?', options: ['$1$', '$2$', '$3$', '$0$'], answer: 2, explanation: '$y\'=4x(x^2-1)$ có 3 nghiệm.' },
        { stem: 'Thể tích khi quay $y=\\sqrt{x}$ quanh $Ox$ từ $0$ đến $1$ là?', options: ['$\\pi$', '$\\dfrac{\\pi}{2}$', '$\\dfrac{\\pi}{3}$', '$2\\pi$'], answer: 1, explanation: '$V=\\pi\\int_0^1 x\\,dx=\\dfrac{\\pi}{2}$.' },
        { stem: 'Cho $P(A\\cap B)=0{,}2$, $P(B)=0{,}5$. Tính $P(A\\mid B)$.', options: ['$0{,}1$', '$0{,}25$', '$0{,}7$', '$0{,}4$'], answer: 3, explanation: '$0{,}2/0{,}5=0{,}4$.' },
        { stem: 'Độ dài $\\vec{AB}$ với $A(1;0;0)$, $B(1;3;4)$ là?', options: ['$5$', '$7$', '$25$', '$\\sqrt7$'], answer: 0, explanation: '$\\sqrt{0+9+16}=5$.' },
        { stem: 'Vectơ pháp tuyến của $2x+y-2z+1=0$ là?', options: ['$(2;1;2)$', '$(2;-1;-2)$', '$(2;1;-2)$', '$(-2;1;2)$'], answer: 2, explanation: 'Hệ số $x,y,z$.' },
        { stem: 'Tâm mặt cầu $x^2+y^2+z^2-4x=0$ là?', options: ['$(-2;0;0)$', '$(2;0;0)$', '$(4;0;0)$', '$(0;0;2)$'], answer: 1, explanation: '$-2a=-4\\Rightarrow a=2$.' },
        { stem: 'Khoảng biến thiên của mẫu $5,9,14$ là?', options: ['$14$', '$5$', '$19$', '$9$'], answer: 3, explanation: '$14-5=9$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi/2}\\cos x\\,dx$.', options: ['$1$', '$0$', '$2$', '$-1$'], answer: 0, explanation: '$[\\sin x]_0^{\\pi/2}=1$.' },
        { stem: 'Đạo hàm của $y=\\ln x$ là?', options: ['$x$', '$e^x$', '$\\dfrac{1}{x}$', '$\\ln x$'], answer: 2, explanation: '$(\\ln x)\'=\\dfrac{1}{x}$.' },
      ],
    },
    {
      examId: 'hk-2', title: 'Đề thi Học kỳ #2 — Tổng hợp Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=-x^3+3x$ đồng biến trên?', options: ['$(-1;1)$', '$(0;1)$', '$\\mathbb{R}$', '$(1;+\\infty)$'], answer: 0, explanation: '$y\'=-3x^2+3>0\\Leftrightarrow -1<x<1$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 e^x\\,dx$.', options: ['$e$', '$1$', '$e-1$', '$0$'], answer: 2, explanation: '$[e^x]_0^1=e-1$.' },
        { stem: 'Giá trị cực tiểu của $y=x^3-3x$ là?', options: ['$2$', '$-2$', '$0$', '$-4$'], answer: 1, explanation: 'Tại $x=1$, $y=-2$.' },
        { stem: 'Tiệm cận đứng của $y=\\dfrac{x+1}{x-2}$ là?', options: ['$y=2$', '$x=-1$', '$y=1$', '$x=2$'], answer: 3, explanation: 'Mẫu $=0\\Leftrightarrow x=2$.' },
        { stem: '$\\displaystyle\\int x\\,dx$ bằng?', options: ['$\\dfrac{x^2}{2}+C$', '$1$', '$2x$', '$x^2+C$'], answer: 0, explanation: '$\\dfrac{x^2}{2}+C$.' },
        { stem: 'Phương trình $y\'=0$ của $y=x^3+3x^2$ có mấy nghiệm?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 2, explanation: '$y\'=3x(x+2)\\Rightarrow x=0,-2$.' },
        { stem: 'Khoảng cách từ $M(1;1;1)$ đến mặt phẳng $x+y+z-6=0$ là?', options: ['$3$', '$\\sqrt3$', '$1$', '$\\sqrt2$'], answer: 1, explanation: '$\\dfrac{|3-6|}{\\sqrt3}=\\sqrt3$.' },
        { stem: '$A,B$ độc lập, $P(A)=0{,}5$, $P(B)=0{,}4$. Tính $P(A\\cap B)$.', options: ['$0{,}9$', '$0{,}1$', '$0{,}45$', '$0{,}2$'], answer: 3, explanation: '$0{,}5\\cdot0{,}4=0{,}2$.' },
        { stem: 'Tính $\\displaystyle\\int_1^2 3x^2\\,dx$.', options: ['$7$', '$8$', '$9$', '$6$'], answer: 0, explanation: '$[x^3]_1^2=8-1=7$.' },
        { stem: 'Vectơ chỉ phương của $d:x=2-t,\\ y=1+2t,\\ z=3t$ là?', options: ['$(2;1;0)$', '$(1;2;3)$', '$(-1;2;3)$', '$(1;-2;3)$'], answer: 2, explanation: 'Hệ số của $t$: $(-1;2;3)$.' },
        { stem: 'Số trung bình của mẫu $2,4,6,8$ là?', options: ['$4$', '$5$', '$6$', '$20$'], answer: 1, explanation: '$\\dfrac{20}{4}=5$.' },
        { stem: 'Mặt cầu tâm $I(0;1;0)$ bán kính $2$ có phương trình?', options: ['$x^2+y^2+z^2=4$', '$x^2+(y-1)^2+z^2=2$', '$(x-1)^2+y^2+z^2=4$', '$x^2+(y-1)^2+z^2=4$'], answer: 3, explanation: 'Tâm $(0;1;0)$, $R^2=4$.' },
        { stem: 'GTNN của $y=x+\\dfrac{4}{x}$ trên $(0;+\\infty)$ là?', options: ['$4$', '$2$', '$8$', '$0$'], answer: 0, explanation: 'Đạt tại $x=2$ (Cô-si), $y=4$.' },
        { stem: '$\\displaystyle\\int \\cos(2x)\\,dx$ bằng?', options: ['$-\\tfrac12\\sin2x+C$', '$2\\sin2x+C$', '$\\tfrac12\\sin2x+C$', '$\\sin2x+C$'], answer: 2, explanation: '$\\tfrac12\\sin2x+C$.' },
        { stem: 'Đạo hàm của $y=e^{2x}$ là?', options: ['$e^{2x}$', '$2e^{2x}$', '$\\tfrac12 e^{2x}$', '$2e^x$'], answer: 1, explanation: '$(e^{2x})\'=2e^{2x}$.' },
      ],
    },
    {
      examId: 'hk-3', title: 'Đề thi Học kỳ #3 — Tổng hợp Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^3+1$ đồng biến trên?', options: ['$(0;+\\infty)$', '$(-\\infty;0)$', '$\\mathbb{R}$', 'không khoảng nào'], answer: 2, explanation: '$y\'=3x^2\\ge0$ ⇒ đồng biến trên $\\mathbb{R}$.' },
        { stem: 'Tính $\\displaystyle\\int_0^2 (x+1)\\,dx$.', options: ['$4$', '$2$', '$6$', '$3$'], answer: 0, explanation: '$[x^2/2+x]_0^2=2+2=4$.' },
        { stem: 'GTLN của $y=-x^2+2x+3$ trên $\\mathbb{R}$ là?', options: ['$1$', '$2$', '$3$', '$4$'], answer: 3, explanation: 'Tại $x=1$, $y=4$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{x+2}{2x-1}$ là?', options: ['$y=2$', '$y=\\tfrac12$', '$x=\\tfrac12$', '$y=1$'], answer: 1, explanation: '$\\lim y=\\dfrac{1}{2}$.' },
        { stem: '$\\displaystyle\\int 6x^2\\,dx$ bằng?', options: ['$6x+C$', '$3x^3+C$', '$2x^3+C$', '$x^3+C$'], answer: 2, explanation: '$2x^3+C$.' },
        { stem: 'Giá trị cực đại của $y=x^3-12x$ là?', options: ['$16$', '$-16$', '$0$', '$8$'], answer: 0, explanation: '$y\'=3x^2-12=0\\Rightarrow x=\\pm2$; tại $x=-2$, $y=16$.' },
        { stem: 'Độ dài $\\vec{u}=(1;2;2)$ là?', options: ['$5$', '$3$', '$9$', '$\\sqrt5$'], answer: 1, explanation: '$\\sqrt{1+4+4}=3$.' },
        { stem: 'Cho $P(A\\cap B)=0{,}12$, $P(A\\mid B)=0{,}3$. Tính $P(B)$.', options: ['$0{,}036$', '$0{,}3$', '$0{,}12$', '$0{,}4$'], answer: 3, explanation: '$P(B)=\\dfrac{0{,}12}{0{,}3}=0{,}4$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi}\\sin x\\,dx$.', options: ['$0$', '$1$', '$2$', '$-1$'], answer: 2, explanation: '$[-\\cos x]_0^\\pi=2$.' },
        { stem: 'Vectơ pháp tuyến của mặt phẳng $(Oxz)$ (tức $y=0$) là?', options: ['$(0;1;0)$', '$(1;0;0)$', '$(0;0;1)$', '$(1;1;0)$'], answer: 0, explanation: 'Mặt phẳng $y=0$ có VTPT $(0;1;0)$.' },
        { stem: 'Phương sai của mẫu $2,2,2$ là?', options: ['$2$', '$0$', '$1$', '$4$'], answer: 1, explanation: 'Mọi giá trị bằng nhau ⇒ phương sai $0$.' },
        { stem: 'Số điểm cực trị của $y=x^3$ là?', options: ['$1$', '$2$', '$3$', '$0$'], answer: 3, explanation: '$y\'=3x^2\\ge0$ không đổi dấu ⇒ 0 cực trị.' },
        { stem: 'Khoảng cách từ $O$ đến mặt phẳng $2x-y+2z-9=0$ là?', options: ['$3$', '$9$', '$1$', '$\\sqrt3$'], answer: 0, explanation: '$\\dfrac{|-9|}{\\sqrt{4+1+4}}=3$.' },
        { stem: 'Tính $\\displaystyle\\int_1^{e^2} \\dfrac{1}{x}\\,dx$.', options: ['$e^2$', '$1$', '$2$', '$e$'], answer: 2, explanation: '$[\\ln x]_1^{e^2}=2$.' },
        { stem: 'Đạo hàm của $y=\\sin x$ là?', options: ['$-\\cos x$', '$\\cos x$', '$\\sin x$', '$-\\sin x$'], answer: 1, explanation: '$(\\sin x)\'=\\cos x$.' },
      ],
    },
    {
      examId: 'hk-4', title: 'Đề thi Học kỳ #4 — Tổng hợp Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^3-6x^2+9x$ đồng biến trên?', options: ['$(1;3)$', '$\\mathbb{R}$', '$(-\\infty;1)$ và $(3;+\\infty)$', '$(3;+\\infty)$'], answer: 2, explanation: '$y\'=3(x-1)(x-3)>0\\Leftrightarrow x<1$ hoặc $x>3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 4x^3\\,dx$.', options: ['$1$', '$4$', '$\\tfrac12$', '$2$'], answer: 0, explanation: '$[x^4]_0^1=1$.' },
        { stem: 'Giá trị cực tiểu của $y=x^2-4x+1$ là?', options: ['$1$', '$3$', '$0$', '$-3$'], answer: 3, explanation: 'Tại $x=2$, $y=-3$.' },
        { stem: 'Tiệm cận đứng của $y=\\dfrac{2x}{x+4}$ là?', options: ['$x=4$', '$x=-4$', '$y=2$', '$x=2$'], answer: 1, explanation: 'Mẫu $=0\\Leftrightarrow x=-4$.' },
        { stem: '$\\displaystyle\\int (x^2+1)\\,dx$ bằng?', options: ['$2x$', '$x^3+x$', '$\\dfrac{x^3}{3}+x+C$', '$x^3+C$'], answer: 2, explanation: '$\\dfrac{x^3}{3}+x+C$.' },
        { stem: 'GTLN của $y=x^3-3x^2$ trên $[1;3]$ là?', options: ['$0$', '$-2$', '$-4$', '$27$'], answer: 0, explanation: '$y(1)=-2,y(2)=-4,y(3)=0$.' },
        { stem: 'Khoảng cách từ $A(2;1;0)$ đến mặt phẳng $x-2y+2z+1=0$ là?', options: ['$1$', '$3$', '$\\tfrac{2}{3}$', '$\\tfrac13$'], answer: 3, explanation: '$\\dfrac{|2-2+0+1|}{3}=\\dfrac13$.' },
        { stem: 'Cho $P(A)=0{,}4$, $P(A\\cap B)=0{,}1$. Tính $P(B\\mid A)$.', options: ['$0{,}04$', '$0{,}25$', '$0{,}5$', '$0{,}1$'], answer: 1, explanation: '$\\dfrac{0{,}1}{0{,}4}=0{,}25$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi/2}\\sin x\\,dx$.', options: ['$0$', '$-1$', '$1$', '$2$'], answer: 2, explanation: '$[-\\cos x]_0^{\\pi/2}=1$.' },
        { stem: 'VTPT mặt phẳng qua $A(1;0;0),B(0;1;0),C(0;0;1)$ là?', options: ['$(1;1;1)$', '$(1;1;0)$', '$(1;0;1)$', '$(0;1;1)$'], answer: 0, explanation: 'Mặt phẳng $x+y+z=1$.' },
        { stem: 'Trung vị của mẫu $1,3,3,6,7,8,9$ là?', options: ['$3$', '$7$', '$8$', '$6$'], answer: 3, explanation: 'Số ở giữa (vị trí 4) là $6$.' },
        { stem: 'Tâm mặt cầu $x^2+y^2+z^2+2x-4y=0$ là?', options: ['$(1;-2;0)$', '$(-1;2;0)$', '$(2;-4;0)$', '$(-1;2;1)$'], answer: 1, explanation: '$-2a=2\\Rightarrow a=-1$; $-2b=-4\\Rightarrow b=2$.' },
        { stem: 'Số nghiệm thực của $x^3-3x=0$ là?', options: ['$1$', '$2$', '$3$', '$0$'], answer: 2, explanation: '$x(x^2-3)=0\\Rightarrow x=0,\\pm\\sqrt3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\ln 2} e^x\\,dx$.', options: ['$1$', '$2$', '$\\ln 2$', '$0$'], answer: 0, explanation: '$[e^x]_0^{\\ln2}=2-1=1$.' },
        { stem: 'Đạo hàm của $y=\\cos x$ là?', options: ['$\\sin x$', '$\\cos x$', '$\\tan x$', '$-\\sin x$'], answer: 3, explanation: '$(\\cos x)\'=-\\sin x$.' },
      ],
    },
    {
      examId: 'hk-5', title: 'Đề thi Học kỳ #5 — Tổng hợp Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^4-4x^2$ đồng biến trên?', options: ['$(0;\\sqrt2)$', '$(-\\sqrt2;0)$ và $(\\sqrt2;+\\infty)$', '$\\mathbb{R}$', '$(2;+\\infty)$'], answer: 1, explanation: '$y\'=4x(x^2-2)>0$ trên $(-\\sqrt2;0)\\cup(\\sqrt2;+\\infty)$.' },
        { stem: 'Tính $\\displaystyle\\int_0^2 3x^2\\,dx$.', options: ['$2$', '$4$', '$6$', '$8$'], answer: 3, explanation: '$[x^3]_0^2=8$.' },
        { stem: 'GTNN của $y=x^2+1$ trên $\\mathbb{R}$ là?', options: ['$1$', '$0$', '$-1$', '$2$'], answer: 0, explanation: 'Đạt tại $x=0$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{5x}{x-1}$ là?', options: ['$x=1$', '$y=1$', '$y=5$', '$x=5$'], answer: 2, explanation: '$\\lim y=5$.' },
        { stem: '$\\displaystyle\\int (2x-3)\\,dx$ bằng?', options: ['$2$', '$x^2-3x+C$', '$2x^2-3x$', '$x^2-3$'], answer: 1, explanation: '$x^2-3x+C$.' },
        { stem: 'Số điểm cực trị của $y=x^4-4x^2$ là?', options: ['$1$', '$2$', '$3$', '$0$'], answer: 2, explanation: '$y\'=4x(x^2-2)$ có 3 nghiệm.' },
        { stem: 'Độ dài $\\vec{AB}$ với $A(0;0;0),B(2;3;6)$ là?', options: ['$7$', '$5$', '$49$', '$\\sqrt7$'], answer: 0, explanation: '$\\sqrt{4+9+36}=7$.' },
        { stem: 'Cho $P(A\\mid B)=0{,}6$, $P(B)=0{,}5$. Tính $P(A\\cap B)$.', options: ['$1{,}1$', '$0{,}12$', '$0{,}5$', '$0{,}3$'], answer: 3, explanation: '$0{,}6\\cdot0{,}5=0{,}3$.' },
        { stem: 'Tính $\\displaystyle\\int_1^2 (2x+1)\\,dx$.', options: ['$2$', '$4$', '$6$', '$3$'], answer: 1, explanation: '$[x^2+x]_1^2=6-2=4$.' },
        { stem: 'Mặt phẳng qua $O$ với pháp tuyến $(3;0;4)$ có phương trình?', options: ['$3x+4y=0$', '$4x+3z=0$', '$3x+4z=0$', '$3x+4z+1=0$'], answer: 2, explanation: 'Qua $O$ ⇒ $3x+4z=0$.' },
        { stem: 'Số trung bình của $10,20,30,40$ là?', options: ['$25$', '$30$', '$20$', '$100$'], answer: 0, explanation: '$\\dfrac{100}{4}=25$.' },
        { stem: 'Bán kính mặt cầu $x^2+y^2+z^2-2x-2y-2z=0$ là?', options: ['$3$', '$1$', '$9$', '$\\sqrt3$'], answer: 3, explanation: '$R=\\sqrt{1+1+1-0}=\\sqrt3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi/2}\\cos x\\,dx$.', options: ['$0$', '$1$', '$2$', '$-1$'], answer: 1, explanation: '$[\\sin x]_0^{\\pi/2}=1$.' },
        { stem: 'Đạo hàm của $y=2x^3$ là?', options: ['$6x^2$', '$2x^2$', '$3x^2$', '$6x$'], answer: 0, explanation: '$(2x^3)\'=6x^2$.' },
        { stem: 'Tiệm cận đứng của $y=\\dfrac{3}{2x-6}$ là?', options: ['$x=-3$', '$x=6$', '$x=3$', '$x=2$'], answer: 2, explanation: '$2x-6=0\\Leftrightarrow x=3$.' },
      ],
    },
    {
      examId: 'ck-1', title: 'Đề thi Cuối kỳ #1 — Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^3-3x^2+2$ đồng biến trên?', options: ['$(0;2)$', '$\\mathbb{R}$', '$(2;+\\infty)$', '$(-\\infty;0)$ và $(2;+\\infty)$'], answer: 3, explanation: '$y\'=3x(x-2)>0\\Leftrightarrow x<0$ hoặc $x>2$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (3x^2+2x)\\,dx$.', options: ['$1$', '$2$', '$3$', '$\\tfrac12$'], answer: 1, explanation: '$[x^3+x^2]_0^1=2$.' },
        { stem: 'Giá trị cực đại của $y=-x^3+3x$ là?', options: ['$2$', '$-2$', '$0$', '$1$'], answer: 0, explanation: 'Tại $x=1$, $y=2$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{4x-1}{2x+3}$ là?', options: ['$y=4$', '$x=-\\tfrac32$', '$y=2$', '$y=\\tfrac12$'], answer: 2, explanation: '$\\lim y=\\dfrac{4}{2}=2$.' },
        { stem: '$\\displaystyle\\int \\sin(3x)\\,dx$ bằng?', options: ['$\\tfrac13\\cos3x+C$', '$-\\cos3x+C$', '$3\\cos3x$', '$-\\tfrac13\\cos3x+C$'], answer: 3, explanation: '$-\\tfrac13\\cos3x+C$.' },
        { stem: 'GTNN của $y=x^3-3x$ trên $[-2;0]$ là?', options: ['$2$', '$-2$', '$0$', '$-1$'], answer: 1, explanation: '$y(-2)=-2,y(-1)=2,y(0)=0$.' },
        { stem: 'Khoảng cách từ $O$ đến mặt phẳng $2x+y+2z-12=0$ là?', options: ['$4$', '$12$', '$2$', '$\\sqrt2$'], answer: 0, explanation: '$\\dfrac{12}{3}=4$.' },
        { stem: 'Cho $P(A\\cap B)=0{,}15$, $P(B)=0{,}3$. Tính $P(A\\mid B)$.', options: ['$0{,}045$', '$0{,}3$', '$0{,}5$', '$0{,}15$'], answer: 2, explanation: '$0{,}15/0{,}3=0{,}5$.' },
        { stem: 'Tính $\\displaystyle\\int_1^e \\dfrac{2}{x}\\,dx$.', options: ['$1$', '$2$', '$e$', '$2e$'], answer: 1, explanation: '$2[\\ln x]_1^e=2$.' },
        { stem: 'Mặt cầu đường kính $AB$ với $A(0;0;0),B(2;0;0)$ có phương trình?', options: ['$x^2+y^2+z^2=1$', '$(x-2)^2+y^2+z^2=1$', '$(x-1)^2+y^2+z^2=4$', '$(x-1)^2+y^2+z^2=1$'], answer: 3, explanation: 'Tâm $(1;0;0)$, $R=1$.' },
        { stem: 'Trung vị của mẫu $4,6,8,10$ là?', options: ['$6$', '$8$', '$7$', '$9$'], answer: 2, explanation: '$\\dfrac{6+8}{2}=7$.' },
        { stem: 'Số điểm cực trị của $y=x^3-3x^2+3x-1$ là?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 0, explanation: '$y\'=3(x-1)^2\\ge0$ không đổi dấu.' },
        { stem: 'Độ dài vectơ $\\vec{u}=(2;-1;2)$ là?', options: ['$5$', '$3$', '$9$', '$\\sqrt5$'], answer: 1, explanation: '$\\sqrt{4+1+4}=3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 e^{2x}\\,dx$.', options: ['$e^2-1$', '$2(e^2-1)$', '$e^2$', '$\\tfrac12(e^2-1)$'], answer: 3, explanation: '$\\tfrac12[e^{2x}]_0^1=\\tfrac12(e^2-1)$.' },
        { stem: 'Đạo hàm của $y=\\ln(2x)$ là?', options: ['$\\dfrac{1}{2x}$', '$2x$', '$\\dfrac{1}{x}$', '$\\ln 2$'], answer: 2, explanation: '$\\dfrac{2}{2x}=\\dfrac{1}{x}$.' },
      ],
    },
    {
      examId: 'ck-2', title: 'Đề thi Cuối kỳ #2 — Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^3-3x^2-9x$ đồng biến trên?', options: ['$(-1;3)$', '$\\mathbb{R}$', '$(-\\infty;-1)$ và $(3;+\\infty)$', '$(3;+\\infty)$'], answer: 2, explanation: '$y\'=3(x-3)(x+1)>0\\Leftrightarrow x<-1$ hoặc $x>3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (e^x+1)\\,dx$.', options: ['$e$', '$e-1$', '$e+1$', '$1$'], answer: 0, explanation: '$[e^x+x]_0^1=(e+1)-1=e$.' },
        { stem: 'Giá trị cực tiểu của $y=x^3-3x$ là?', options: ['$2$', '$0$', '$-4$', '$-2$'], answer: 3, explanation: 'Tại $x=1$, $y=-2$.' },
        { stem: 'Số đường tiệm cận đứng của $y=\\dfrac{1}{x^2-1}$ là?', options: ['$1$', '$2$', '$0$', '$3$'], answer: 1, explanation: 'Mẫu $=0$ tại $x=\\pm1$.' },
        { stem: '$\\displaystyle\\int (4x^3-1)\\,dx$ bằng?', options: ['$12x^2$', '$x^4+C$', '$x^4-x+C$', '$4x^4-x$'], answer: 2, explanation: '$x^4-x+C$.' },
        { stem: 'GTLN của $y=x^4-2x^2+3$ trên $[0;2]$ là?', options: ['$11$', '$3$', '$2$', '$8$'], answer: 0, explanation: '$y(0)=3,y(1)=2,y(2)=11$.' },
        { stem: 'Khoảng cách giữa $A(1;2;2)$ và $B(4;6;14)$ là?', options: ['$12$', '$169$', '$\\sqrt{14}$', '$13$'], answer: 3, explanation: '$\\vec{AB}=(3;4;12),\\ |\\vec{AB}|=\\sqrt{169}=13$.' },
        { stem: '$A,B$ độc lập, $P(A)=0{,}3$, $P(B)=0{,}6$. Tính $P(A\\cup B)$.', options: ['$0{,}9$', '$0{,}72$', '$0{,}18$', '$0{,}3$'], answer: 1, explanation: '$0{,}3+0{,}6-0{,}18=0{,}72$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi}\\cos x\\,dx$.', options: ['$2$', '$1$', '$0$', '$-1$'], answer: 2, explanation: '$[\\sin x]_0^\\pi=0$.' },
        { stem: 'Độ dài vectơ pháp tuyến của $2x-3y+6z-7=0$ là?', options: ['$7$', '$49$', '$5$', '$\\sqrt7$'], answer: 0, explanation: '$|(2;-3;6)|=\\sqrt{49}=7$.' },
        { stem: 'Mốt (giá trị xuất hiện nhiều nhất) của mẫu $2,2,3,5,5,5,7$ là?', options: ['$2$', '$3$', '$7$', '$5$'], answer: 3, explanation: '$5$ xuất hiện 3 lần.' },
        { stem: 'Hàm $y=x^3+x$ đồng biến trên?', options: ['$(0;+\\infty)$', '$\\mathbb{R}$', '$(-\\infty;0)$', 'không khoảng nào'], answer: 1, explanation: '$y\'=3x^2+1>0\\ \\forall x$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 2\\,dx$.', options: ['$2$', '$1$', '$0$', '$4$'], answer: 0, explanation: '$[2x]_0^1=2$.' },
        { stem: 'Đạo hàm của $y=\\tan x$ là?', options: ['$-\\dfrac{1}{\\sin^2 x}$', '$\\cos x$', '$\\dfrac{1}{\\cos^2 x}$', '$\\sin x$'], answer: 2, explanation: '$(\\tan x)\'=\\dfrac{1}{\\cos^2 x}$.' },
        { stem: 'Số nghiệm thực của $x^4-5x^2+4=0$ là?', options: ['$1$', '$2$', '$3$', '$4$'], answer: 3, explanation: '$(x^2-1)(x^2-4)=0\\Rightarrow x=\\pm1,\\pm2$.' },
      ],
    },
    {
      examId: 'ck-3', title: 'Đề thi Cuối kỳ #3 — Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=2x^3-3x^2+1$ nghịch biến trên?', options: ['$(-\\infty;0)$', '$\\mathbb{R}$', '$(0;1)$', '$(1;+\\infty)$'], answer: 2, explanation: '$y\'=6x(x-1)<0\\Leftrightarrow 0<x<1$.' },
        { stem: 'Tính $\\displaystyle\\int_0^2 x^3\\,dx$.', options: ['$4$', '$8$', '$2$', '$16$'], answer: 0, explanation: '$[x^4/4]_0^2=4$.' },
        { stem: 'Giá trị cực đại của $y=x^3-3x^2$ là?', options: ['$2$', '$-4$', '$1$', '$0$'], answer: 3, explanation: 'Tại $x=0$, $y=0$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{1-2x}{x+1}$ là?', options: ['$y=2$', '$y=-2$', '$x=-1$', '$y=1$'], answer: 1, explanation: '$\\lim y=-2$.' },
        { stem: '$\\displaystyle\\int \\dfrac{1}{x+1}\\,dx$ bằng?', options: ['$\\ln x+C$', '$\\dfrac{1}{(x+1)^2}$', '$\\ln|x+1|+C$', '$\\dfrac{-1}{(x+1)^2}$'], answer: 2, explanation: '$\\ln|x+1|+C$.' },
        { stem: 'GTLN của $y=-x^2+4x-1$ trên $[0;3]$ là?', options: ['$3$', '$-1$', '$2$', '$-9$'], answer: 0, explanation: 'Tại $x=2$, $y=3$.' },
        { stem: 'Điểm $M(1;1;1)$ có thuộc mặt phẳng $x+y-z+2=0$ không?', options: ['Có', 'Không', 'Không xác định', 'Chỉ khi $x=0$'], answer: 1, explanation: '$1+1-1+2=3\\ne0$.' },
        { stem: 'Cho $P(B\\mid A)=0{,}5$, $P(A)=0{,}6$. Tính $P(A\\cap B)$.', options: ['$0{,}83$', '$1{,}1$', '$0{,}5$', '$0{,}3$'], answer: 3, explanation: '$0{,}5\\cdot0{,}6=0{,}3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (x^2+x)\\,dx$.', options: ['$1$', '$\\tfrac12$', '$\\tfrac56$', '$\\tfrac13$'], answer: 2, explanation: '$\\tfrac13+\\tfrac12=\\tfrac56$.' },
        { stem: 'VTCP của $d:\\dfrac{x-1}{1}=\\dfrac{y+2}{2}=\\dfrac{z}{3}$ là?', options: ['$(1;2;3)$', '$(1;-2;0)$', '$(-1;2;3)$', '$(1;2;0)$'], answer: 0, explanation: 'Mẫu số.' },
        { stem: 'Tổng hai nghiệm của $x^2-5x+6=0$ là?', options: ['$2$', '$3$', '$6$', '$5$'], answer: 3, explanation: 'Vi-ét: $S=5$.' },
        { stem: 'Số điểm cực trị của $y=x^4+1$ là?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 1, explanation: '$y\'=4x^3$ đổi dấu tại $x=0$.' },
        { stem: 'Độ dài $\\vec{u}=(0;3;4)$ là?', options: ['$5$', '$7$', '$25$', '$\\sqrt7$'], answer: 0, explanation: '$\\sqrt{9+16}=5$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi/2} 2\\cos x\\,dx$.', options: ['$0$', '$1$', '$2$', '$4$'], answer: 2, explanation: '$2[\\sin x]_0^{\\pi/2}=2$.' },
        { stem: 'Đạo hàm của $y=\\sqrt{x}$ là?', options: ['$\\sqrt x$', '$\\dfrac{1}{\\sqrt x}$', '$2\\sqrt x$', '$\\dfrac{1}{2\\sqrt x}$'], answer: 3, explanation: '$(x^{1/2})\'=\\tfrac12 x^{-1/2}$.' },
      ],
    },
    {
      examId: 'ck-4', title: 'Đề thi Cuối kỳ #4 — Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^3+3x^2+3x+1$ đồng biến trên?', options: ['$(0;\\infty)$', '$(-1;\\infty)$', '$\\mathbb{R}$', 'không khoảng nào'], answer: 2, explanation: '$y\'=3(x+1)^2\\ge0$.' },
        { stem: 'Tính $\\displaystyle\\int_1^2 \\dfrac{1}{x^2}\\,dx$.', options: ['$\\tfrac12$', '$1$', '$2$', '$-\\tfrac12$'], answer: 0, explanation: '$[-1/x]_1^2=-\\tfrac12+1=\\tfrac12$.' },
        { stem: 'Giá trị cực tiểu của $y=x^2+2x$ là?', options: ['$1$', '$0$', '$2$', '$-1$'], answer: 3, explanation: 'Tại $x=-1$, $y=-1$.' },
        { stem: 'Số đường tiệm cận đứng của $y=\\dfrac{x}{x^2-4}$ là?', options: ['$1$', '$2$', '$0$', '$3$'], answer: 1, explanation: 'Mẫu $=0$ tại $x=\\pm2$.' },
        { stem: '$\\displaystyle\\int 3\\,dx$ bằng?', options: ['$0$', '$3$', '$3x+C$', '$x+C$'], answer: 2, explanation: '$\\int 3\\,dx=3x+C$.' },
        { stem: 'GTNN của $y=x^3-3x^2+2$ trên $[0;3]$ là?', options: ['$-2$', '$2$', '$0$', '$27$'], answer: 0, explanation: '$y(2)=-2$ nhỏ nhất.' },
        { stem: 'Khoảng cách từ $M(3;0;0)$ đến mặt phẳng $x+y+z=0$ là?', options: ['$3$', '$1$', '$0$', '$\\sqrt3$'], answer: 3, explanation: '$\\dfrac{3}{\\sqrt3}=\\sqrt3$.' },
        { stem: 'Gieo 2 đồng xu cân đối. Xác suất được 2 mặt ngửa là?', options: ['$\\tfrac12$', '$\\tfrac14$', '$\\tfrac13$', '$1$'], answer: 1, explanation: '$\\tfrac12\\cdot\\tfrac12=\\tfrac14$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (6x^2-2x)\\,dx$.', options: ['$2$', '$0$', '$1$', '$3$'], answer: 2, explanation: '$[2x^3-x^2]_0^1=1$.' },
        { stem: 'Phương trình mặt phẳng $(Oyz)$ là?', options: ['$x=0$', '$y=0$', '$z=0$', '$x+y+z=0$'], answer: 0, explanation: 'Mặt phẳng $Oyz$: $x=0$.' },
        { stem: 'Phương sai của mẫu $1,2,3$ là?', options: ['$1$', '$2$', '$\\tfrac13$', '$\\tfrac23$'], answer: 3, explanation: '$\\bar{x}=2$, $s^2=\\tfrac13(1+0+1)=\\tfrac23$.' },
        { stem: 'Số nghiệm thực của $x^3=8$ là?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 1, explanation: 'Chỉ $x=2$.' },
        { stem: 'Khoảng cách giữa $A(2;2;2)$ và $B(0;0;0)$ là?', options: ['$12$', '$6$', '$2\\sqrt3$', '$\\sqrt6$'], answer: 2, explanation: '$\\sqrt{4+4+4}=2\\sqrt3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 e^{-x}\\,dx$.', options: ['$1-\\tfrac1e$', '$\\tfrac1e-1$', '$e-1$', '$1$'], answer: 0, explanation: '$[-e^{-x}]_0^1=1-\\tfrac1e$.' },
        { stem: 'Đạo hàm của $y=x^5$ là?', options: ['$x^4$', '$\\tfrac{x^6}{6}$', '$5x$', '$5x^4$'], answer: 3, explanation: '$(x^5)\'=5x^4$.' },
      ],
    },
    {
      examId: 'ck-5', title: 'Đề thi Cuối kỳ #5 — Toán 12 (tổng hợp)', durationMin: 90,
      questions: [
        { stem: 'Số nghiệm phân biệt của phương trình $x^3-3x+2=0$ là?', options: ['$1$', '$2$', '$3$', '$0$'], answer: 1, explanation: '$(x-1)^2(x+2)=0\\Rightarrow x=1$ (kép), $x=-2$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi} \\sin(2x)\\,dx$.', options: ['$2$', '$1$', '$-1$', '$0$'], answer: 3, explanation: '$[-\\tfrac12\\cos2x]_0^\\pi=-\\tfrac12+\\tfrac12=0$.' },
        { stem: 'GTLN của $y=4x-x^2$ trên $\\mathbb{R}$ là?', options: ['$4$', '$2$', '$0$', '$8$'], answer: 0, explanation: 'Tại $x=2$, $y=4$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{2x^2+1}{x^2+1}$ là?', options: ['$y=1$', '$y=0$', '$y=2$', '$x=1$'], answer: 2, explanation: 'Bậc tử $=$ bậc mẫu, tỉ số hệ số cao nhất $=2$.' },
        { stem: '$\\displaystyle\\int (\\cos x-\\sin x)\\,dx$ bằng?', options: ['$-\\sin x-\\cos x+C$', '$\\sin x+\\cos x+C$', '$\\cos x-\\sin x$', '$\\sin x-\\cos x+C$'], answer: 1, explanation: '$\\sin x+\\cos x+C$.' },
        { stem: 'Số điểm cực trị của $y=x^3$ là?', options: ['$1$', '$2$', '$3$', '$0$'], answer: 3, explanation: '$y\'=3x^2\\ge0$ không đổi dấu.' },
        { stem: 'Độ dài VTPT của mặt phẳng $3x-6y+2z+1=0$ là?', options: ['$7$', '$49$', '$5$', '$\\sqrt7$'], answer: 0, explanation: '$\\sqrt{9+36+4}=7$.' },
        { stem: 'Cho $P(A)=0{,}2$, $P(B\\mid A)=0{,}5$. Tính $P(A\\cap B)$.', options: ['$0{,}4$', '$0{,}7$', '$0{,}1$', '$0{,}25$'], answer: 2, explanation: '$0{,}2\\cdot0{,}5=0{,}1$.' },
        { stem: 'Tính $\\displaystyle\\int_1^2 x\\,dx$.', options: ['$2$', '$1$', '$\\tfrac12$', '$\\tfrac32$'], answer: 3, explanation: '$[x^2/2]_1^2=2-\\tfrac12=\\tfrac32$.' },
        { stem: 'Mặt cầu tâm $I(1;1;1)$ đi qua gốc $O$ có phương trình?', options: ['$(x-1)^2+(y-1)^2+(z-1)^2=9$', '$(x-1)^2+(y-1)^2+(z-1)^2=3$', '$x^2+y^2+z^2=3$', '$(x-1)^2+(y-1)^2+(z-1)^2=1$'], answer: 1, explanation: '$R=OI=\\sqrt3$.' },
        { stem: 'Trung vị của mẫu $3,5,7,9,11$ là?', options: ['$5$', '$9$', '$7$', '$11$'], answer: 2, explanation: 'Số ở giữa là $7$.' },
        { stem: 'GTNN của $y=x^4-2x^2$ trên $\\mathbb{R}$ là?', options: ['$-1$', '$0$', '$1$', '$-2$'], answer: 0, explanation: 'Tại $x=\\pm1$, $y=-1$.' },
        { stem: 'Độ dài $\\vec{u}=(1;2;-2)$ là?', options: ['$5$', '$3$', '$9$', '$\\sqrt5$'], answer: 1, explanation: '$\\sqrt{1+4+4}=3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (2x+3)\\,dx$.', options: ['$4$', '$2$', '$6$', '$3$'], answer: 0, explanation: '$[x^2+3x]_0^1=4$.' },
        { stem: 'Đạo hàm của $y=e^{-x}$ là?', options: ['$e^{-x}$', '$e^{x}$', '$-e^{-x}$', '$xe^{-x-1}$'], answer: 2, explanation: '$(e^{-x})\'=-e^{-x}$.' },
      ],
    },
  ],

  LY: [
    {
      examId: 'ly-kt45-1', title: 'Kiểm tra 45′ #1 — Vật lí nhiệt & Khí lí tưởng', durationMin: 45,
      questions: [
        { stem: 'Định luật I Nhiệt động lực học: $\\Delta U=$?', options: ['$Q-A$', '$A+Q$', '$A-Q$', '$AQ$'], answer: 1, explanation: '$\\Delta U=A+Q$.' },
        { stem: 'Đun $1$ kg nước ($c=4200$) tăng $5$ °C cần nhiệt lượng?', options: ['$4200$ J', '$21000$ J', '$1000$ J', '$84000$ J'], answer: 1, explanation: '$Q=mc\\Delta t=1\\cdot4200\\cdot5=21000$ J.' },
        { stem: 'Đơn vị của nội năng là?', options: ['Niutơn (N)', 'Oát (W)', 'Jun (J)', 'Paxcan (Pa)'], answer: 2, explanation: 'Nội năng đo bằng jun.' },
        { stem: 'Khí đẳng nhiệt $p_1=2$, $V_1=3$, nén còn $V_2=1$. Tính $p_2$.', options: ['$2$', '$3$', '$6$', '$1$'], answer: 2, explanation: '$p_2=\\dfrac{p_1V_1}{V_2}=6$.' },
        { stem: '$27$ °C bằng bao nhiêu Kelvin?', options: ['$27$', '$300$', '$246$', '$273$'], answer: 1, explanation: '$T=27+273=300$ K.' },
        { stem: 'Đẳng tích: $p_1=1$ atm ở $T_1=300$ K, đun tới $T_2=600$ K. Tính $p_2$.', options: ['$1$', '$2$', '$0{,}5$', '$4$'], answer: 1, explanation: '$\\dfrac{p}{T}$ const ⇒ $p_2=2$ atm.' },
        { stem: 'Trong định luật I, $Q>0$ nghĩa là?', options: ['hệ tỏa nhiệt', 'hệ nhận nhiệt', 'hệ sinh công', 'nội năng không đổi'], answer: 1, explanation: 'Quy ước $Q>0$: nhận nhiệt.' },
        { stem: 'Phương trình trạng thái khí lí tưởng: $\\dfrac{p_1V_1}{T_1}=$?', options: ['$p_2V_2T_2$', '$\\dfrac{T_2}{p_2V_2}$', '$\\dfrac{p_2V_2}{T_2}$', '$p_2+V_2$'], answer: 2, explanation: '$\\dfrac{p_1V_1}{T_1}=\\dfrac{p_2V_2}{T_2}$.' },
        { stem: 'Đơn vị nhiệt dung riêng là?', options: ['J', 'J/kg', 'J/(kg·K)', 'W/K'], answer: 2, explanation: '$c$ đo bằng J/(kg·K).' },
        { stem: 'Khi khí sinh công thì công $A$?', options: ['$A>0$', '$A=0$', '$A<0$', '$A=Q$'], answer: 2, explanation: 'Hệ sinh công ⇒ $A<0$.' },
      ],
    },
    {
      examId: 'ly-kt45-2', title: 'Kiểm tra 45′ #2 — Từ trường & Hạt nhân', durationMin: 45,
      questions: [
        { stem: 'Lực từ lên dây ($B=0{,}2$ T, $I=3$ A, $l=0{,}5$ m, vuông góc) là?', options: ['$0{,}3$ N', '$0{,}1$ N', '$3$ N', '$0{,}6$ N'], answer: 0, explanation: '$F=BIl=0{,}2\\cdot3\\cdot0{,}5=0{,}3$ N.' },
        { stem: 'Đơn vị của cảm ứng từ $B$ là?', options: ['Vêbe (Wb)', 'Tesla (T)', 'Henry (H)', 'Jun (J)'], answer: 1, explanation: '$B$ đo bằng tesla.' },
        { stem: 'Từ thông qua khung $N=5$ vòng, $B=0{,}4$ T, $S=0{,}02$ m², $\\alpha=0$?', options: ['$0{,}4$', '$0{,}04$', '$0{,}004$', '$4$'], answer: 1, explanation: '$\\Phi=NBS=5\\cdot0{,}4\\cdot0{,}02=0{,}04$ Wb.' },
        { stem: 'Từ thông biến thiên $0{,}1$ Wb trong $0{,}5$ s. Suất điện động cảm ứng?', options: ['$0{,}05$ V', '$0{,}5$ V', '$0{,}2$ V', '$2$ V'], answer: 2, explanation: '$|e|=\\dfrac{0{,}1}{0{,}5}=0{,}2$ V.' },
        { stem: 'Hạt nhân $^{4}_{2}He$ có bao nhiêu neutron?', options: ['$4$', '$2$', '$6$', '$0$'], answer: 1, explanation: '$N=A-Z=4-2=2$.' },
        { stem: 'Năng lượng liên kết của hạt nhân tính bằng?', options: ['$\\Delta m\\,c$', '$\\Delta m\\,c^2$', '$mc^2$', '$\\dfrac{\\Delta m}{c^2}$'], answer: 1, explanation: '$W_{lk}=\\Delta m\\,c^2$.' },
        { stem: 'Sau một chu kì bán rã, số hạt nhân còn lại bằng?', options: ['$100\\%$', '$50\\%$', '$25\\%$', '$0\\%$'], answer: 1, explanation: '$N=N_0/2$.' },
        { stem: '$1$ u tương đương xấp xỉ?', options: ['$931{,}5$ MeV/$c^2$', '$1$ MeV', '$3\\cdot10^8$ m/s', '$9{,}1\\cdot10^{-31}$ kg'], answer: 0, explanation: '$1\\,u\\approx931{,}5$ MeV/$c^2$.' },
        { stem: 'Lực Lorentz lên hạt điện tích là?', options: ['$qvB$ (luôn vậy)', '$|q|vB\\sin\\alpha$', '$BIl$', '$qE$'], answer: 1, explanation: '$f=|q|vB\\sin\\alpha$.' },
        { stem: 'Định luật phóng xạ có dạng?', options: ['$N=N_0 2^{t/T}$', '$N=N_0 e^{\\lambda t}$', '$N=N_0 2^{-t/T}$', '$N=N_0 t$'], answer: 2, explanation: '$N=N_0 2^{-t/T}=N_0 e^{-\\lambda t}$.' },
      ],
    },
  ],

  TOEIC: [
    {
      examId: 'toeic-reading', title: 'TOEIC Reading – Mini test', durationMin: 10,
      questions: [
        { stem: 'The report must be submitted ____ Friday.',
          options: ['in', 'on', 'at', 'by'], answer: 3, explanation: '"by Friday" = hạn chót đến thứ Sáu.' },
        { stem: 'She is responsible ____ marketing.',
          options: ['for', 'to', 'with', 'of'], answer: 0, explanation: 'be responsible <strong>for</strong> something.' },
        { stem: 'We look forward to ____ from you.',
          options: ['hear', 'hearing', 'heard', 'hears'], answer: 1, explanation: 'look forward to + V-ing.' },
      ],
    },
  ],

  IELTS: [],
};

const Exams = {
  list(code) { return EXAMS[code] || []; },
  get(examId) {
    for (const code in EXAMS) {
      const e = EXAMS[code].find((x) => x.examId === examId);
      if (e) {
        // gán id cho từng câu để chấm
        return Object.assign({}, e, { questions: e.questions.map((q, i) => Object.assign({ questionId: examId + '-' + i, type: 'MCQ' }, q)) });
      }
    }
    return null;
  },
};
