/* ============================================================
   exams.js — ĐỀ KIỂM TRA (tĩnh). Tự chấm tại trình duyệt → tức thì.

   CÁCH THÊM ĐỀ / CÂU HỎI:
   - Thêm object vào EXAMS[<mã môn>]:
       { examId:'ma-de', title:'Tên đề', durationMin:15, questions:[ ... ] }
   - Mỗi câu (trắc nghiệm 1 đáp án):
       { stem:'Đề bài (LaTeX $...$)', options:['A','B','C','D'], answer:<chỉ số đúng 0..3>,
         explanation:'Lời giải ngắn' }
   ============================================================ */

const EXAMS = {
  TOAN: [
    {
      examId: 'toan-c1', title: 'Đạo hàm & Khảo sát hàm số', durationMin: 15,
      questions: [
        { stem: 'Hàm số $y=x^3-3x$ đồng biến trên khoảng nào?',
          options: ['$(-1;1)$', '$(-\\infty;-1)$ và $(1;+\\infty)$', '$(0;+\\infty)$', '$\\mathbb{R}$'],
          answer: 1, explanation: '$y\'=3x^2-3>0 \\Leftrightarrow x<-1$ hoặc $x>1$.' },
        { stem: 'Số điểm cực trị của hàm $y=x^4-2x^2$ là?',
          options: ['$0$', '$1$', '$2$', '$3$'],
          answer: 3, explanation: '$y\'=4x^3-4x=4x(x-1)(x+1)$ có 3 nghiệm ⇒ 3 cực trị.' },
        { stem: 'Giá trị lớn nhất của $y=-x^2+4x$ trên $\\mathbb{R}$ là?',
          options: ['$2$', '$4$', '$0$', '$8$'],
          answer: 1, explanation: '$y\'=-2x+4=0 \\Leftrightarrow x=2$, $y(2)=4$.' },
        { stem: 'Tiệm cận ngang của đồ thị $y=\\dfrac{2x+1}{x-1}$ là?',
          options: ['$x=1$', '$y=2$', '$y=1$', '$x=2$'],
          answer: 1, explanation: '$\\lim\\limits_{x\\to\\pm\\infty}y=\\dfrac{2}{1}=2$.' },
        { stem: 'Đạo hàm của $y=\\ln x$ là?',
          options: ['$x$', '$\\dfrac{1}{x}$', '$\\dfrac{1}{x^2}$', '$\\ln x$'],
          answer: 1, explanation: '$(\\ln x)\'=\\dfrac{1}{x}$.' },
      ],
    },
    {
      examId: 'toan-tp-xs', title: 'Tích phân & Xác suất', durationMin: 15,
      questions: [
        { stem: 'Tính $\\displaystyle\\int_0^1 2x\\,dx$.',
          options: ['$1$', '$2$', '$\\dfrac{1}{2}$', '$0$'],
          answer: 0, explanation: '$[x^2]_0^1=1$.' },
        { stem: 'Họ nguyên hàm của $f(x)=x^2$ là?',
          options: ['$x^3+C$', '$\\dfrac{x^3}{3}+C$', '$2x+C$', '$3x^2+C$'],
          answer: 1, explanation: '$\\int x^2dx=\\dfrac{x^3}{3}+C$.' },
        { stem: 'Thể tích khối tròn xoay khi quay $y=\\sqrt{x}$ quanh $Ox$ từ $0$ đến $4$ là?',
          options: ['$4\\pi$', '$8\\pi$', '$16\\pi$', '$2\\pi$'],
          answer: 1, explanation: '$V=\\pi\\int_0^4 x\\,dx=8\\pi$.' },
        { stem: 'Cho $P(A\\cap B)=0{,}2$, $P(B)=0{,}5$. Tính $P(A\\mid B)$.',
          options: ['$0{,}1$', '$0{,}4$', '$0{,}25$', '$0{,}7$'],
          answer: 1, explanation: '$P(A\\mid B)=\\dfrac{0{,}2}{0{,}5}=0{,}4$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi}\\sin x\\,dx$.',
          options: ['$0$', '$1$', '$2$', '$-2$'],
          answer: 2, explanation: '$[-\\cos x]_0^{\\pi}=1+1=2$.' },
      ],
    },
    {
      examId: 'kt45-1', title: 'Kiểm tra 45′ #1 — Đạo hàm & Khảo sát hàm số', durationMin: 45,
      questions: [
        { stem: 'Hàm số $y=x^3-3x^2$ đồng biến trên khoảng nào?', options: ['$(0;2)$', '$(-\\infty;0)$ và $(2;+\\infty)$', '$(2;+\\infty)$', '$\\mathbb{R}$'], answer: 1, explanation: '$y\'=3x^2-6x=3x(x-2)>0\\Leftrightarrow x<0$ hoặc $x>2$.' },
        { stem: 'Giá trị cực đại của $y=-x^2+2x$ là?', options: ['$1$', '$2$', '$0$', '$-1$'], answer: 0, explanation: '$y\'=-2x+2=0\\Rightarrow x=1,\\ y(1)=1$.' },
        { stem: 'Số điểm cực trị của $y=x^3+x$ là?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 0, explanation: '$y\'=3x^2+1>0\\ \\forall x$ ⇒ không có cực trị.' },
        { stem: 'GTNN của $y=x^2-4x+5$ trên $\\mathbb{R}$ là?', options: ['$1$', '$5$', '$0$', '$-1$'], answer: 0, explanation: '$y=(x-2)^2+1\\ge 1$.' },
        { stem: 'Tiệm cận đứng của $y=\\dfrac{x+1}{x-2}$ là?', options: ['$x=2$', '$y=2$', '$x=-1$', '$y=1$'], answer: 0, explanation: 'Mẫu $=0\\Leftrightarrow x=2$.' },
        { stem: 'Hàm $y=x^4-2x^2+1$ có mấy điểm cực trị?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 3, explanation: '$y\'=4x^3-4x=4x(x-1)(x+1)$ có 3 nghiệm.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{2x-3}{x+1}$ là?', options: ['$y=2$', '$x=-1$', '$y=-3$', '$x=2$'], answer: 0, explanation: '$\\lim\\limits_{x\\to\\pm\\infty}y=2$.' },
        { stem: 'Hàm số $y=x^3$ đồng biến trên?', options: ['$(0;+\\infty)$', '$\\mathbb{R}$', '$(-\\infty;0)$', 'không khoảng nào'], answer: 1, explanation: '$y\'=3x^2\\ge 0$, bằng 0 tại 1 điểm ⇒ đồng biến trên $\\mathbb{R}$.' },
        { stem: 'Đạo hàm của $y=e^x$ là?', options: ['$x e^{x-1}$', '$e^x$', '$\\dfrac{1}{x}$', '$x$'], answer: 1, explanation: '$(e^x)\'=e^x$.' },
        { stem: 'GTLN của $y=x^3-3x$ trên $[0;2]$ là?', options: ['$0$', '$-2$', '$2$', '$6$'], answer: 2, explanation: '$y\'=3x^2-3=0\\Rightarrow x=1$; $y(0)=0, y(1)=-2, y(2)=2$.' },
      ],
    },
    {
      examId: 'kt45-2', title: 'Kiểm tra 45′ #2 — Nguyên hàm & Tích phân', durationMin: 45,
      questions: [
        { stem: 'Họ nguyên hàm $\\displaystyle\\int x^3\\,dx$ bằng?', options: ['$\\dfrac{x^4}{4}+C$', '$3x^2+C$', '$x^4+C$', '$4x^3+C$'], answer: 0, explanation: '$\\int x^n dx=\\dfrac{x^{n+1}}{n+1}+C$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 x^2\\,dx$.', options: ['$\\dfrac{1}{3}$', '$1$', '$\\dfrac{1}{2}$', '$3$'], answer: 0, explanation: '$[x^3/3]_0^1=1/3$.' },
        { stem: '$\\displaystyle\\int \\dfrac{1}{x}\\,dx$ bằng?', options: ['$\\ln|x|+C$', '$-\\dfrac{1}{x^2}+C$', '$x+C$', '$\\dfrac{1}{x^2}$'], answer: 0, explanation: '$\\int\\frac{1}{x}dx=\\ln|x|+C$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi}\\sin x\\,dx$.', options: ['$0$', '$1$', '$2$', '$-1$'], answer: 2, explanation: '$[-\\cos x]_0^\\pi=2$.' },
        { stem: '$\\displaystyle\\int e^x\\,dx$ bằng?', options: ['$e^x+C$', '$xe^{x-1}$', '$\\ln x+C$', '$e^x$'], answer: 0, explanation: '$\\int e^x dx=e^x+C$.' },
        { stem: 'Tính $\\displaystyle\\int_1^2 2x\\,dx$.', options: ['$3$', '$4$', '$1$', '$2$'], answer: 0, explanation: '$[x^2]_1^2=3$.' },
        { stem: 'Diện tích hình phẳng giới hạn $y=x^2$, $Ox$, $x=0$, $x=3$ là?', options: ['$9$', '$3$', '$27$', '$6$'], answer: 0, explanation: '$\\int_0^3 x^2 dx=9$.' },
        { stem: '$\\displaystyle\\int \\cos x\\,dx$ bằng?', options: ['$\\sin x+C$', '$-\\sin x+C$', '$\\cos x$', '$-\\cos x+C$'], answer: 0, explanation: '$\\int\\cos x dx=\\sin x+C$.' },
        { stem: 'Thể tích khối tròn xoay quay $y=x$ quanh $Ox$ từ $0$ đến $1$ là?', options: ['$\\dfrac{\\pi}{3}$', '$\\pi$', '$\\dfrac{\\pi}{2}$', '$\\dfrac{2\\pi}{3}$'], answer: 0, explanation: '$V=\\pi\\int_0^1 x^2 dx=\\dfrac{\\pi}{3}$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (2x+1)\\,dx$.', options: ['$2$', '$1$', '$3$', '$0$'], answer: 0, explanation: '$[x^2+x]_0^1=2$.' },
      ],
    },
    {
      examId: 'kt45-3', title: 'Kiểm tra 45′ #3 — Vectơ & tọa độ Oxyz', durationMin: 45,
      questions: [
        { stem: 'Cho $A(1;2;3)$, $B(3;0;1)$. Tọa độ $\\vec{AB}$ là?', options: ['$(2;-2;-2)$', '$(-2;2;2)$', '$(4;2;4)$', '$(2;2;2)$'], answer: 0, explanation: '$\\vec{AB}=B-A=(2;-2;-2)$.' },
        { stem: 'Độ dài của $\\vec{u}=(2;1;2)$ là?', options: ['$3$', '$5$', '$9$', '$\\sqrt{5}$'], answer: 0, explanation: '$|\\vec{u}|=\\sqrt{4+1+4}=3$.' },
        { stem: 'Trung điểm của $A(0;0;0)$ và $B(2;4;6)$ là?', options: ['$(1;2;3)$', '$(2;4;6)$', '$(1;1;1)$', '$(0;2;3)$'], answer: 0, explanation: 'Trung điểm $=\\left(\\tfrac{0+2}{2};\\tfrac{0+4}{2};\\tfrac{0+6}{2}\\right)$.' },
        { stem: 'Tích vô hướng $\\vec{u}\\cdot\\vec{v}$ với $\\vec{u}=(1;2;3)$, $\\vec{v}=(2;0;-1)$ là?', options: ['$-1$', '$5$', '$1$', '$2$'], answer: 0, explanation: '$2+0-3=-1$.' },
        { stem: 'Vectơ nào vuông góc với $\\vec{u}=(2;1;2)$?', options: ['$(1;-2;0)$', '$(1;1;1)$', '$(0;0;1)$', '$(1;0;1)$'], answer: 0, explanation: '$(2)(1)+(1)(-2)+(2)(0)=0$.' },
        { stem: 'Trọng tâm tam giác $A(1;1;1)$, $B(2;2;2)$, $C(3;3;3)$ là?', options: ['$(2;2;2)$', '$(6;6;6)$', '$(1;1;1)$', '$(3;3;3)$'], answer: 0, explanation: '$G=\\left(\\tfrac{1+2+3}{3};\\dots\\right)=(2;2;2)$.' },
        { stem: 'Góc giữa $\\vec{u}=(1;0;0)$ và $\\vec{v}=(0;1;0)$ là?', options: ['$90^\\circ$', '$0^\\circ$', '$45^\\circ$', '$180^\\circ$'], answer: 0, explanation: '$\\vec{u}\\cdot\\vec{v}=0$.' },
        { stem: 'Điểm nào nằm trên trục $Ox$?', options: ['$(3;0;0)$', '$(0;3;0)$', '$(0;0;3)$', '$(1;1;1)$'], answer: 0, explanation: 'Trên $Ox$: $y=z=0$.' },
        { stem: 'Điểm đối xứng của $A(2;-1;0)$ qua gốc $O$ là?', options: ['$(-2;1;0)$', '$(2;1;0)$', '$(-2;-1;0)$', '$(2;-1;0)$'], answer: 0, explanation: 'Đổi dấu các tọa độ.' },
        { stem: 'Hai vectơ $\\vec{u}=(1;1;1)$, $\\vec{v}=(2;2;2)$ có quan hệ gì?', options: ['Cùng phương ($\\vec{v}=2\\vec{u}$)', 'Vuông góc', 'Không cùng phương', 'Bằng nhau'], answer: 0, explanation: '$\\vec{v}=2\\vec{u}$.' },
      ],
    },
    {
      examId: 'kt45-4', title: 'Kiểm tra 45′ #4 — Mặt phẳng, đường thẳng, mặt cầu', durationMin: 45,
      questions: [
        { stem: 'Vectơ pháp tuyến của mặt phẳng $2x-3y+z-1=0$ là?', options: ['$(2;-3;1)$', '$(2;3;1)$', '$(2;-3;-1)$', '$(-1;2;-3)$'], answer: 0, explanation: 'Hệ số của $x,y,z$.' },
        { stem: 'Khoảng cách từ $O$ đến mặt phẳng $x+y+z-3=0$ là?', options: ['$\\sqrt{3}$', '$3$', '$1$', '$\\sqrt{2}$'], answer: 0, explanation: '$d=\\dfrac{|-3|}{\\sqrt{3}}=\\sqrt{3}$.' },
        { stem: 'Bán kính mặt cầu $(x-1)^2+(y+2)^2+z^2=9$ là?', options: ['$3$', '$9$', '$\\sqrt{3}$', '$1$'], answer: 0, explanation: '$R=\\sqrt{9}=3$.' },
        { stem: 'Tâm mặt cầu $x^2+y^2+z^2-2x-4y+1=0$ là?', options: ['$(1;2;0)$', '$(-1;-2;0)$', '$(2;4;0)$', '$(1;2;1)$'], answer: 0, explanation: '$I(a;b;c)$ với $a=1,b=2,c=0$.' },
        { stem: 'Vectơ chỉ phương của $d:\\dfrac{x-1}{2}=\\dfrac{y}{-1}=\\dfrac{z+2}{3}$ là?', options: ['$(2;-1;3)$', '$(1;0;-2)$', '$(2;1;3)$', '$(-2;1;3)$'], answer: 0, explanation: 'Mẫu số là tọa độ VTCP.' },
        { stem: 'Mặt phẳng qua $O$ với pháp tuyến $(1;2;2)$ có phương trình?', options: ['$x+2y+2z=0$', '$x+2y+2z-1=0$', '$2x+y+2z=0$', '$x+y+z=0$'], answer: 0, explanation: 'Qua $O$ ⇒ $D=0$.' },
        { stem: 'Điểm $M(1;1;1)$ có thuộc mặt phẳng $x+y+z-3=0$ không?', options: ['Có', 'Không', 'Không xác định', 'Chỉ khi đổi dấu'], answer: 0, explanation: '$1+1+1-3=0$.' },
        { stem: 'Khoảng cách từ $M(1;0;0)$ đến mặt phẳng $2x+2y+z+4=0$ là?', options: ['$2$', '$6$', '$3$', '$1$'], answer: 0, explanation: '$\\dfrac{|2+0+0+4|}{\\sqrt{4+4+1}}=\\dfrac{6}{3}=2$.' },
        { stem: 'Bán kính mặt cầu $x^2+y^2+z^2=16$ là?', options: ['$4$', '$16$', '$8$', '$2$'], answer: 0, explanation: '$R=\\sqrt{16}=4$.' },
        { stem: 'Vectơ pháp tuyến của mặt phẳng $3x-4z+5=0$ là?', options: ['$(3;0;-4)$', '$(3;-4;0)$', '$(3;-4;5)$', '$(3;0;4)$'], answer: 0, explanation: 'Thiếu $y$ ⇒ hệ số $y=0$.' },
      ],
    },
    {
      examId: 'kt45-5', title: 'Kiểm tra 45′ #5 — Xác suất có điều kiện & Thống kê', durationMin: 45,
      questions: [
        { stem: 'Cho $P(A\\cap B)=0{,}2$, $P(B)=0{,}4$. Tính $P(A\\mid B)$.', options: ['$0{,}5$', '$0{,}8$', '$0{,}08$', '$0{,}2$'], answer: 0, explanation: '$\\dfrac{0{,}2}{0{,}4}=0{,}5$.' },
        { stem: '$A,B$ độc lập, $P(A)=0{,}3$, $P(B)=0{,}5$. Tính $P(A\\cap B)$.', options: ['$0{,}15$', '$0{,}8$', '$0{,}2$', '$0{,}5$'], answer: 0, explanation: '$P(A)P(B)=0{,}15$.' },
        { stem: 'Khoảng biến thiên của mẫu $2,5,9,12$ là?', options: ['$10$', '$7$', '$2$', '$12$'], answer: 0, explanation: '$12-2=10$.' },
        { stem: 'Gieo một xúc xắc. Xác suất "số chẵn" biết "số $\\ge 3$" là?', options: ['$\\dfrac{1}{2}$', '$\\dfrac{1}{3}$', '$\\dfrac{1}{4}$', '$\\dfrac{2}{3}$'], answer: 0, explanation: '$B=\\{3,4,5,6\\}, A\\cap B=\\{4,6\\}\\Rightarrow 2/4$.' },
        { stem: 'Phương sai và độ lệch chuẩn đo đại lượng nào?', options: ['Độ phân tán của dữ liệu', 'Giá trị trung bình', 'Giá trị lớn nhất', 'Trung vị'], answer: 0, explanation: 'Đo mức độ phân tán quanh trung bình.' },
        { stem: 'Phương sai của mẫu $4,4,4,4$ là?', options: ['$0$', '$4$', '$16$', '$1$'], answer: 0, explanation: 'Mọi giá trị bằng trung bình ⇒ phương sai $=0$.' },
        { stem: 'Cho $P(A\\cap B)=0{,}1$, $P(A\\mid B)=0{,}5$. Tính $P(B)$.', options: ['$0{,}2$', '$0{,}05$', '$0{,}5$', '$0{,}6$'], answer: 0, explanation: '$P(B)=\\dfrac{0{,}1}{0{,}5}=0{,}2$.' },
        { stem: 'Khoảng tứ phân vị $\\Delta_Q$ của mẫu $1,3,5,7,9$ là?', options: ['$6$', '$4$', '$8$', '$2$'], answer: 0, explanation: '$Q_1=2, Q_3=8 \\Rightarrow \\Delta_Q=6$.' },
        { stem: 'Nếu $P(A\\mid B)=P(A)$ thì hai biến cố $A,B$?', options: ['Độc lập', 'Xung khắc', 'Đối nhau', 'Bằng nhau'], answer: 0, explanation: 'Định nghĩa biến cố độc lập.' },
        { stem: 'Độ lệch chuẩn $s$ bằng?', options: ['Căn bậc hai của phương sai', 'Bình phương phương sai', 'Trung bình', 'Phương sai'], answer: 0, explanation: '$s=\\sqrt{s^2}$.' },
      ],
    },
    {
      examId: 'kt45-6', title: 'Kiểm tra 45′ #6 — Khảo sát hàm số (tổng hợp)', durationMin: 45,
      questions: [
        { stem: 'Điểm cực tiểu của $y=x^3-3x+2$ có hoành độ?', options: ['$x=-1$', '$x=1$', '$x=0$', '$x=2$'], answer: 1, explanation: '$y\'=3x^2-3=0\\Rightarrow x=\\pm1$; $y\'\'(1)=6>0$ ⇒ cực tiểu tại $x=1$.' },
        { stem: 'Phương trình $y\'=0$ của $y=x^4-8x^2$ có mấy nghiệm?', options: ['$2$', '$4$', '$3$', '$1$'], answer: 2, explanation: '$y\'=4x^3-16x=4x(x^2-4)\\Rightarrow x=0,\\pm2$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{x-1}{x+1}$ là?', options: ['$y=1$', '$y=-1$', '$x=1$', '$x=-1$'], answer: 0, explanation: '$\\lim\\limits_{x\\to\\pm\\infty}y=1$.' },
        { stem: 'Đồ thị $y=x^3$ có điểm uốn tại?', options: ['$x=1$', '$x=-1$', '$x=2$', '$x=0$'], answer: 3, explanation: '$y\'\'=6x=0\\Rightarrow x=0$.' },
        { stem: 'GTLN của $y=4-x^2$ trên $\\mathbb{R}$ là?', options: ['$0$', '$4$', '$2$', '$-4$'], answer: 1, explanation: 'Đạt tại $x=0$, $y=4$.' },
        { stem: 'Đạo hàm của $y=2x^3-3x^2+1$ là?', options: ['$6x^2-6$', '$2x^2-3x$', '$6x^2-6x$', '$6x^2-3$'], answer: 2, explanation: '$y\'=6x^2-6x$.' },
        { stem: 'Hàm số nào nghịch biến trên $\\mathbb{R}$?', options: ['$y=x^3$', '$y=x^2$', '$y=x^4$', '$y=-x^3-x$'], answer: 3, explanation: '$y\'=-3x^2-1<0\\ \\forall x$.' },
        { stem: 'Tiệm cận đứng của $y=\\dfrac{1}{x-3}$ là?', options: ['$x=3$', '$x=-3$', '$y=3$', '$y=0$'], answer: 0, explanation: 'Mẫu $=0\\Leftrightarrow x=3$.' },
        { stem: 'Hàm $y=x^2-2x+3$ đạt cực tiểu tại?', options: ['$x=0$', '$x=2$', '$x=1$', '$x=-1$'], answer: 2, explanation: '$y\'=2x-2=0\\Rightarrow x=1$.' },
        { stem: 'Đồ thị hàm bậc ba cắt trục hoành tối đa mấy điểm?', options: ['$2$', '$3$', '$1$', 'vô số'], answer: 1, explanation: 'Phương trình bậc ba có tối đa 3 nghiệm.' },
      ],
    },
    {
      examId: 'kt45-7', title: 'Kiểm tra 45′ #7 — Nguyên hàm & Tích phân (nâng cao)', durationMin: 45,
      questions: [
        { stem: '$\\displaystyle\\int (2x+3)\\,dx$ bằng?', options: ['$2x+3$', '$2$', '$x^2+3x+C$', '$x^2+3$'], answer: 2, explanation: '$\\int(2x+3)dx=x^2+3x+C$.' },
        { stem: 'Tính $\\displaystyle\\int_0^2 x\\,dx$.', options: ['$2$', '$4$', '$1$', '$\\tfrac12$'], answer: 0, explanation: '$[x^2/2]_0^2=2$.' },
        { stem: '$\\displaystyle\\int \\sin(2x)\\,dx$ bằng?', options: ['$\\tfrac12\\cos 2x+C$', '$-\\cos 2x+C$', '$2\\cos 2x$', '$-\\tfrac12\\cos 2x+C$'], answer: 3, explanation: '$\\int\\sin 2x\\,dx=-\\tfrac12\\cos 2x+C$.' },
        { stem: 'Tính $\\displaystyle\\int_1^e \\dfrac{1}{x}\\,dx$.', options: ['$e$', '$1$', '$0$', '$e-1$'], answer: 1, explanation: '$[\\ln x]_1^e=1$.' },
        { stem: '$\\displaystyle\\int (3x^2-2x)\\,dx$ bằng?', options: ['$x^3-x^2+C$', '$6x-2$', '$3x^3-2x^2$', '$x^3-2x$'], answer: 0, explanation: '$x^3-x^2+C$.' },
        { stem: 'Diện tích hình phẳng dưới $y=x^3$ trên $[0;2]$ là?', options: ['$8$', '$2$', '$4$', '$16$'], answer: 2, explanation: '$\\int_0^2 x^3 dx=[x^4/4]_0^2=4$.' },
        { stem: '$\\displaystyle\\int e^{-x}\\,dx$ bằng?', options: ['$e^{-x}+C$', '$-e^{-x}+C$', '$-e^{x}$', '$e^{-x}$'], answer: 1, explanation: '$\\int e^{-x}dx=-e^{-x}+C$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 4x^3\\,dx$.', options: ['$4$', '$\\tfrac12$', '$2$', '$1$'], answer: 3, explanation: '$[x^4]_0^1=1$.' },
        { stem: '$\\displaystyle\\int \\dfrac{1}{x^2}\\,dx$ bằng?', options: ['$-\\dfrac{1}{x}+C$', '$\\dfrac{1}{x}+C$', '$-\\dfrac{2}{x^3}$', '$\\ln x^2$'], answer: 0, explanation: '$\\int x^{-2}dx=-x^{-1}+C$.' },
        { stem: 'Thể tích khi quay $y=x^2$ quanh $Ox$ từ $0$ đến $1$ là?', options: ['$\\dfrac{\\pi}{3}$', '$\\pi$', '$\\dfrac{\\pi}{5}$', '$\\dfrac{2\\pi}{5}$'], answer: 2, explanation: '$V=\\pi\\int_0^1 x^4 dx=\\dfrac{\\pi}{5}$.' },
      ],
    },
    {
      examId: 'kt45-8', title: 'Kiểm tra 45′ #8 — Tổng hợp giữa kỳ', durationMin: 45,
      questions: [
        { stem: 'Hàm $y=x^2-4x+1$ đạt cực tiểu tại?', options: ['$x=-2$', '$x=2$', '$x=1$', '$x=4$'], answer: 1, explanation: '$y\'=2x-4=0\\Rightarrow x=2$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 3x^2\\,dx$.', options: ['$1$', '$3$', '$\\tfrac13$', '$2$'], answer: 0, explanation: '$[x^3]_0^1=1$.' },
        { stem: 'Cho $P(A\\cap B)=0{,}3$, $P(B)=0{,}6$. Tính $P(A\\mid B)$.', options: ['$0{,}18$', '$0{,}9$', '$0{,}5$', '$0{,}3$'], answer: 2, explanation: '$0{,}3/0{,}6=0{,}5$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{x-2}{x+3}$ là?', options: ['$y=-2$', '$x=-3$', '$y=2$', '$y=1$'], answer: 3, explanation: '$\\lim y=1$.' },
        { stem: 'Số điểm cực trị của $y=x^4-2x^2$ là?', options: ['$1$', '$3$', '$2$', '$0$'], answer: 1, explanation: '$y\'=4x(x^2-1)$ có 3 nghiệm.' },
        { stem: '$\\displaystyle\\int \\cos x\\,dx$ bằng?', options: ['$\\sin x+C$', '$-\\sin x+C$', '$\\cos x$', '$-\\cos x+C$'], answer: 0, explanation: '$\\int\\cos x dx=\\sin x+C$.' },
        { stem: 'Khoảng biến thiên của mẫu $3,8,15$ là?', options: ['$15$', '$3$', '$12$', '$8$'], answer: 2, explanation: '$15-3=12$.' },
        { stem: 'Khoảng cách từ $O$ đến mặt phẳng $x+2y+2z-6=0$ là?', options: ['$6$', '$3$', '$1$', '$2$'], answer: 3, explanation: '$\\dfrac{6}{\\sqrt{1+4+4}}=2$.' },
        { stem: 'Độ dài $\\vec{AB}$ với $A(0;0;0)$, $B(1;2;2)$ là?', options: ['$3$', '$5$', '$9$', '$\\sqrt5$'], answer: 0, explanation: '$\\sqrt{1+4+4}=3$.' },
        { stem: 'Cho $y=x^3-3x$. Giá trị $y(1)$ là?', options: ['$2$', '$-2$', '$0$', '$-4$'], answer: 1, explanation: '$1-3=-2$.' },
      ],
    },
    {
      examId: 'kt45-9', title: 'Kiểm tra 45′ #9 — Hình học tọa độ không gian', durationMin: 45,
      questions: [
        { stem: 'Vectơ pháp tuyến của mặt phẳng $(Oxy)$ (tức $z=0$) là?', options: ['$(1;0;0)$', '$(0;1;0)$', '$(0;0;1)$', '$(1;1;0)$'], answer: 2, explanation: 'Mặt phẳng $z=0$ có VTPT $(0;0;1)$.' },
        { stem: 'Giao điểm của $d:x=t,y=2t,z=3t$ với mặt phẳng $z=3$ là?', options: ['$(1;2;3)$', '$(0;0;3)$', '$(3;6;9)$', '$(1;1;1)$'], answer: 0, explanation: '$z=3t=3\\Rightarrow t=1$.' },
        { stem: 'Phương trình mặt cầu tâm $O$ bán kính $2$ là?', options: ['$x^2+y^2+z^2=2$', '$x^2+y^2+z^2=4$', '$x^2+y^2+z^2=1$', '$x^2+y^2+z^2=16$'], answer: 1, explanation: '$R^2=4$.' },
        { stem: 'Khoảng cách từ $M(2;0;0)$ đến gốc $O$ là?', options: ['$4$', '$1$', '$\\sqrt2$', '$2$'], answer: 3, explanation: '$OM=2$.' },
        { stem: 'Hai mặt phẳng $x+y+z=0$ và $2x+2y+2z=5$ có vị trí?', options: ['Song song', 'Cắt nhau', 'Trùng nhau', 'Vuông góc'], answer: 0, explanation: 'VTPT cùng phương, hằng số khác ⇒ song song.' },
        { stem: 'Vectơ pháp tuyến của $2x-y+2z-3=0$ là?', options: ['$(2;1;2)$', '$(2;-1;2)$', '$(2;-1;-2)$', '$(-2;1;2)$'], answer: 1, explanation: 'Hệ số $x,y,z$.' },
        { stem: 'Trung điểm của $A(1;3;5)$ và $B(3;1;-1)$ là?', options: ['$(4;4;4)$', '$(1;1;1)$', '$(2;2;2)$', '$(2;2;3)$'], answer: 2, explanation: '$\\left(\\tfrac{1+3}{2};\\tfrac{3+1}{2};\\tfrac{5-1}{2}\\right)$.' },
        { stem: 'Khoảng cách từ $O$ đến mặt phẳng $z=5$ là?', options: ['$5$', '$0$', '$1$', '$25$'], answer: 0, explanation: '$\\dfrac{|-5|}{1}=5$.' },
        { stem: 'Đường thẳng qua $O$ có VTCP $(1;1;1)$ có dạng tham số?', options: ['$x=1,y=1,z=1$', '$x=t,y=2t,z=3t$', '$x=0$', '$x=t,y=t,z=t$'], answer: 3, explanation: 'Qua $O$, VTCP $(1;1;1)$.' },
        { stem: 'Tâm mặt cầu $x^2+y^2+z^2-6z=0$ là?', options: ['$(0;0;-3)$', '$(0;0;3)$', '$(0;0;6)$', '$(0;3;0)$'], answer: 1, explanation: '$-2c=-6\\Rightarrow c=3$, $I(0;0;3)$.' },
      ],
    },
    {
      examId: 'kt45-10', title: 'Kiểm tra 45′ #10 — Tổng hợp cuối kỳ', durationMin: 45,
      questions: [
        { stem: 'Số điểm cực trị của $y=x^3-3x^2+4$ là?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 2, explanation: '$y\'=3x^2-6x=3x(x-2)$ có 2 nghiệm.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (x+1)\\,dx$.', options: ['$\\tfrac32$', '$1$', '$2$', '$\\tfrac12$'], answer: 0, explanation: '$[x^2/2+x]_0^1=\\tfrac32$.' },
        { stem: 'Cho $P(A)=0{,}6$, $P(B\\mid A)=0{,}5$. Tính $P(A\\cap B)$.', options: ['$0{,}6$', '$0{,}3$', '$1{,}1$', '$0{,}5$'], answer: 1, explanation: '$P(A)P(B\\mid A)=0{,}3$.' },
        { stem: 'GTNN của $y=x^2-6x+10$ trên $\\mathbb{R}$ là?', options: ['$10$', '$3$', '$0$', '$1$'], answer: 3, explanation: '$y=(x-3)^2+1\\ge 1$.' },
        { stem: 'Tiệm cận đứng của $y=\\dfrac{2x+1}{x-1}$ là?', options: ['$x=1$', '$y=2$', '$x=-1$', '$y=1$'], answer: 0, explanation: 'Mẫu $=0\\Leftrightarrow x=1$.' },
        { stem: '$\\displaystyle\\int \\sin x\\,dx$ bằng?', options: ['$\\cos x+C$', '$\\sin x+C$', '$-\\cos x+C$', '$-\\sin x+C$'], answer: 2, explanation: '$\\int\\sin x dx=-\\cos x+C$.' },
        { stem: 'Độ dài $\\vec{u}=(3;4;0)$ là?', options: ['$7$', '$5$', '$25$', '$\\sqrt7$'], answer: 1, explanation: '$\\sqrt{9+16}=5$.' },
        { stem: 'Trung vị của mẫu $2,4,6,8,10$ là?', options: ['$4$', '$8$', '$5$', '$6$'], answer: 3, explanation: 'Số ở giữa là $6$.' },
        { stem: 'Đạo hàm của $y=x^2$ là?', options: ['$2x$', '$x^2$', '$2$', '$x$'], answer: 0, explanation: '$(x^2)\'=2x$.' },
        { stem: 'Bán kính mặt cầu $(x-2)^2+y^2+z^2=9$ là?', options: ['$9$', '$\\sqrt3$', '$3$', '$6$'], answer: 2, explanation: '$R=\\sqrt9=3$.' },
      ],
    },
    {
      examId: 'hk-1', title: 'Đề thi Học kỳ #1 — Tổng hợp Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^3-3x^2$ đồng biến trên?', options: ['$(0;2)$', '$(-\\infty;0)$ và $(2;+\\infty)$', '$\\mathbb{R}$', '$(2;+\\infty)$'], answer: 1, explanation: '$y\'=3x(x-2)>0\\Leftrightarrow x<0$ hoặc $x>2$.' },
        { stem: 'Giá trị cực đại của $y=-x^2+4x-1$ là?', options: ['$1$', '$2$', '$3$', '$4$'], answer: 2, explanation: '$x=2\\Rightarrow y=3$.' },
        { stem: 'GTLN của $y=x^3-3x$ trên $[0;2]$ là?', options: ['$2$', '$0$', '$-2$', '$6$'], answer: 0, explanation: '$y(2)=2$ là lớn nhất.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 x^2\\,dx$.', options: ['$1$', '$3$', '$\\tfrac12$', '$\\tfrac13$'], answer: 3, explanation: '$[x^3/3]_0^1=\\tfrac13$.' },
        { stem: '$\\displaystyle\\int (2x+1)\\,dx$ bằng?', options: ['$2$', '$x^2+x+C$', '$2x^2+x$', '$x^2+1$'], answer: 1, explanation: '$x^2+x+C$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{3x-1}{x+2}$ là?', options: ['$y=3$', '$x=-2$', '$y=-1$', '$x=3$'], answer: 0, explanation: '$\\lim y=3$.' },
        { stem: 'Số điểm cực trị của $y=x^4-2x^2+1$ là?', options: ['$1$', '$2$', '$3$', '$0$'], answer: 2, explanation: '$y\'=4x(x^2-1)$ có 3 nghiệm.' },
        { stem: 'Thể tích khi quay $y=\\sqrt{x}$ quanh $Ox$ từ $0$ đến $1$ là?', options: ['$\\pi$', '$\\dfrac{\\pi}{2}$', '$\\dfrac{\\pi}{3}$', '$2\\pi$'], answer: 1, explanation: '$V=\\pi\\int_0^1 x\\,dx=\\dfrac{\\pi}{2}$.' },
        { stem: 'Cho $P(A\\cap B)=0{,}2$, $P(B)=0{,}5$. Tính $P(A\\mid B)$.', options: ['$0{,}1$', '$0{,}25$', '$0{,}7$', '$0{,}4$'], answer: 3, explanation: '$0{,}2/0{,}5=0{,}4$.' },
        { stem: 'Độ dài $\\vec{AB}$ với $A(1;0;0)$, $B(1;3;4)$ là?', options: ['$5$', '$7$', '$25$', '$\\sqrt7$'], answer: 0, explanation: '$\\sqrt{0+9+16}=5$.' },
        { stem: 'Vectơ pháp tuyến của $2x+y-2z+1=0$ là?', options: ['$(2;1;2)$', '$(2;-1;-2)$', '$(2;1;-2)$', '$(-2;1;2)$'], answer: 2, explanation: 'Hệ số $x,y,z$.' },
        { stem: 'Tâm mặt cầu $x^2+y^2+z^2-4x=0$ là?', options: ['$(-2;0;0)$', '$(2;0;0)$', '$(4;0;0)$', '$(0;0;2)$'], answer: 1, explanation: '$-2a=-4\\Rightarrow a=2$.' },
        { stem: 'Khoảng biến thiên của mẫu $5,9,14$ là?', options: ['$14$', '$5$', '$19$', '$9$'], answer: 3, explanation: '$14-5=9$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi/2}\\cos x\\,dx$.', options: ['$1$', '$0$', '$2$', '$-1$'], answer: 0, explanation: '$[\\sin x]_0^{\\pi/2}=1$.' },
        { stem: 'Đạo hàm của $y=\\ln x$ là?', options: ['$x$', '$e^x$', '$\\dfrac{1}{x}$', '$\\ln x$'], answer: 2, explanation: '$(\\ln x)\'=\\dfrac{1}{x}$.' },
      ],
    },
    {
      examId: 'hk-2', title: 'Đề thi Học kỳ #2 — Tổng hợp Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=-x^3+3x$ đồng biến trên?', options: ['$(-1;1)$', '$(0;1)$', '$\\mathbb{R}$', '$(1;+\\infty)$'], answer: 0, explanation: '$y\'=-3x^2+3>0\\Leftrightarrow -1<x<1$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 e^x\\,dx$.', options: ['$e$', '$1$', '$e-1$', '$0$'], answer: 2, explanation: '$[e^x]_0^1=e-1$.' },
        { stem: 'Giá trị cực tiểu của $y=x^3-3x$ là?', options: ['$2$', '$-2$', '$0$', '$-4$'], answer: 1, explanation: 'Tại $x=1$, $y=-2$.' },
        { stem: 'Tiệm cận đứng của $y=\\dfrac{x+1}{x-2}$ là?', options: ['$y=2$', '$x=-1$', '$y=1$', '$x=2$'], answer: 3, explanation: 'Mẫu $=0\\Leftrightarrow x=2$.' },
        { stem: '$\\displaystyle\\int x\\,dx$ bằng?', options: ['$\\dfrac{x^2}{2}+C$', '$1$', '$2x$', '$x^2+C$'], answer: 0, explanation: '$\\dfrac{x^2}{2}+C$.' },
        { stem: 'Phương trình $y\'=0$ của $y=x^3+3x^2$ có mấy nghiệm?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 2, explanation: '$y\'=3x(x+2)\\Rightarrow x=0,-2$.' },
        { stem: 'Khoảng cách từ $M(1;1;1)$ đến mặt phẳng $x+y+z-6=0$ là?', options: ['$3$', '$\\sqrt3$', '$1$', '$\\sqrt2$'], answer: 1, explanation: '$\\dfrac{|3-6|}{\\sqrt3}=\\sqrt3$.' },
        { stem: '$A,B$ độc lập, $P(A)=0{,}5$, $P(B)=0{,}4$. Tính $P(A\\cap B)$.', options: ['$0{,}9$', '$0{,}1$', '$0{,}45$', '$0{,}2$'], answer: 3, explanation: '$0{,}5\\cdot0{,}4=0{,}2$.' },
        { stem: 'Tính $\\displaystyle\\int_1^2 3x^2\\,dx$.', options: ['$7$', '$8$', '$9$', '$6$'], answer: 0, explanation: '$[x^3]_1^2=8-1=7$.' },
        { stem: 'Vectơ chỉ phương của $d:x=2-t,\\ y=1+2t,\\ z=3t$ là?', options: ['$(2;1;0)$', '$(1;2;3)$', '$(-1;2;3)$', '$(1;-2;3)$'], answer: 2, explanation: 'Hệ số của $t$: $(-1;2;3)$.' },
        { stem: 'Số trung bình của mẫu $2,4,6,8$ là?', options: ['$4$', '$5$', '$6$', '$20$'], answer: 1, explanation: '$\\dfrac{20}{4}=5$.' },
        { stem: 'Mặt cầu tâm $I(0;1;0)$ bán kính $2$ có phương trình?', options: ['$x^2+y^2+z^2=4$', '$x^2+(y-1)^2+z^2=2$', '$(x-1)^2+y^2+z^2=4$', '$x^2+(y-1)^2+z^2=4$'], answer: 3, explanation: 'Tâm $(0;1;0)$, $R^2=4$.' },
        { stem: 'GTNN của $y=x+\\dfrac{4}{x}$ trên $(0;+\\infty)$ là?', options: ['$4$', '$2$', '$8$', '$0$'], answer: 0, explanation: 'Đạt tại $x=2$ (Cô-si), $y=4$.' },
        { stem: '$\\displaystyle\\int \\cos(2x)\\,dx$ bằng?', options: ['$-\\tfrac12\\sin2x+C$', '$2\\sin2x+C$', '$\\tfrac12\\sin2x+C$', '$\\sin2x+C$'], answer: 2, explanation: '$\\tfrac12\\sin2x+C$.' },
        { stem: 'Đạo hàm của $y=e^{2x}$ là?', options: ['$e^{2x}$', '$2e^{2x}$', '$\\tfrac12 e^{2x}$', '$2e^x$'], answer: 1, explanation: '$(e^{2x})\'=2e^{2x}$.' },
      ],
    },
    {
      examId: 'hk-3', title: 'Đề thi Học kỳ #3 — Tổng hợp Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^3+1$ đồng biến trên?', options: ['$(0;+\\infty)$', '$(-\\infty;0)$', '$\\mathbb{R}$', 'không khoảng nào'], answer: 2, explanation: '$y\'=3x^2\\ge0$ ⇒ đồng biến trên $\\mathbb{R}$.' },
        { stem: 'Tính $\\displaystyle\\int_0^2 (x+1)\\,dx$.', options: ['$4$', '$2$', '$6$', '$3$'], answer: 0, explanation: '$[x^2/2+x]_0^2=2+2=4$.' },
        { stem: 'GTLN của $y=-x^2+2x+3$ trên $\\mathbb{R}$ là?', options: ['$1$', '$2$', '$3$', '$4$'], answer: 3, explanation: 'Tại $x=1$, $y=4$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{x+2}{2x-1}$ là?', options: ['$y=2$', '$y=\\tfrac12$', '$x=\\tfrac12$', '$y=1$'], answer: 1, explanation: '$\\lim y=\\dfrac{1}{2}$.' },
        { stem: '$\\displaystyle\\int 6x^2\\,dx$ bằng?', options: ['$6x+C$', '$3x^3+C$', '$2x^3+C$', '$x^3+C$'], answer: 2, explanation: '$2x^3+C$.' },
        { stem: 'Giá trị cực đại của $y=x^3-12x$ là?', options: ['$16$', '$-16$', '$0$', '$8$'], answer: 0, explanation: '$y\'=3x^2-12=0\\Rightarrow x=\\pm2$; tại $x=-2$, $y=16$.' },
        { stem: 'Độ dài $\\vec{u}=(1;2;2)$ là?', options: ['$5$', '$3$', '$9$', '$\\sqrt5$'], answer: 1, explanation: '$\\sqrt{1+4+4}=3$.' },
        { stem: 'Cho $P(A\\cap B)=0{,}12$, $P(A\\mid B)=0{,}3$. Tính $P(B)$.', options: ['$0{,}036$', '$0{,}3$', '$0{,}12$', '$0{,}4$'], answer: 3, explanation: '$P(B)=\\dfrac{0{,}12}{0{,}3}=0{,}4$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi}\\sin x\\,dx$.', options: ['$0$', '$1$', '$2$', '$-1$'], answer: 2, explanation: '$[-\\cos x]_0^\\pi=2$.' },
        { stem: 'Vectơ pháp tuyến của mặt phẳng $(Oxz)$ (tức $y=0$) là?', options: ['$(0;1;0)$', '$(1;0;0)$', '$(0;0;1)$', '$(1;1;0)$'], answer: 0, explanation: 'Mặt phẳng $y=0$ có VTPT $(0;1;0)$.' },
        { stem: 'Phương sai của mẫu $2,2,2$ là?', options: ['$2$', '$0$', '$1$', '$4$'], answer: 1, explanation: 'Mọi giá trị bằng nhau ⇒ phương sai $0$.' },
        { stem: 'Số điểm cực trị của $y=x^3$ là?', options: ['$1$', '$2$', '$3$', '$0$'], answer: 3, explanation: '$y\'=3x^2\\ge0$ không đổi dấu ⇒ 0 cực trị.' },
        { stem: 'Khoảng cách từ $O$ đến mặt phẳng $2x-y+2z-9=0$ là?', options: ['$3$', '$9$', '$1$', '$\\sqrt3$'], answer: 0, explanation: '$\\dfrac{|-9|}{\\sqrt{4+1+4}}=3$.' },
        { stem: 'Tính $\\displaystyle\\int_1^{e^2} \\dfrac{1}{x}\\,dx$.', options: ['$e^2$', '$1$', '$2$', '$e$'], answer: 2, explanation: '$[\\ln x]_1^{e^2}=2$.' },
        { stem: 'Đạo hàm của $y=\\sin x$ là?', options: ['$-\\cos x$', '$\\cos x$', '$\\sin x$', '$-\\sin x$'], answer: 1, explanation: '$(\\sin x)\'=\\cos x$.' },
      ],
    },
    {
      examId: 'hk-4', title: 'Đề thi Học kỳ #4 — Tổng hợp Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^3-6x^2+9x$ đồng biến trên?', options: ['$(1;3)$', '$\\mathbb{R}$', '$(-\\infty;1)$ và $(3;+\\infty)$', '$(3;+\\infty)$'], answer: 2, explanation: '$y\'=3(x-1)(x-3)>0\\Leftrightarrow x<1$ hoặc $x>3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 4x^3\\,dx$.', options: ['$1$', '$4$', '$\\tfrac12$', '$2$'], answer: 0, explanation: '$[x^4]_0^1=1$.' },
        { stem: 'Giá trị cực tiểu của $y=x^2-4x+1$ là?', options: ['$1$', '$3$', '$0$', '$-3$'], answer: 3, explanation: 'Tại $x=2$, $y=-3$.' },
        { stem: 'Tiệm cận đứng của $y=\\dfrac{2x}{x+4}$ là?', options: ['$x=4$', '$x=-4$', '$y=2$', '$x=2$'], answer: 1, explanation: 'Mẫu $=0\\Leftrightarrow x=-4$.' },
        { stem: '$\\displaystyle\\int (x^2+1)\\,dx$ bằng?', options: ['$2x$', '$x^3+x$', '$\\dfrac{x^3}{3}+x+C$', '$x^3+C$'], answer: 2, explanation: '$\\dfrac{x^3}{3}+x+C$.' },
        { stem: 'GTLN của $y=x^3-3x^2$ trên $[1;3]$ là?', options: ['$0$', '$-2$', '$-4$', '$27$'], answer: 0, explanation: '$y(1)=-2,y(2)=-4,y(3)=0$.' },
        { stem: 'Khoảng cách từ $A(2;1;0)$ đến mặt phẳng $x-2y+2z+1=0$ là?', options: ['$1$', '$3$', '$\\tfrac{2}{3}$', '$\\tfrac13$'], answer: 3, explanation: '$\\dfrac{|2-2+0+1|}{3}=\\dfrac13$.' },
        { stem: 'Cho $P(A)=0{,}4$, $P(A\\cap B)=0{,}1$. Tính $P(B\\mid A)$.', options: ['$0{,}04$', '$0{,}25$', '$0{,}5$', '$0{,}1$'], answer: 1, explanation: '$\\dfrac{0{,}1}{0{,}4}=0{,}25$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi/2}\\sin x\\,dx$.', options: ['$0$', '$-1$', '$1$', '$2$'], answer: 2, explanation: '$[-\\cos x]_0^{\\pi/2}=1$.' },
        { stem: 'VTPT mặt phẳng qua $A(1;0;0),B(0;1;0),C(0;0;1)$ là?', options: ['$(1;1;1)$', '$(1;1;0)$', '$(1;0;1)$', '$(0;1;1)$'], answer: 0, explanation: 'Mặt phẳng $x+y+z=1$.' },
        { stem: 'Trung vị của mẫu $1,3,3,6,7,8,9$ là?', options: ['$3$', '$7$', '$8$', '$6$'], answer: 3, explanation: 'Số ở giữa (vị trí 4) là $6$.' },
        { stem: 'Tâm mặt cầu $x^2+y^2+z^2+2x-4y=0$ là?', options: ['$(1;-2;0)$', '$(-1;2;0)$', '$(2;-4;0)$', '$(-1;2;1)$'], answer: 1, explanation: '$-2a=2\\Rightarrow a=-1$; $-2b=-4\\Rightarrow b=2$.' },
        { stem: 'Số nghiệm thực của $x^3-3x=0$ là?', options: ['$1$', '$2$', '$3$', '$0$'], answer: 2, explanation: '$x(x^2-3)=0\\Rightarrow x=0,\\pm\\sqrt3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\ln 2} e^x\\,dx$.', options: ['$1$', '$2$', '$\\ln 2$', '$0$'], answer: 0, explanation: '$[e^x]_0^{\\ln2}=2-1=1$.' },
        { stem: 'Đạo hàm của $y=\\cos x$ là?', options: ['$\\sin x$', '$\\cos x$', '$\\tan x$', '$-\\sin x$'], answer: 3, explanation: '$(\\cos x)\'=-\\sin x$.' },
      ],
    },
    {
      examId: 'hk-5', title: 'Đề thi Học kỳ #5 — Tổng hợp Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^4-4x^2$ đồng biến trên?', options: ['$(0;\\sqrt2)$', '$(-\\sqrt2;0)$ và $(\\sqrt2;+\\infty)$', '$\\mathbb{R}$', '$(2;+\\infty)$'], answer: 1, explanation: '$y\'=4x(x^2-2)>0$ trên $(-\\sqrt2;0)\\cup(\\sqrt2;+\\infty)$.' },
        { stem: 'Tính $\\displaystyle\\int_0^2 3x^2\\,dx$.', options: ['$2$', '$4$', '$6$', '$8$'], answer: 3, explanation: '$[x^3]_0^2=8$.' },
        { stem: 'GTNN của $y=x^2+1$ trên $\\mathbb{R}$ là?', options: ['$1$', '$0$', '$-1$', '$2$'], answer: 0, explanation: 'Đạt tại $x=0$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{5x}{x-1}$ là?', options: ['$x=1$', '$y=1$', '$y=5$', '$x=5$'], answer: 2, explanation: '$\\lim y=5$.' },
        { stem: '$\\displaystyle\\int (2x-3)\\,dx$ bằng?', options: ['$2$', '$x^2-3x+C$', '$2x^2-3x$', '$x^2-3$'], answer: 1, explanation: '$x^2-3x+C$.' },
        { stem: 'Số điểm cực trị của $y=x^4-4x^2$ là?', options: ['$1$', '$2$', '$3$', '$0$'], answer: 2, explanation: '$y\'=4x(x^2-2)$ có 3 nghiệm.' },
        { stem: 'Độ dài $\\vec{AB}$ với $A(0;0;0),B(2;3;6)$ là?', options: ['$7$', '$5$', '$49$', '$\\sqrt7$'], answer: 0, explanation: '$\\sqrt{4+9+36}=7$.' },
        { stem: 'Cho $P(A\\mid B)=0{,}6$, $P(B)=0{,}5$. Tính $P(A\\cap B)$.', options: ['$1{,}1$', '$0{,}12$', '$0{,}5$', '$0{,}3$'], answer: 3, explanation: '$0{,}6\\cdot0{,}5=0{,}3$.' },
        { stem: 'Tính $\\displaystyle\\int_1^2 (2x+1)\\,dx$.', options: ['$2$', '$4$', '$6$', '$3$'], answer: 1, explanation: '$[x^2+x]_1^2=6-2=4$.' },
        { stem: 'Mặt phẳng qua $O$ với pháp tuyến $(3;0;4)$ có phương trình?', options: ['$3x+4y=0$', '$4x+3z=0$', '$3x+4z=0$', '$3x+4z+1=0$'], answer: 2, explanation: 'Qua $O$ ⇒ $3x+4z=0$.' },
        { stem: 'Số trung bình của $10,20,30,40$ là?', options: ['$25$', '$30$', '$20$', '$100$'], answer: 0, explanation: '$\\dfrac{100}{4}=25$.' },
        { stem: 'Bán kính mặt cầu $x^2+y^2+z^2-2x-2y-2z=0$ là?', options: ['$3$', '$1$', '$9$', '$\\sqrt3$'], answer: 3, explanation: '$R=\\sqrt{1+1+1-0}=\\sqrt3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi/2}\\cos x\\,dx$.', options: ['$0$', '$1$', '$2$', '$-1$'], answer: 1, explanation: '$[\\sin x]_0^{\\pi/2}=1$.' },
        { stem: 'Đạo hàm của $y=2x^3$ là?', options: ['$6x^2$', '$2x^2$', '$3x^2$', '$6x$'], answer: 0, explanation: '$(2x^3)\'=6x^2$.' },
        { stem: 'Tiệm cận đứng của $y=\\dfrac{3}{2x-6}$ là?', options: ['$x=-3$', '$x=6$', '$x=3$', '$x=2$'], answer: 2, explanation: '$2x-6=0\\Leftrightarrow x=3$.' },
      ],
    },
    {
      examId: 'ck-1', title: 'Đề thi Cuối kỳ #1 — Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^3-3x^2+2$ đồng biến trên?', options: ['$(0;2)$', '$\\mathbb{R}$', '$(2;+\\infty)$', '$(-\\infty;0)$ và $(2;+\\infty)$'], answer: 3, explanation: '$y\'=3x(x-2)>0\\Leftrightarrow x<0$ hoặc $x>2$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (3x^2+2x)\\,dx$.', options: ['$1$', '$2$', '$3$', '$\\tfrac12$'], answer: 1, explanation: '$[x^3+x^2]_0^1=2$.' },
        { stem: 'Giá trị cực đại của $y=-x^3+3x$ là?', options: ['$2$', '$-2$', '$0$', '$1$'], answer: 0, explanation: 'Tại $x=1$, $y=2$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{4x-1}{2x+3}$ là?', options: ['$y=4$', '$x=-\\tfrac32$', '$y=2$', '$y=\\tfrac12$'], answer: 2, explanation: '$\\lim y=\\dfrac{4}{2}=2$.' },
        { stem: '$\\displaystyle\\int \\sin(3x)\\,dx$ bằng?', options: ['$\\tfrac13\\cos3x+C$', '$-\\cos3x+C$', '$3\\cos3x$', '$-\\tfrac13\\cos3x+C$'], answer: 3, explanation: '$-\\tfrac13\\cos3x+C$.' },
        { stem: 'GTNN của $y=x^3-3x$ trên $[-2;0]$ là?', options: ['$2$', '$-2$', '$0$', '$-1$'], answer: 1, explanation: '$y(-2)=-2,y(-1)=2,y(0)=0$.' },
        { stem: 'Khoảng cách từ $O$ đến mặt phẳng $2x+y+2z-12=0$ là?', options: ['$4$', '$12$', '$2$', '$\\sqrt2$'], answer: 0, explanation: '$\\dfrac{12}{3}=4$.' },
        { stem: 'Cho $P(A\\cap B)=0{,}15$, $P(B)=0{,}3$. Tính $P(A\\mid B)$.', options: ['$0{,}045$', '$0{,}3$', '$0{,}5$', '$0{,}15$'], answer: 2, explanation: '$0{,}15/0{,}3=0{,}5$.' },
        { stem: 'Tính $\\displaystyle\\int_1^e \\dfrac{2}{x}\\,dx$.', options: ['$1$', '$2$', '$e$', '$2e$'], answer: 1, explanation: '$2[\\ln x]_1^e=2$.' },
        { stem: 'Mặt cầu đường kính $AB$ với $A(0;0;0),B(2;0;0)$ có phương trình?', options: ['$x^2+y^2+z^2=1$', '$(x-2)^2+y^2+z^2=1$', '$(x-1)^2+y^2+z^2=4$', '$(x-1)^2+y^2+z^2=1$'], answer: 3, explanation: 'Tâm $(1;0;0)$, $R=1$.' },
        { stem: 'Trung vị của mẫu $4,6,8,10$ là?', options: ['$6$', '$8$', '$7$', '$9$'], answer: 2, explanation: '$\\dfrac{6+8}{2}=7$.' },
        { stem: 'Số điểm cực trị của $y=x^3-3x^2+3x-1$ là?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 0, explanation: '$y\'=3(x-1)^2\\ge0$ không đổi dấu.' },
        { stem: 'Độ dài vectơ $\\vec{u}=(2;-1;2)$ là?', options: ['$5$', '$3$', '$9$', '$\\sqrt5$'], answer: 1, explanation: '$\\sqrt{4+1+4}=3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 e^{2x}\\,dx$.', options: ['$e^2-1$', '$2(e^2-1)$', '$e^2$', '$\\tfrac12(e^2-1)$'], answer: 3, explanation: '$\\tfrac12[e^{2x}]_0^1=\\tfrac12(e^2-1)$.' },
        { stem: 'Đạo hàm của $y=\\ln(2x)$ là?', options: ['$\\dfrac{1}{2x}$', '$2x$', '$\\dfrac{1}{x}$', '$\\ln 2$'], answer: 2, explanation: '$\\dfrac{2}{2x}=\\dfrac{1}{x}$.' },
      ],
    },
    {
      examId: 'ck-2', title: 'Đề thi Cuối kỳ #2 — Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^3-3x^2-9x$ đồng biến trên?', options: ['$(-1;3)$', '$\\mathbb{R}$', '$(-\\infty;-1)$ và $(3;+\\infty)$', '$(3;+\\infty)$'], answer: 2, explanation: '$y\'=3(x-3)(x+1)>0\\Leftrightarrow x<-1$ hoặc $x>3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (e^x+1)\\,dx$.', options: ['$e$', '$e-1$', '$e+1$', '$1$'], answer: 0, explanation: '$[e^x+x]_0^1=(e+1)-1=e$.' },
        { stem: 'Giá trị cực tiểu của $y=x^3-3x$ là?', options: ['$2$', '$0$', '$-4$', '$-2$'], answer: 3, explanation: 'Tại $x=1$, $y=-2$.' },
        { stem: 'Số đường tiệm cận đứng của $y=\\dfrac{1}{x^2-1}$ là?', options: ['$1$', '$2$', '$0$', '$3$'], answer: 1, explanation: 'Mẫu $=0$ tại $x=\\pm1$.' },
        { stem: '$\\displaystyle\\int (4x^3-1)\\,dx$ bằng?', options: ['$12x^2$', '$x^4+C$', '$x^4-x+C$', '$4x^4-x$'], answer: 2, explanation: '$x^4-x+C$.' },
        { stem: 'GTLN của $y=x^4-2x^2+3$ trên $[0;2]$ là?', options: ['$11$', '$3$', '$2$', '$8$'], answer: 0, explanation: '$y(0)=3,y(1)=2,y(2)=11$.' },
        { stem: 'Khoảng cách giữa $A(1;2;2)$ và $B(4;6;14)$ là?', options: ['$12$', '$169$', '$\\sqrt{14}$', '$13$'], answer: 3, explanation: '$\\vec{AB}=(3;4;12),\\ |\\vec{AB}|=\\sqrt{169}=13$.' },
        { stem: '$A,B$ độc lập, $P(A)=0{,}3$, $P(B)=0{,}6$. Tính $P(A\\cup B)$.', options: ['$0{,}9$', '$0{,}72$', '$0{,}18$', '$0{,}3$'], answer: 1, explanation: '$0{,}3+0{,}6-0{,}18=0{,}72$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi}\\cos x\\,dx$.', options: ['$2$', '$1$', '$0$', '$-1$'], answer: 2, explanation: '$[\\sin x]_0^\\pi=0$.' },
        { stem: 'Độ dài vectơ pháp tuyến của $2x-3y+6z-7=0$ là?', options: ['$7$', '$49$', '$5$', '$\\sqrt7$'], answer: 0, explanation: '$|(2;-3;6)|=\\sqrt{49}=7$.' },
        { stem: 'Mốt (giá trị xuất hiện nhiều nhất) của mẫu $2,2,3,5,5,5,7$ là?', options: ['$2$', '$3$', '$7$', '$5$'], answer: 3, explanation: '$5$ xuất hiện 3 lần.' },
        { stem: 'Hàm $y=x^3+x$ đồng biến trên?', options: ['$(0;+\\infty)$', '$\\mathbb{R}$', '$(-\\infty;0)$', 'không khoảng nào'], answer: 1, explanation: '$y\'=3x^2+1>0\\ \\forall x$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 2\\,dx$.', options: ['$2$', '$1$', '$0$', '$4$'], answer: 0, explanation: '$[2x]_0^1=2$.' },
        { stem: 'Đạo hàm của $y=\\tan x$ là?', options: ['$-\\dfrac{1}{\\sin^2 x}$', '$\\cos x$', '$\\dfrac{1}{\\cos^2 x}$', '$\\sin x$'], answer: 2, explanation: '$(\\tan x)\'=\\dfrac{1}{\\cos^2 x}$.' },
        { stem: 'Số nghiệm thực của $x^4-5x^2+4=0$ là?', options: ['$1$', '$2$', '$3$', '$4$'], answer: 3, explanation: '$(x^2-1)(x^2-4)=0\\Rightarrow x=\\pm1,\\pm2$.' },
      ],
    },
    {
      examId: 'ck-3', title: 'Đề thi Cuối kỳ #3 — Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=2x^3-3x^2+1$ nghịch biến trên?', options: ['$(-\\infty;0)$', '$\\mathbb{R}$', '$(0;1)$', '$(1;+\\infty)$'], answer: 2, explanation: '$y\'=6x(x-1)<0\\Leftrightarrow 0<x<1$.' },
        { stem: 'Tính $\\displaystyle\\int_0^2 x^3\\,dx$.', options: ['$4$', '$8$', '$2$', '$16$'], answer: 0, explanation: '$[x^4/4]_0^2=4$.' },
        { stem: 'Giá trị cực đại của $y=x^3-3x^2$ là?', options: ['$2$', '$-4$', '$1$', '$0$'], answer: 3, explanation: 'Tại $x=0$, $y=0$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{1-2x}{x+1}$ là?', options: ['$y=2$', '$y=-2$', '$x=-1$', '$y=1$'], answer: 1, explanation: '$\\lim y=-2$.' },
        { stem: '$\\displaystyle\\int \\dfrac{1}{x+1}\\,dx$ bằng?', options: ['$\\ln x+C$', '$\\dfrac{1}{(x+1)^2}$', '$\\ln|x+1|+C$', '$\\dfrac{-1}{(x+1)^2}$'], answer: 2, explanation: '$\\ln|x+1|+C$.' },
        { stem: 'GTLN của $y=-x^2+4x-1$ trên $[0;3]$ là?', options: ['$3$', '$-1$', '$2$', '$-9$'], answer: 0, explanation: 'Tại $x=2$, $y=3$.' },
        { stem: 'Điểm $M(1;1;1)$ có thuộc mặt phẳng $x+y-z+2=0$ không?', options: ['Có', 'Không', 'Không xác định', 'Chỉ khi $x=0$'], answer: 1, explanation: '$1+1-1+2=3\\ne0$.' },
        { stem: 'Cho $P(B\\mid A)=0{,}5$, $P(A)=0{,}6$. Tính $P(A\\cap B)$.', options: ['$0{,}83$', '$1{,}1$', '$0{,}5$', '$0{,}3$'], answer: 3, explanation: '$0{,}5\\cdot0{,}6=0{,}3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (x^2+x)\\,dx$.', options: ['$1$', '$\\tfrac12$', '$\\tfrac56$', '$\\tfrac13$'], answer: 2, explanation: '$\\tfrac13+\\tfrac12=\\tfrac56$.' },
        { stem: 'VTCP của $d:\\dfrac{x-1}{1}=\\dfrac{y+2}{2}=\\dfrac{z}{3}$ là?', options: ['$(1;2;3)$', '$(1;-2;0)$', '$(-1;2;3)$', '$(1;2;0)$'], answer: 0, explanation: 'Mẫu số.' },
        { stem: 'Tổng hai nghiệm của $x^2-5x+6=0$ là?', options: ['$2$', '$3$', '$6$', '$5$'], answer: 3, explanation: 'Vi-ét: $S=5$.' },
        { stem: 'Số điểm cực trị của $y=x^4+1$ là?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 1, explanation: '$y\'=4x^3$ đổi dấu tại $x=0$.' },
        { stem: 'Độ dài $\\vec{u}=(0;3;4)$ là?', options: ['$5$', '$7$', '$25$', '$\\sqrt7$'], answer: 0, explanation: '$\\sqrt{9+16}=5$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi/2} 2\\cos x\\,dx$.', options: ['$0$', '$1$', '$2$', '$4$'], answer: 2, explanation: '$2[\\sin x]_0^{\\pi/2}=2$.' },
        { stem: 'Đạo hàm của $y=\\sqrt{x}$ là?', options: ['$\\sqrt x$', '$\\dfrac{1}{\\sqrt x}$', '$2\\sqrt x$', '$\\dfrac{1}{2\\sqrt x}$'], answer: 3, explanation: '$(x^{1/2})\'=\\tfrac12 x^{-1/2}$.' },
      ],
    },
    {
      examId: 'ck-4', title: 'Đề thi Cuối kỳ #4 — Toán 12', durationMin: 90,
      questions: [
        { stem: 'Hàm $y=x^3+3x^2+3x+1$ đồng biến trên?', options: ['$(0;\\infty)$', '$(-1;\\infty)$', '$\\mathbb{R}$', 'không khoảng nào'], answer: 2, explanation: '$y\'=3(x+1)^2\\ge0$.' },
        { stem: 'Tính $\\displaystyle\\int_1^2 \\dfrac{1}{x^2}\\,dx$.', options: ['$\\tfrac12$', '$1$', '$2$', '$-\\tfrac12$'], answer: 0, explanation: '$[-1/x]_1^2=-\\tfrac12+1=\\tfrac12$.' },
        { stem: 'Giá trị cực tiểu của $y=x^2+2x$ là?', options: ['$1$', '$0$', '$2$', '$-1$'], answer: 3, explanation: 'Tại $x=-1$, $y=-1$.' },
        { stem: 'Số đường tiệm cận đứng của $y=\\dfrac{x}{x^2-4}$ là?', options: ['$1$', '$2$', '$0$', '$3$'], answer: 1, explanation: 'Mẫu $=0$ tại $x=\\pm2$.' },
        { stem: '$\\displaystyle\\int 3\\,dx$ bằng?', options: ['$0$', '$3$', '$3x+C$', '$x+C$'], answer: 2, explanation: '$\\int 3\\,dx=3x+C$.' },
        { stem: 'GTNN của $y=x^3-3x^2+2$ trên $[0;3]$ là?', options: ['$-2$', '$2$', '$0$', '$27$'], answer: 0, explanation: '$y(2)=-2$ nhỏ nhất.' },
        { stem: 'Khoảng cách từ $M(3;0;0)$ đến mặt phẳng $x+y+z=0$ là?', options: ['$3$', '$1$', '$0$', '$\\sqrt3$'], answer: 3, explanation: '$\\dfrac{3}{\\sqrt3}=\\sqrt3$.' },
        { stem: 'Gieo 2 đồng xu cân đối. Xác suất được 2 mặt ngửa là?', options: ['$\\tfrac12$', '$\\tfrac14$', '$\\tfrac13$', '$1$'], answer: 1, explanation: '$\\tfrac12\\cdot\\tfrac12=\\tfrac14$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (6x^2-2x)\\,dx$.', options: ['$2$', '$0$', '$1$', '$3$'], answer: 2, explanation: '$[2x^3-x^2]_0^1=1$.' },
        { stem: 'Phương trình mặt phẳng $(Oyz)$ là?', options: ['$x=0$', '$y=0$', '$z=0$', '$x+y+z=0$'], answer: 0, explanation: 'Mặt phẳng $Oyz$: $x=0$.' },
        { stem: 'Phương sai của mẫu $1,2,3$ là?', options: ['$1$', '$2$', '$\\tfrac13$', '$\\tfrac23$'], answer: 3, explanation: '$\\bar{x}=2$, $s^2=\\tfrac13(1+0+1)=\\tfrac23$.' },
        { stem: 'Số nghiệm thực của $x^3=8$ là?', options: ['$0$', '$1$', '$2$', '$3$'], answer: 1, explanation: 'Chỉ $x=2$.' },
        { stem: 'Khoảng cách giữa $A(2;2;2)$ và $B(0;0;0)$ là?', options: ['$12$', '$6$', '$2\\sqrt3$', '$\\sqrt6$'], answer: 2, explanation: '$\\sqrt{4+4+4}=2\\sqrt3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 e^{-x}\\,dx$.', options: ['$1-\\tfrac1e$', '$\\tfrac1e-1$', '$e-1$', '$1$'], answer: 0, explanation: '$[-e^{-x}]_0^1=1-\\tfrac1e$.' },
        { stem: 'Đạo hàm của $y=x^5$ là?', options: ['$x^4$', '$\\tfrac{x^6}{6}$', '$5x$', '$5x^4$'], answer: 3, explanation: '$(x^5)\'=5x^4$.' },
      ],
    },
    {
      examId: 'ck-5', title: 'Đề thi Cuối kỳ #5 — Toán 12 (tổng hợp)', durationMin: 90,
      questions: [
        { stem: 'Số nghiệm phân biệt của phương trình $x^3-3x+2=0$ là?', options: ['$1$', '$2$', '$3$', '$0$'], answer: 1, explanation: '$(x-1)^2(x+2)=0\\Rightarrow x=1$ (kép), $x=-2$.' },
        { stem: 'Tính $\\displaystyle\\int_0^{\\pi} \\sin(2x)\\,dx$.', options: ['$2$', '$1$', '$-1$', '$0$'], answer: 3, explanation: '$[-\\tfrac12\\cos2x]_0^\\pi=-\\tfrac12+\\tfrac12=0$.' },
        { stem: 'GTLN của $y=4x-x^2$ trên $\\mathbb{R}$ là?', options: ['$4$', '$2$', '$0$', '$8$'], answer: 0, explanation: 'Tại $x=2$, $y=4$.' },
        { stem: 'Tiệm cận ngang của $y=\\dfrac{2x^2+1}{x^2+1}$ là?', options: ['$y=1$', '$y=0$', '$y=2$', '$x=1$'], answer: 2, explanation: 'Bậc tử $=$ bậc mẫu, tỉ số hệ số cao nhất $=2$.' },
        { stem: '$\\displaystyle\\int (\\cos x-\\sin x)\\,dx$ bằng?', options: ['$-\\sin x-\\cos x+C$', '$\\sin x+\\cos x+C$', '$\\cos x-\\sin x$', '$\\sin x-\\cos x+C$'], answer: 1, explanation: '$\\sin x+\\cos x+C$.' },
        { stem: 'Số điểm cực trị của $y=x^3$ là?', options: ['$1$', '$2$', '$3$', '$0$'], answer: 3, explanation: '$y\'=3x^2\\ge0$ không đổi dấu.' },
        { stem: 'Độ dài VTPT của mặt phẳng $3x-6y+2z+1=0$ là?', options: ['$7$', '$49$', '$5$', '$\\sqrt7$'], answer: 0, explanation: '$\\sqrt{9+36+4}=7$.' },
        { stem: 'Cho $P(A)=0{,}2$, $P(B\\mid A)=0{,}5$. Tính $P(A\\cap B)$.', options: ['$0{,}4$', '$0{,}7$', '$0{,}1$', '$0{,}25$'], answer: 2, explanation: '$0{,}2\\cdot0{,}5=0{,}1$.' },
        { stem: 'Tính $\\displaystyle\\int_1^2 x\\,dx$.', options: ['$2$', '$1$', '$\\tfrac12$', '$\\tfrac32$'], answer: 3, explanation: '$[x^2/2]_1^2=2-\\tfrac12=\\tfrac32$.' },
        { stem: 'Mặt cầu tâm $I(1;1;1)$ đi qua gốc $O$ có phương trình?', options: ['$(x-1)^2+(y-1)^2+(z-1)^2=9$', '$(x-1)^2+(y-1)^2+(z-1)^2=3$', '$x^2+y^2+z^2=3$', '$(x-1)^2+(y-1)^2+(z-1)^2=1$'], answer: 1, explanation: '$R=OI=\\sqrt3$.' },
        { stem: 'Trung vị của mẫu $3,5,7,9,11$ là?', options: ['$5$', '$9$', '$7$', '$11$'], answer: 2, explanation: 'Số ở giữa là $7$.' },
        { stem: 'GTNN của $y=x^4-2x^2$ trên $\\mathbb{R}$ là?', options: ['$-1$', '$0$', '$1$', '$-2$'], answer: 0, explanation: 'Tại $x=\\pm1$, $y=-1$.' },
        { stem: 'Độ dài $\\vec{u}=(1;2;-2)$ là?', options: ['$5$', '$3$', '$9$', '$\\sqrt5$'], answer: 1, explanation: '$\\sqrt{1+4+4}=3$.' },
        { stem: 'Tính $\\displaystyle\\int_0^1 (2x+3)\\,dx$.', options: ['$4$', '$2$', '$6$', '$3$'], answer: 0, explanation: '$[x^2+3x]_0^1=4$.' },
        { stem: 'Đạo hàm của $y=e^{-x}$ là?', options: ['$e^{-x}$', '$e^{x}$', '$-e^{-x}$', '$xe^{-x-1}$'], answer: 2, explanation: '$(e^{-x})\'=-e^{-x}$.' },
      ],
    },
  ],

  LY: [
    {
      examId: 'ly-kt45-1', title: 'Kiểm tra 45′ #1 — Vật lí nhiệt & Khí lí tưởng', durationMin: 45,
      questions: [
        { stem: 'Định luật I Nhiệt động lực học: $\\Delta U=$?', options: ['$Q-A$', '$A+Q$', '$A-Q$', '$AQ$'], answer: 1, explanation: '$\\Delta U=A+Q$.' },
        { stem: 'Đun $1$ kg nước ($c=4200$) tăng $5$ °C cần nhiệt lượng?', options: ['$4200$ J', '$21000$ J', '$1000$ J', '$84000$ J'], answer: 1, explanation: '$Q=mc\\Delta t=1\\cdot4200\\cdot5=21000$ J.' },
        { stem: 'Đơn vị của nội năng là?', options: ['Niutơn (N)', 'Oát (W)', 'Jun (J)', 'Paxcan (Pa)'], answer: 2, explanation: 'Nội năng đo bằng jun.' },
        { stem: 'Khí đẳng nhiệt $p_1=2$, $V_1=3$, nén còn $V_2=1$. Tính $p_2$.', options: ['$2$', '$3$', '$6$', '$1$'], answer: 2, explanation: '$p_2=\\dfrac{p_1V_1}{V_2}=6$.' },
        { stem: '$27$ °C bằng bao nhiêu Kelvin?', options: ['$27$', '$300$', '$246$', '$273$'], answer: 1, explanation: '$T=27+273=300$ K.' },
        { stem: 'Đẳng tích: $p_1=1$ atm ở $T_1=300$ K, đun tới $T_2=600$ K. Tính $p_2$.', options: ['$1$', '$2$', '$0{,}5$', '$4$'], answer: 1, explanation: '$\\dfrac{p}{T}$ const ⇒ $p_2=2$ atm.' },
        { stem: 'Trong định luật I, $Q>0$ nghĩa là?', options: ['hệ tỏa nhiệt', 'hệ nhận nhiệt', 'hệ sinh công', 'nội năng không đổi'], answer: 1, explanation: 'Quy ước $Q>0$: nhận nhiệt.' },
        { stem: 'Phương trình trạng thái khí lí tưởng: $\\dfrac{p_1V_1}{T_1}=$?', options: ['$p_2V_2T_2$', '$\\dfrac{T_2}{p_2V_2}$', '$\\dfrac{p_2V_2}{T_2}$', '$p_2+V_2$'], answer: 2, explanation: '$\\dfrac{p_1V_1}{T_1}=\\dfrac{p_2V_2}{T_2}$.' },
        { stem: 'Đơn vị nhiệt dung riêng là?', options: ['J', 'J/kg', 'J/(kg·K)', 'W/K'], answer: 2, explanation: '$c$ đo bằng J/(kg·K).' },
        { stem: 'Khi khí sinh công thì công $A$?', options: ['$A>0$', '$A=0$', '$A<0$', '$A=Q$'], answer: 2, explanation: 'Hệ sinh công ⇒ $A<0$.' },
      ],
    },
    {
      examId: 'ly-kt45-2', title: 'Kiểm tra 45′ #2 — Từ trường & Hạt nhân', durationMin: 45,
      questions: [
        { stem: 'Lực từ lên dây ($B=0{,}2$ T, $I=3$ A, $l=0{,}5$ m, vuông góc) là?', options: ['$0{,}3$ N', '$0{,}1$ N', '$3$ N', '$0{,}6$ N'], answer: 0, explanation: '$F=BIl=0{,}2\\cdot3\\cdot0{,}5=0{,}3$ N.' },
        { stem: 'Đơn vị của cảm ứng từ $B$ là?', options: ['Vêbe (Wb)', 'Tesla (T)', 'Henry (H)', 'Jun (J)'], answer: 1, explanation: '$B$ đo bằng tesla.' },
        { stem: 'Từ thông qua khung $N=5$ vòng, $B=0{,}4$ T, $S=0{,}02$ m², $\\alpha=0$?', options: ['$0{,}4$', '$0{,}04$', '$0{,}004$', '$4$'], answer: 1, explanation: '$\\Phi=NBS=5\\cdot0{,}4\\cdot0{,}02=0{,}04$ Wb.' },
        { stem: 'Từ thông biến thiên $0{,}1$ Wb trong $0{,}5$ s. Suất điện động cảm ứng?', options: ['$0{,}05$ V', '$0{,}5$ V', '$0{,}2$ V', '$2$ V'], answer: 2, explanation: '$|e|=\\dfrac{0{,}1}{0{,}5}=0{,}2$ V.' },
        { stem: 'Hạt nhân $^{4}_{2}He$ có bao nhiêu neutron?', options: ['$4$', '$2$', '$6$', '$0$'], answer: 1, explanation: '$N=A-Z=4-2=2$.' },
        { stem: 'Năng lượng liên kết của hạt nhân tính bằng?', options: ['$\\Delta m\\,c$', '$\\Delta m\\,c^2$', '$mc^2$', '$\\dfrac{\\Delta m}{c^2}$'], answer: 1, explanation: '$W_{lk}=\\Delta m\\,c^2$.' },
        { stem: 'Sau một chu kì bán rã, số hạt nhân còn lại bằng?', options: ['$100\\%$', '$50\\%$', '$25\\%$', '$0\\%$'], answer: 1, explanation: '$N=N_0/2$.' },
        { stem: '$1$ u tương đương xấp xỉ?', options: ['$931{,}5$ MeV/$c^2$', '$1$ MeV', '$3\\cdot10^8$ m/s', '$9{,}1\\cdot10^{-31}$ kg'], answer: 0, explanation: '$1\\,u\\approx931{,}5$ MeV/$c^2$.' },
        { stem: 'Lực Lorentz lên hạt điện tích là?', options: ['$qvB$ (luôn vậy)', '$|q|vB\\sin\\alpha$', '$BIl$', '$qE$'], answer: 1, explanation: '$f=|q|vB\\sin\\alpha$.' },
        { stem: 'Định luật phóng xạ có dạng?', options: ['$N=N_0 2^{t/T}$', '$N=N_0 e^{\\lambda t}$', '$N=N_0 2^{-t/T}$', '$N=N_0 t$'], answer: 2, explanation: '$N=N_0 2^{-t/T}=N_0 e^{-\\lambda t}$.' },
      ],
    },
    {
      examId: 'ly-kt45-3', title: 'Kiểm tra 45′ #3 — Tổng hợp Vật lí 12', durationMin: 45,
      questions: [
        { stem: 'Khí nhận nhiệt $Q=200$ J và sinh công $50$ J. Tính $\\Delta U$.', options: ['$250$ J', '$150$ J', '$50$ J', '$-150$ J'], answer: 1, explanation: '$A=-50,\\ \\Delta U=A+Q=150$ J.' },
        { stem: 'Nhiệt lượng đun $0{,}5$ kg nước tăng $20$ °C ($c=4200$)?', options: ['$4200$ J', '$42000$ J', '$21000$ J', '$84000$ J'], answer: 1, explanation: '$Q=0{,}5\\cdot4200\\cdot20=42000$ J.' },
        { stem: 'Đẳng nhiệt: $p_1=3$, $V_1=2$, sang $p_2=2$. Tính $V_2$.', options: ['$1$', '$2$', '$3$', '$6$'], answer: 2, explanation: '$V_2=\\dfrac{p_1V_1}{p_2}=3$.' },
        { stem: '$0$ °C bằng bao nhiêu Kelvin?', options: ['$0$', '$273$', '$300$', '$-273$'], answer: 1, explanation: '$T=0+273=273$ K.' },
        { stem: 'Lực từ với $B=0{,}5$ T, $I=4$ A, $l=0{,}2$ m (vuông góc)?', options: ['$0{,}4$ N', '$4$ N', '$0{,}1$ N', '$0{,}8$ N'], answer: 0, explanation: '$F=BIl=0{,}5\\cdot4\\cdot0{,}2=0{,}4$ N.' },
        { stem: 'Từ thông $N=2$ vòng, $B=0{,}5$ T, $S=0{,}1$ m², $\\alpha=0$?', options: ['$1$', '$0{,}1$', '$0{,}01$', '$0{,}5$'], answer: 1, explanation: '$\\Phi=NBS=0{,}1$ Wb.' },
        { stem: 'Hạt nhân $^{12}_{6}C$ có bao nhiêu proton?', options: ['$12$', '$6$', '$18$', '$0$'], answer: 1, explanation: '$Z=6$.' },
        { stem: 'Sau 2 chu kì bán rã, còn lại bao nhiêu phần trăm?', options: ['$50\\%$', '$25\\%$', '$12{,}5\\%$', '$75\\%$'], answer: 1, explanation: '$2^{-2}=\\tfrac14=25\\%$.' },
        { stem: 'Hằng số phóng xạ $\\lambda$ liên hệ chu kì bán rã $T$ qua?', options: ['$\\lambda=\\dfrac{T}{\\ln2}$', '$\\lambda=\\ln2\\cdot T$', '$\\lambda=\\dfrac{\\ln2}{T}$', '$\\lambda=2T$'], answer: 2, explanation: '$\\lambda=\\dfrac{\\ln2}{T}$.' },
        { stem: 'Đẳng áp: $V_1=2$ ở $T_1=300$ K, sang $T_2=450$ K. Tính $V_2$.', options: ['$2$', '$3$', '$4{,}5$', '$1{,}5$'], answer: 1, explanation: '$\\dfrac{V}{T}$ const ⇒ $V_2=2\\cdot\\dfrac{450}{300}=3$.' },
      ],
    },
    {
      examId: 'ly-kt45-4', title: 'Kiểm tra 45′ #4 — Tổng hợp Vật lí 12', durationMin: 45,
      questions: [
        { stem: 'Hệ nhận nhiệt $80$ J và nhận công $20$ J. Tính $\\Delta U$.', options: ['$120$ J', '$100$ J', '$60$ J', '$80$ J'], answer: 1, explanation: '$\\Delta U=A+Q=20+80=100$ J.' },
        { stem: 'Đơn vị của nhiệt lượng là?', options: ['Jun (J)', 'Tesla (T)', 'Oát (W)', 'Vêbe (Wb)'], answer: 0, explanation: 'Nhiệt lượng đo bằng jun.' },
        { stem: 'Khí đẳng nhiệt $p_1=4$, $V_1=1$, khi $p_2=2$ thì $V_2$=?', options: ['$1$', '$4$', '$2$', '$8$'], answer: 2, explanation: '$V_2=\\dfrac{p_1V_1}{p_2}=2$.' },
        { stem: '$100$ °C bằng bao nhiêu Kelvin?', options: ['$273$', '$100$', '$173$', '$373$'], answer: 3, explanation: '$100+273=373$ K.' },
        { stem: 'Lực từ lên dây dẫn đạt cực đại khi góc giữa dây và $\\vec{B}$ bằng?', options: ['$0^\\circ$', '$90^\\circ$', '$45^\\circ$', '$180^\\circ$'], answer: 1, explanation: '$\\sin\\theta$ lớn nhất khi $\\theta=90^\\circ$.' },
        { stem: 'Đơn vị của từ thông là?', options: ['Vêbe (Wb)', 'Tesla (T)', 'Jun (J)', 'Ampe (A)'], answer: 0, explanation: 'Từ thông đo bằng vêbe.' },
        { stem: 'Hạt nhân $^{16}_{8}O$ có bao nhiêu neutron?', options: ['$16$', '$24$', '$8$', '$0$'], answer: 2, explanation: '$N=A-Z=16-8=8$.' },
        { stem: 'Sau 3 chu kì bán rã, còn lại bao nhiêu phần trăm?', options: ['$50\\%$', '$25\\%$', '$75\\%$', '$12{,}5\\%$'], answer: 3, explanation: '$2^{-3}=\\tfrac18=12{,}5\\%$.' },
        { stem: 'Suất điện động cảm ứng tỉ lệ với?', options: ['độ lớn từ thông', 'tốc độ biến thiên từ thông', 'cường độ dòng điện', 'điện trở'], answer: 1, explanation: '$|e|=\\left|\\dfrac{\\Delta\\Phi}{\\Delta t}\\right|$.' },
        { stem: 'Lực từ $F=BIl$; nếu $I$ tăng gấp đôi (các đại lượng khác không đổi) thì $F$?', options: ['không đổi', 'giảm một nửa', 'gấp đôi', 'gấp bốn'], answer: 2, explanation: '$F$ tỉ lệ thuận với $I$.' },
      ],
    },
    {
      examId: 'ly-kt45-5', title: 'Kiểm tra 45′ #5 — Vật lí 12 (mở rộng)', durationMin: 45,
      questions: [
        { stem: 'Nội năng của khí lí tưởng phụ thuộc chủ yếu vào?', options: ['áp suất', 'nhiệt độ', 'thể tích', 'khối lượng riêng'], answer: 1, explanation: 'Nội năng khí lí tưởng chỉ phụ thuộc nhiệt độ.' },
        { stem: 'Nhiệt lượng đun $2$ kg nhôm ($c=880$) tăng $10$ °C là?', options: ['$8800$ J', '$1760$ J', '$17600$ J', '$880$ J'], answer: 2, explanation: '$Q=2\\cdot880\\cdot10=17600$ J.' },
        { stem: 'Đẳng tích: $p_1=1{,}5$ atm ở $T_1=300$ K, đun tới $T_2=400$ K. Tính $p_2$.', options: ['$2$', '$1{,}5$', '$1{,}125$', '$3$'], answer: 0, explanation: '$p_2=1{,}5\\cdot\\dfrac{400}{300}=2$ atm.' },
        { stem: 'Trong quá trình đẳng nhiệt, đại lượng nào không đổi?', options: ['$p/T$', '$pV$', '$V/T$', '$pVT$'], answer: 1, explanation: 'Đẳng nhiệt: $pV=$ const.' },
        { stem: 'Độ lớn lực Lorentz phụ thuộc vận tốc $v$ thế nào?', options: ['không phụ thuộc $v$', 'tỉ lệ $1/v$', 'tỉ lệ thuận $v$', 'tỉ lệ $v^2$'], answer: 2, explanation: '$f=|q|vB\\sin\\alpha$.' },
        { stem: 'Cảm ứng từ thường được ký hiệu là?', options: ['$E$', '$F$', '$\\Phi$', '$B$'], answer: 3, explanation: 'Cảm ứng từ: $B$ (đơn vị T).' },
        { stem: 'Hạt nhân $^{235}_{92}U$ có bao nhiêu proton?', options: ['$92$', '$235$', '$143$', '$0$'], answer: 0, explanation: '$Z=92$.' },
        { stem: 'Phóng xạ $\\alpha$ phát ra hạt nào?', options: ['proton', '$^{4}_{2}He$', 'electron', 'neutron'], answer: 1, explanation: 'Tia $\\alpha$ là hạt nhân heli $^{4}_{2}He$.' },
        { stem: 'Độ hụt khối $\\Delta m=0{,}1$ u ⇒ năng lượng liên kết xấp xỉ?', options: ['$9{,}315$ MeV', '$931{,}5$ MeV', '$93{,}15$ MeV', '$0{,}1$ MeV'], answer: 2, explanation: '$0{,}1\\cdot931{,}5\\approx93{,}15$ MeV.' },
        { stem: 'Theo định luật Len-xơ, dòng điện cảm ứng có chiều?', options: ['cùng chiều biến thiên', 'không xác định', 'theo chiều dòng ngoài', 'chống lại sự biến thiên từ thông'], answer: 3, explanation: 'Dòng cảm ứng chống lại nguyên nhân sinh ra nó.' },
      ],
    },
  ],

  HOA: [
    {
      examId: 'hoa-kt45-1', title: 'Kiểm tra 45′ #1 — Ester–Lipid & Carbohydrate', durationMin: 45,
      questions: [
        { stem: 'Công thức tổng quát ester no, đơn chức, mạch hở là?', options: ['$C_nH_{2n+2}O$', '$C_nH_{2n}O_2$', '$C_nH_{2n-2}O_2$', '$C_nH_{2n}O$'], answer: 1, explanation: 'Ester no đơn chức mạch hở: $C_nH_{2n}O_2\\ (n\\ge2)$.' },
        { stem: 'Công thức của ethyl acetate là?', options: ['$HCOOCH_3$', '$CH_3COOC_2H_5$', '$C_2H_5COOH$', '$CH_3OH$'], answer: 1, explanation: 'Acetate $CH_3COO-$ + ethyl $C_2H_5$.' },
        { stem: 'Thủy phân ester trong môi trường kiềm thu được?', options: ['acid + ancol', 'muối + ancol', 'aldehyde + nước', 'ester + nước'], answer: 1, explanation: 'Xà phòng hóa: $RCOOR\'+NaOH\\to RCOONa+R\'OH$.' },
        { stem: 'Chất béo là trieste của glycerol với?', options: ['acid béo', 'glucose', 'amino acid', 'ethanol'], answer: 0, explanation: 'Chất béo = trieste của glycerol và acid béo.' },
        { stem: 'Công thức phân tử của glucose là?', options: ['$C_{12}H_{22}O_{11}$', '$C_6H_{12}O_6$', '$(C_6H_{10}O_5)_n$', '$C_6H_6$'], answer: 1, explanation: 'Glucose: $C_6H_{12}O_6$.' },
        { stem: 'Glucose tham gia phản ứng tráng bạc nhờ nhóm chức?', options: ['$-OH$', '$-COOH$', '$-CHO$', '$-NH_2$'], answer: 2, explanation: 'Nhóm aldehyde $-CHO$.' },
        { stem: 'Thủy phân hoàn toàn tinh bột thu được?', options: ['fructose', 'saccharose', 'glucose', 'cellulose'], answer: 2, explanation: 'Tinh bột → glucose.' },
        { stem: 'Công thức phân tử của saccharose là?', options: ['$C_6H_{12}O_6$', '$C_{12}H_{22}O_{11}$', '$(C_6H_{10}O_5)_n$', '$C_{11}H_{22}O_{12}$'], answer: 1, explanation: 'Saccharose: $C_{12}H_{22}O_{11}$.' },
        { stem: 'Phản ứng ester hóa cần xúc tác?', options: ['$NaOH$', '$HCl$ loãng', '$H_2SO_4$ đặc, $t^\\circ$', '$AgNO_3$'], answer: 2, explanation: 'Xúc tác $H_2SO_4$ đặc, đun nóng.' },
        { stem: 'Số nhóm $-OH$ trong phân tử glucose (mạch hở) là?', options: ['$3$', '$4$', '$5$', '$6$'], answer: 2, explanation: 'Glucose có 5 nhóm $-OH$ và 1 nhóm $-CHO$.' },
      ],
    },
    {
      examId: 'hoa-kt45-2', title: 'Kiểm tra 45′ #2 — Nitơ, Polymer & Kim loại', durationMin: 45,
      questions: [
        { stem: 'Methylamine $CH_3NH_2$ làm quỳ tím?', options: ['hóa đỏ', 'hóa xanh', 'không đổi màu', 'mất màu'], answer: 1, explanation: 'Amine có tính base ⇒ quỳ hóa xanh.' },
        { stem: 'Công thức của glycine là?', options: ['$CH_3NH_2$', '$H_2N{-}CH_2{-}COOH$', '$C_6H_5NH_2$', '$CH_3COOH$'], answer: 1, explanation: 'Glycine: $H_2N{-}CH_2{-}COOH$.' },
        { stem: 'Amino acid có tính chất?', options: ['chỉ acid', 'chỉ base', 'lưỡng tính', 'trung tính'], answer: 2, explanation: 'Có cả $-NH_2$ và $-COOH$.' },
        { stem: 'Nhận biết protein bằng phản ứng?', options: ['tráng bạc', 'màu biure', 'với quỳ tím', 'với $NaCl$'], answer: 1, explanation: 'Phản ứng màu biure (với $Cu(OH)_2$ → tím).' },
        { stem: 'Trùng hợp ethylene thu được?', options: ['PVC', 'PE', 'cao su', 'tơ nylon'], answer: 1, explanation: '$nCH_2{=}CH_2\\to(-CH_2-CH_2-)_n$ (PE).' },
        { stem: 'Monomer để điều chế PVC là?', options: ['$CH_2{=}CH_2$', '$CH_2{=}CHCl$', '$CH_2{=}CH{-}CH_3$', '$CHCl_3$'], answer: 1, explanation: 'Vinyl chloride $CH_2{=}CHCl$.' },
        { stem: 'Trong các kim loại $Cu, Fe, K, Ag$, kim loại nào tính khử mạnh nhất?', options: ['$Cu$', '$Fe$', '$K$', '$Ag$'], answer: 2, explanation: '$K$ đứng đầu dãy hoạt động.' },
        { stem: 'Sản phẩm của $Fe + CuSO_4$ là?', options: ['$Fe_2(SO_4)_3 + Cu$', '$FeSO_4 + Cu$', '$FeS + CuO$', 'không phản ứng'], answer: 1, explanation: '$Fe + CuSO_4 \\to FeSO_4 + Cu$.' },
        { stem: 'Liên kết peptide có dạng?', options: ['$-COO-$', '$-O-$', '$-CO{-}NH-$', '$-NH_2$'], answer: 2, explanation: 'Liên kết $-CO{-}NH-$.' },
        { stem: 'Công thức amine no, đơn chức, mạch hở là?', options: ['$C_nH_{2n+1}N$', '$C_nH_{2n+3}N$', '$C_nH_{2n}N$', '$C_nH_{2n+2}N$'], answer: 1, explanation: '$C_nH_{2n+3}N$.' },
      ],
    },
    {
      examId: 'hoa-kt45-3', title: 'Kiểm tra 45′ #3 — Tổng hợp Hóa 12', durationMin: 45,
      questions: [
        { stem: 'Số nguyên tử carbon trong phân tử glucose là?', options: ['$5$', '$12$', '$6$', '$3$'], answer: 2, explanation: 'Glucose $C_6H_{12}O_6$.' },
        { stem: 'Xà phòng hóa chất béo thu được muối của acid béo và?', options: ['glycerol', 'ethanol', 'nước', 'aldehyde'], answer: 0, explanation: 'Chất béo + NaOH → muối + glycerol.' },
        { stem: 'Chất nào làm quỳ tím hóa xanh?', options: ['phenol', 'glucose', 'acetic acid', 'methylamine'], answer: 3, explanation: 'Amine có tính base.' },
        { stem: 'Polymer nào được dùng làm tơ?', options: ['PE', 'nylon-6,6', 'PVC', 'cao su buna'], answer: 1, explanation: 'Nylon-6,6 là tơ poliamide.' },
        { stem: 'Kim loại kiềm thuộc nhóm nào trong bảng tuần hoàn?', options: ['IA', 'IIA', 'IIIA', 'VIIIA'], answer: 0, explanation: 'Kim loại kiềm: nhóm IA.' },
        { stem: 'Tính chất hóa học đặc trưng của kim loại là?', options: ['tính oxi hóa', 'tính acid', 'tính khử', 'tính base'], answer: 2, explanation: 'Kim loại nhường e ⇒ tính khử.' },
        { stem: 'Glucose tác dụng $AgNO_3/NH_3$ tạo ra?', options: ['Cu', '$H_2$', '$CO_2$', 'Ag'], answer: 3, explanation: 'Phản ứng tráng bạc tạo Ag.' },
        { stem: 'Amino acid đơn giản nhất là?', options: ['alanine', 'glycine', 'lysine', 'valine'], answer: 1, explanation: 'Glycine $H_2NCH_2COOH$.' },
        { stem: 'Thủy phân saccharose thu được?', options: ['glucose + fructose', '2 glucose', 'maltose', 'tinh bột'], answer: 0, explanation: 'Saccharose → glucose + fructose.' },
        { stem: 'Phản ứng trùng ngưng thường loại ra phân tử?', options: ['$CO_2$', '$O_2$', '$H_2O$', '$H_2$'], answer: 2, explanation: 'Trùng ngưng loại $H_2O$.' },
      ],
    },
    {
      examId: 'hoa-kt45-4', title: 'Kiểm tra 45′ #4 — Hóa hữu cơ & Kim loại', durationMin: 45,
      questions: [
        { stem: 'Ester thường có mùi đặc trưng gì?', options: ['khai', 'thơm (hoa quả)', 'hắc', 'không mùi'], answer: 1, explanation: 'Nhiều ester có mùi thơm.' },
        { stem: 'Công thức chung của carbohydrate là?', options: ['$C_nH_{2n}$', '$C_nH_{2n+2}$', '$C_n(H_2O)_m$', '$C_nH_{2n}O$'], answer: 2, explanation: 'Carbohydrate: $C_n(H_2O)_m$.' },
        { stem: 'Công thức phân tử của cellulose là?', options: ['$C_6H_{12}O_6$', '$C_{12}H_{22}O_{11}$', '$C_6H_6$', '$(C_6H_{10}O_5)_n$'], answer: 3, explanation: 'Cellulose: $(C_6H_{10}O_5)_n$.' },
        { stem: 'Amine có N gắn trực tiếp với 2 gốc hydrocarbon là amine bậc?', options: ['bậc 1', 'bậc 2', 'bậc 3', 'bậc 4'], answer: 1, explanation: 'Bậc = số gốc gắn vào N.' },
        { stem: 'Tơ nylon được điều chế bằng phản ứng?', options: ['trùng ngưng', 'trùng hợp', 'thủy phân', 'oxi hóa'], answer: 0, explanation: 'Nylon tạo bằng trùng ngưng.' },
        { stem: 'Kim loại dẫn điện tốt nhất là?', options: ['Cu', 'Fe', 'Ag', 'Al'], answer: 2, explanation: 'Bạc (Ag) dẫn điện tốt nhất.' },
        { stem: 'Phản ứng nào dùng để nhận biết glucose?', options: ['quỳ tím', 'tráng bạc', 'đốt cháy', 'màu biure'], answer: 1, explanation: 'Glucose có $-CHO$ ⇒ tráng bạc.' },
        { stem: 'Amino acid chứa các nhóm chức nào?', options: ['chỉ $-OH$', 'chỉ $-COOH$', 'chỉ $-NH_2$', '$-NH_2$ và $-COOH$'], answer: 3, explanation: 'Amino acid lưỡng tính.' },
        { stem: 'Đốt cháy ester no, đơn chức, mạch hở: quan hệ $n_{CO_2}$ và $n_{H_2O}$?', options: ['bằng nhau', '$n_{CO_2}>n_{H_2O}$', '$n_{CO_2}<n_{H_2O}$', 'không xác định'], answer: 0, explanation: '$C_nH_{2n}O_2 \\to n\\,CO_2 + n\\,H_2O$.' },
        { stem: 'Kim loại kiềm thổ thuộc nhóm nào?', options: ['IA', 'IIIA', 'IIA', 'VIIIA'], answer: 2, explanation: 'Kim loại kiềm thổ: nhóm IIA.' },
      ],
    },
    {
      examId: 'hoa-kt45-5', title: 'Kiểm tra 45′ #5 — Hóa 12 (mở rộng)', durationMin: 45,
      questions: [
        { stem: 'Phản ứng ester hóa là phản ứng giữa?', options: ['acid + ancol', 'acid + kiềm', 'ancol + kim loại', 'ester + nước'], answer: 0, explanation: 'Acid carboxylic + ancol → ester + nước.' },
        { stem: 'Glucose thuộc loại carbohydrate nào?', options: ['polysaccharide', 'disaccharide', 'monosaccharide', 'không phải carbohydrate'], answer: 2, explanation: 'Glucose là monosaccharide.' },
        { stem: 'Xà phòng là muối của?', options: ['acid vô cơ', 'acid béo', 'ancol', 'amine'], answer: 1, explanation: 'Xà phòng = muối Na/K của acid béo.' },
        { stem: 'Protein bị đông tụ khi?', options: ['làm lạnh', 'pha loãng', 'để yên', 'đun nóng'], answer: 3, explanation: 'Nhiệt làm protein đông tụ (biến tính).' },
        { stem: 'Kim loại nào nhẹ nhất?', options: ['Li', 'Fe', 'Pb', 'Cu'], answer: 0, explanation: 'Lithium có khối lượng riêng nhỏ nhất.' },
        { stem: 'Kim loại nào tác dụng với nước ở nhiệt độ thường?', options: ['Cu', 'Ag', 'Na', 'Au'], answer: 2, explanation: 'Na (kim loại kiềm) phản ứng mạnh với nước.' },
        { stem: 'Tơ visco, tơ acetate thuộc loại tơ?', options: ['thiên nhiên', 'bán tổng hợp', 'tổng hợp', 'không phải tơ'], answer: 1, explanation: 'Tơ nhân tạo (bán tổng hợp) từ cellulose.' },
        { stem: 'Glucose tác dụng $H_2$ (Ni, $t^\\circ$) tạo ra?', options: ['fructose', 'acid gluconic', 'ethanol', 'sorbitol'], answer: 3, explanation: 'Khử nhóm $-CHO$ → sorbitol.' },
        { stem: 'Dung dịch chất nào làm quỳ tím hóa đỏ?', options: ['glutamic acid', 'glycine', 'lysine', 'alanine'], answer: 0, explanation: 'Glutamic acid có 2 nhóm $-COOH$ ⇒ tính acid.' },
        { stem: 'Phản ứng tạo polymer từ monomer có liên kết bội là?', options: ['trùng ngưng', 'thủy phân', 'trùng hợp', 'ester hóa'], answer: 2, explanation: 'Trùng hợp.' },
      ],
    },
  ],

  ANH: [
    {
      examId: 'anh-kt45-1', title: 'Kiểm tra 45′ #1 — Grammar (Tiếng Anh 12)', durationMin: 45,
      questions: [
        { stem: 'She ____ here since 2010.', options: ['lives', 'has lived', 'lived', 'living'], answer: 1, explanation: 'since + mốc thời gian ⇒ present perfect.' },
        { stem: 'A letter ____ by Tom yesterday.', options: ['writes', 'wrote', 'was written', 'is writing'], answer: 2, explanation: 'Bị động quá khứ: was + V3.' },
        { stem: 'If I ____ you, I would accept the offer.', options: ['am', 'was', 'be', 'were'], answer: 3, explanation: 'Điều kiện loại 2: dùng "were".' },
        { stem: 'The man ____ lives next door is a doctor.', options: ['who', 'which', 'whom', 'whose'], answer: 0, explanation: '"who" thay cho người làm chủ ngữ.' },
        { stem: 'This is the house ____ I was born.', options: ['which', 'when', 'where', 'who'], answer: 2, explanation: '"where" chỉ nơi chốn.' },
        { stem: 'They ____ to Paris last summer.', options: ['go', 'went', 'gone', 'have gone'], answer: 1, explanation: 'last summer ⇒ quá khứ đơn.' },
        { stem: 'English ____ all over the world.', options: ['speaks', 'spoke', 'speaking', 'is spoken'], answer: 3, explanation: 'Bị động hiện tại: is + V3.' },
        { stem: 'If it ____ tomorrow, we will cancel the trip.', options: ['rains', 'rained', 'will rain', 'would rain'], answer: 0, explanation: 'Điều kiện loại 1: If + hiện tại đơn.' },
        { stem: 'The girl ____ bag was stolen is crying.', options: ['which', 'whose', 'who', 'that'], answer: 1, explanation: '"whose" chỉ sở hữu.' },
        { stem: 'I have ____ finished my homework.', options: ['yet', 'since', 'already', 'ago'], answer: 2, explanation: '"already" trong câu khẳng định hoàn thành.' },
      ],
    },
    {
      examId: 'anh-kt45-2', title: 'Kiểm tra 45′ #2 — Grammar (Tiếng Anh 12)', durationMin: 45,
      questions: [
        { stem: 'He suggested ____ a short break.', options: ['take', 'to take', 'took', 'taking'], answer: 3, explanation: 'suggest + V-ing.' },
        { stem: 'By the time we arrived, the film ____.', options: ['had started', 'has started', 'started', 'starts'], answer: 0, explanation: 'Quá khứ hoàn thành cho hành động xảy ra trước.' },
        { stem: 'This bridge ____ in 1990.', options: ['built', 'is built', 'was built', 'builds'], answer: 2, explanation: 'Bị động quá khứ: was + V3.' },
        { stem: 'Neither John nor his friends ____ here.', options: ['is', 'are', 'was', 'has'], answer: 1, explanation: 'Động từ chia theo chủ ngữ gần nhất "friends".' },
        { stem: 'I wish I ____ taller.', options: ['am', 'was', 'be', 'were'], answer: 3, explanation: 'wish + were (giả định).' },
        { stem: 'She asked me where I ____.', options: ['lived', 'live', 'living', 'to live'], answer: 0, explanation: 'Câu tường thuật ⇒ lùi thì.' },
        { stem: "It's the best film I ____ ever seen.", options: ['has', 'had', 'have', 'having'], answer: 2, explanation: 'Hiện tại hoàn thành với "I".' },
        { stem: 'If he had studied, he ____ passed.', options: ['will have', 'would have', 'would', 'had'], answer: 1, explanation: 'Điều kiện loại 3: would have + V3.' },
        { stem: 'Choose the synonym of "famous".', options: ['unknown', 'ordinary', 'hidden', 'well-known'], answer: 3, explanation: 'famous ≈ well-known.' },
        { stem: "You ____ smoke here; it's forbidden.", options: ["mustn't", 'must', 'should', 'can'], answer: 0, explanation: "mustn't = cấm." },
      ],
    },
    {
      examId: 'anh-kt45-3', title: 'Kiểm tra 45′ #3 — Grammar & Vocabulary', durationMin: 45,
      questions: [
        { stem: 'She has worked here ____ five years.', options: ['since', 'in', 'for', 'ago'], answer: 2, explanation: 'for + khoảng thời gian.' },
        { stem: 'The book ____ is on the table is mine.', options: ['which', 'who', 'whose', 'where'], answer: 0, explanation: 'which/that thay cho vật.' },
        { stem: 'He ____ to school every day.', options: ['go', 'going', 'gone', 'goes'], answer: 3, explanation: 'Hiện tại đơn ngôi thứ ba: goes.' },
        { stem: "I haven't seen him ____ Monday.", options: ['for', 'since', 'from', 'ago'], answer: 1, explanation: 'since + mốc thời gian.' },
        { stem: 'If I had money, I ____ buy a car.', options: ['will', 'can', 'would', 'must'], answer: 2, explanation: 'Điều kiện loại 2: would + V.' },
        { stem: 'This is ____ interesting book.', options: ['an', 'a', 'the', 'no'], answer: 0, explanation: 'an + nguyên âm (interesting).' },
        { stem: 'They enjoy ____ football at weekends.', options: ['play', 'to play', 'played', 'playing'], answer: 3, explanation: 'enjoy + V-ing.' },
        { stem: 'The cake ____ by Mary last night.', options: ['makes', 'was made', 'made', 'is making'], answer: 1, explanation: 'Bị động quá khứ.' },
        { stem: 'Choose the synonym of "happy".', options: ['sad', 'angry', 'glad', 'tired'], answer: 2, explanation: 'happy ≈ glad.' },
        { stem: 'He is taller ____ his brother.', options: ['than', 'then', 'as', 'that'], answer: 0, explanation: 'So sánh hơn: adj-er + than.' },
      ],
    },
    {
      examId: 'anh-kt45-4', title: 'Kiểm tra 45′ #4 — Grammar & Vocabulary', durationMin: 45,
      questions: [
        { stem: 'If I ____ rich, I would help the poor.', options: ['am', 'was', 'were', 'be'], answer: 2, explanation: 'Điều kiện loại 2: were.' },
        { stem: 'The letter ____ yesterday.', options: ['sends', 'was sent', 'sent', 'is sending'], answer: 1, explanation: 'Bị động quá khứ.' },
        { stem: 'She is interested ____ classical music.', options: ['in', 'on', 'at', 'of'], answer: 0, explanation: 'interested in.' },
        { stem: 'They have lived here ____ 2015.', options: ['for', 'from', 'ago', 'since'], answer: 3, explanation: 'since + mốc thời gian.' },
        { stem: 'This is the man ____ helped me yesterday.', options: ['which', 'who', 'whose', 'where'], answer: 1, explanation: 'who cho người làm chủ ngữ.' },
        { stem: 'I really enjoy ____ books in my free time.', options: ['read', 'to read', 'reading', 'reads'], answer: 2, explanation: 'enjoy + V-ing.' },
        { stem: 'He runs ____ than me.', options: ['faster', 'fast', 'fastest', 'more fast'], answer: 0, explanation: 'So sánh hơn của trạng từ ngắn: faster.' },
        { stem: 'Choose the synonym of "begin".', options: ['stop', 'end', 'finish', 'start'], answer: 3, explanation: 'begin ≈ start.' },
        { stem: 'You ____ to wear a helmet when riding a motorbike.', options: ['have', 'has', 'having', 'had'], answer: 0, explanation: 'have to (nghĩa vụ).' },
        { stem: 'Water ____ at 100°C.', options: ['boil', 'boiled', 'boils', 'boiling'], answer: 2, explanation: 'Chân lý ⇒ hiện tại đơn, ngôi thứ ba.' },
      ],
    },
    {
      examId: 'anh-kt45-5', title: 'Kiểm tra 45′ #5 — Grammar & Vocabulary', durationMin: 45,
      questions: [
        { stem: 'I ____ my homework already.', options: ['do', 'did', 'have done', 'doing'], answer: 2, explanation: 'already + present perfect.' },
        { stem: 'He asked me if I ____ free.', options: ['was', 'am', 'is', 'be'], answer: 0, explanation: 'Câu tường thuật ⇒ lùi thì.' },
        { stem: 'Neither answer ____ correct.', options: ['are', 'were', 'have', 'is'], answer: 3, explanation: 'neither + danh từ số ít + is.' },
        { stem: 'The more he earns, the more he ____.', options: ['spend', 'spends', 'spending', 'spent'], answer: 1, explanation: 'Cấu trúc the more..., ngôi 3 số ít: spends.' },
        { stem: "I'd rather you ____ here tonight.", options: ['stay', 'staying', 'stayed', 'to stay'], answer: 2, explanation: 'would rather + S + V quá khứ.' },
        { stem: 'Choose the synonym of "huge".', options: ['enormous', 'tiny', 'small', 'little'], answer: 0, explanation: 'huge ≈ enormous.' },
        { stem: 'She works ____ a teacher.', options: ['like', 'for', 'with', 'as'], answer: 3, explanation: 'work as + nghề nghiệp.' },
        { stem: 'Hardly ____ I arrived when it started raining.', options: ['have', 'had', 'did', 'was'], answer: 1, explanation: 'Đảo ngữ Hardly had S + V3.' },
        { stem: 'The news ____ very good today.', options: ['are', 'were', 'is', 'have'], answer: 2, explanation: '"news" là danh từ không đếm được, số ít.' },
        { stem: 'Choose the synonym of "rich".', options: ['wealthy', 'poor', 'broke', 'needy'], answer: 0, explanation: 'rich ≈ wealthy.' },
      ],
    },
  ],

  TOEIC: [
    {
      examId: 'toeic-reading', title: 'TOEIC Reading – Mini test', durationMin: 10,
      questions: [
        { stem: 'The report must be submitted ____ Friday.',
          options: ['in', 'on', 'at', 'by'], answer: 3, explanation: '"by Friday" = hạn chót đến thứ Sáu.' },
        { stem: 'She is responsible ____ marketing.',
          options: ['for', 'to', 'with', 'of'], answer: 0, explanation: 'be responsible <strong>for</strong> something.' },
        { stem: 'We look forward to ____ from you.',
          options: ['hear', 'hearing', 'heard', 'hears'], answer: 1, explanation: 'look forward to + V-ing.' },
      ],
    },
    {
      examId: 'toeic-2', title: 'TOEIC – Grammar & Vocabulary #2', durationMin: 20,
      questions: [
        { stem: 'The meeting has been ____ until next week.', options: ['postpone', 'postponed', 'postponing', 'postpones'], answer: 1, explanation: 'has been + V3 (bị động hoàn thành).' },
        { stem: 'We ____ forward to your prompt reply.', options: ['look', 'looks', 'looking', 'looked'], answer: 0, explanation: 'Chủ ngữ "We" + động từ nguyên thể.' },
        { stem: 'All employees must ____ the safety rules.', options: ['follow', 'follows', 'following', 'to follow'], answer: 0, explanation: 'must + V nguyên thể.' },
        { stem: 'The report is due ____ Monday.', options: ['in', 'on', 'at', 'of'], answer: 1, explanation: 'on + thứ trong tuần.' },
        { stem: 'She is responsible ____ the marketing team.', options: ['of', 'to', 'for', 'with'], answer: 2, explanation: 'be responsible for.' },
        { stem: 'Sales have increased ____ 10% this year.', options: ['by', 'in', 'on', 'at'], answer: 0, explanation: 'increase by + mức tăng.' },
        { stem: '____ you have any questions, please contact us.', options: ['If', 'Unless', 'Despite', 'Because'], answer: 0, explanation: 'If + mệnh đề điều kiện.' },
        { stem: 'The new policy will ____ effect next month.', options: ['take', 'make', 'do', 'have'], answer: 0, explanation: 'collocation "take effect".' },
        { stem: 'Choose the synonym of "purchase".', options: ['sell', 'buy', 'return', 'order'], answer: 1, explanation: 'purchase ≈ buy.' },
        { stem: 'The manager ____ the proposal yesterday.', options: ['approve', 'approves', 'approved', 'approving'], answer: 2, explanation: 'yesterday ⇒ quá khứ đơn.' },
      ],
    },
    {
      examId: 'toeic-3', title: 'TOEIC – Grammar & Vocabulary #3', durationMin: 20,
      questions: [
        { stem: 'Please submit the report ____ Friday.', options: ['by', 'in', 'at', 'of'], answer: 0, explanation: 'by + hạn chót.' },
        { stem: 'The company ____ a new product last month.', options: ['launch', 'launching', 'launched', 'launches'], answer: 2, explanation: 'last month ⇒ quá khứ đơn.' },
        { stem: 'Employees are required ____ ID badges.', options: ['wear', 'to wear', 'wearing', 'worn'], answer: 1, explanation: 'be required + to V.' },
        { stem: 'The company is trying to ____ operating costs.', options: ['increase', 'rise', 'raise', 'reduce'], answer: 3, explanation: 'cut/reduce costs.' },
        { stem: 'The director will ____ the weekly meeting.', options: ['lead', 'do', 'make', 'take'], answer: 0, explanation: 'lead a meeting.' },
        { stem: 'We apologize ____ the delay.', options: ['to', 'with', 'for', 'of'], answer: 2, explanation: 'apologize for something.' },
        { stem: 'The invoice ____ to the client yesterday.', options: ['sends', 'was sent', 'sent', 'is sending'], answer: 1, explanation: 'Bị động quá khứ.' },
        { stem: 'Choose the synonym of "increase" (verb).', options: ['fall', 'drop', 'cut', 'rise'], answer: 3, explanation: 'increase ≈ rise.' },
        { stem: 'All staff ____ attend the safety training.', options: ['must', 'can', 'might', 'would'], answer: 0, explanation: 'yêu cầu bắt buộc: must.' },
        { stem: 'The store is open ____ 9 a.m. to 6 p.m.', options: ['in', 'at', 'from', 'since'], answer: 2, explanation: 'from ... to ...' },
      ],
    },
    {
      examId: 'toeic-4', title: 'TOEIC – Grammar & Vocabulary #4', durationMin: 20,
      questions: [
        { stem: 'The shipment will arrive ____ two days.', options: ['on', 'at', 'by', 'in'], answer: 3, explanation: 'in + khoảng thời gian (tương lai).' },
        { stem: 'We are pleased ____ announce the results.', options: ['to', 'for', 'with', 'of'], answer: 0, explanation: 'be pleased to + V.' },
        { stem: 'The contract must be signed ____ both parties.', options: ['with', 'of', 'by', 'to'], answer: 2, explanation: 'Bị động: by + tác nhân.' },
        { stem: 'Sales ____ increased recently.', options: ['has', 'have', 'having', 'had'], answer: 1, explanation: '"Sales" số nhiều + have.' },
        { stem: 'Thank you for ____ us.', options: ['contact', 'contacted', 'contacts', 'contacting'], answer: 3, explanation: 'for + V-ing.' },
        { stem: 'Choose the synonym of "expand".', options: ['grow', 'shrink', 'reduce', 'cut'], answer: 0, explanation: 'expand ≈ grow.' },
        { stem: 'The meeting was ____ due to bad weather.', options: ['cancel', 'cancelling', 'cancelled', 'cancels'], answer: 2, explanation: 'Bị động: was + V3.' },
        { stem: 'Employees should ____ their manager of any problems.', options: ['informed', 'informing', 'informs', 'inform'], answer: 3, explanation: 'should + V nguyên thể.' },
        { stem: 'Please reply ____ receipt of this email.', options: ['in', 'upon', 'at', 'of'], answer: 1, explanation: 'collocation "upon receipt".' },
        { stem: 'Choose the synonym of "client".', options: ['employee', 'manager', 'customer', 'supplier'], answer: 2, explanation: 'client ≈ customer.' },
      ],
    },
    {
      examId: 'toeic-5', title: 'TOEIC – Grammar & Vocabulary #5', durationMin: 20,
      questions: [
        { stem: 'The conference will be held ____ the main hall.', options: ['on', 'at', 'by', 'in'], answer: 3, explanation: 'in + không gian bên trong.' },
        { stem: 'He has worked here ____ three years.', options: ['for', 'since', 'in', 'ago'], answer: 0, explanation: 'for + khoảng thời gian.' },
        { stem: 'Please ____ to the instructions before starting.', options: ['prefer', 'offer', 'refer', 'infer'], answer: 2, explanation: 'refer to = tham khảo.' },
        { stem: 'The package was delivered ____ time.', options: ['in', 'on', 'at', 'by'], answer: 1, explanation: 'collocation "on time".' },
        { stem: 'Our team is ____ for the increase in sales.', options: ['responsible', 'response', 'responsibly', 'responsive'], answer: 0, explanation: 'be responsible for (tính từ).' },
        { stem: 'Choose the synonym of "assist".', options: ['ignore', 'refuse', 'help', 'avoid'], answer: 2, explanation: 'assist ≈ help.' },
        { stem: 'All applications must be ____ by Friday.', options: ['submit', 'submitting', 'submits', 'submitted'], answer: 3, explanation: 'must be + V3 (bị động).' },
        { stem: 'If you ____ any questions, please ask.', options: ['have', 'has', 'having', 'had'], answer: 0, explanation: 'If + hiện tại đơn.' },
        { stem: 'The new branch will ____ next month.', options: ['opens', 'opening', 'open', 'opened'], answer: 2, explanation: 'will + V nguyên thể.' },
        { stem: 'Choose the synonym of "approximately".', options: ['exactly', 'about', 'rarely', 'never'], answer: 1, explanation: 'approximately ≈ about.' },
      ],
    },
  ],

  IELTS: [
    {
      examId: 'ielts-kt-1', title: 'IELTS – Vocabulary & Grammar #1', durationMin: 20,
      questions: [
        { stem: 'Choose the synonym of "thorough": The report was very ____.', options: ['brief', 'shallow', 'comprehensive', 'quick'], answer: 2, explanation: 'thorough ≈ comprehensive.' },
        { stem: 'She made a significant ____ to the project.', options: ['contribution', 'contribute', 'contributor', 'contributing'], answer: 0, explanation: 'Cần danh từ sau tính từ "significant".' },
        { stem: 'Despite ____ hard, he failed the exam.', options: ['work', 'worked', 'to work', 'working'], answer: 3, explanation: 'despite + V-ing.' },
        { stem: 'Choose the synonym of "crucial".', options: ['optional', 'essential', 'minor', 'rare'], answer: 1, explanation: 'crucial ≈ essential.' },
        { stem: 'The number of students ____ increasing every year.', options: ['are', 'were', 'is', 'have'], answer: 2, explanation: '"The number of" + động từ số ít.' },
        { stem: 'There is a wide ____ of options available.', options: ['range', 'amount', 'number', 'deal'], answer: 0, explanation: 'collocation "a wide range of".' },
        { stem: 'Choose the antonym of "increase".', options: ['rise', 'grow', 'expand', 'decrease'], answer: 3, explanation: 'Trái nghĩa của increase là decrease.' },
        { stem: 'I look forward to ____ from you soon.', options: ['hear', 'hearing', 'heard', 'to hear'], answer: 1, explanation: 'look forward to + V-ing.' },
        { stem: 'Choose the synonym of "benefit".', options: ['drawback', 'problem', 'advantage', 'cost'], answer: 2, explanation: 'benefit ≈ advantage.' },
        { stem: 'Global warming ____ a serious threat to humanity.', options: ['poses', 'makes', 'does', 'gives'], answer: 0, explanation: 'collocation "pose a threat".' },
      ],
    },
    {
      examId: 'ielts-kt-2', title: 'IELTS – Vocabulary & Grammar #2', durationMin: 20,
      questions: [
        { stem: 'Choose the synonym of "significant".', options: ['minor', 'slight', 'considerable', 'rare'], answer: 2, explanation: 'significant ≈ considerable.' },
        { stem: 'The graph ____ a sharp increase in sales.', options: ['shows', 'show', 'showing', 'shown'], answer: 0, explanation: 'Chủ ngữ số ít "The graph".' },
        { stem: 'It is important to ____ a decision quickly.', options: ['do', 'take', 'have', 'make'], answer: 3, explanation: 'collocation "make a decision".' },
        { stem: 'Choose the antonym of "rural".', options: ['remote', 'urban', 'quiet', 'village'], answer: 1, explanation: 'rural ↔ urban.' },
        { stem: 'A large ____ of people attended the event.', options: ['amount', 'deal', 'number', 'piece'], answer: 2, explanation: '"a large number of" + danh từ đếm được.' },
        { stem: '____ the heavy rain, they continued the trip.', options: ['Despite', 'Although', 'Because', 'So'], answer: 0, explanation: 'Despite + cụm danh từ.' },
        { stem: 'Choose the synonym of "rapid".', options: ['slow', 'gradual', 'steady', 'quick'], answer: 3, explanation: 'rapid ≈ quick.' },
        { stem: 'Recent research ____ that exercise improves mood.', options: ['suggest', 'suggests', 'suggesting', 'suggested'], answer: 1, explanation: '"research" (số ít) + suggests.' },
        { stem: 'This factor accounts ____ about 20% of the total.', options: ['to', 'in', 'for', 'of'], answer: 2, explanation: 'account for = chiếm/giải thích.' },
        { stem: 'Choose the synonym of "essential".', options: ['optional', 'minor', 'extra', 'vital'], answer: 3, explanation: 'essential ≈ vital.' },
      ],
    },
    {
      examId: 'ielts-kt-3', title: 'IELTS – Vocabulary & Grammar #3', durationMin: 20,
      questions: [
        { stem: 'Choose the synonym of "demonstrate".', options: ['hide', 'deny', 'show', 'forget'], answer: 2, explanation: 'demonstrate ≈ show.' },
        { stem: 'The results were truly ____ (very surprising).', options: ['boring', 'normal', 'dull', 'astonishing'], answer: 3, explanation: 'surprising ≈ astonishing.' },
        { stem: 'He is very good ____ mathematics.', options: ['at', 'in', 'on', 'of'], answer: 0, explanation: 'good at + lĩnh vực.' },
        { stem: 'A number of students ____ absent today.', options: ['is', 'are', 'was', 'has'], answer: 1, explanation: '"a number of" + danh từ số nhiều + are.' },
        { stem: 'Choose the antonym of "expensive".', options: ['costly', 'pricey', 'cheap', 'dear'], answer: 2, explanation: 'expensive ↔ cheap.' },
        { stem: 'She ____ in London for ten years.', options: ['lives', 'lived', 'living', 'has lived'], answer: 3, explanation: 'for + khoảng tg ⇒ present perfect.' },
        { stem: 'Despite ____ tired, she kept working.', options: ['being', 'be', 'was', 'been'], answer: 0, explanation: 'despite + V-ing (being).' },
        { stem: 'Choose the synonym of "obtain".', options: ['lose', 'get', 'give', 'drop'], answer: 1, explanation: 'obtain ≈ get.' },
        { stem: 'The more you practise, ____ you become.', options: ['better', 'best', 'the better', 'the best'], answer: 2, explanation: 'Cấu trúc "the more…, the + so sánh hơn".' },
        { stem: 'It is essential ____ we act now.', options: ['what', 'which', 'who', 'that'], answer: 3, explanation: 'It is essential that + mệnh đề.' },
      ],
    },
    {
      examId: 'ielts-kt-4', title: 'IELTS – Vocabulary & Grammar #4', durationMin: 20,
      questions: [
        { stem: 'Choose the synonym of "reduce".', options: ['increase', 'expand', 'decrease', 'raise'], answer: 2, explanation: 'reduce ≈ decrease.' },
        { stem: 'Each of the students ____ a textbook.', options: ['have', 'having', 'had', 'has'], answer: 3, explanation: 'each + danh từ số ít + has.' },
        { stem: 'Choose the antonym of "difficult".', options: ['hard', 'easy', 'tough', 'complex'], answer: 1, explanation: 'difficult ↔ easy.' },
        { stem: 'He succeeded ____ passing the final exam.', options: ['in', 'on', 'at', 'of'], answer: 0, explanation: 'succeed in + V-ing.' },
        { stem: 'Not only ____ he clever, but also kind.', options: ['was', 'does', 'is', 'has'], answer: 2, explanation: 'Đảo ngữ: Not only is he…' },
        { stem: 'Choose the synonym of "important".', options: ['trivial', 'minor', 'small', 'significant'], answer: 3, explanation: 'important ≈ significant.' },
        { stem: 'The book, ____ was published in 2020, is popular.', options: ['who', 'which', 'whose', 'where'], answer: 1, explanation: 'which cho vật (mệnh đề không xác định).' },
        { stem: 'She has been working ____ 8 a.m.', options: ['since', 'for', 'from', 'ago'], answer: 0, explanation: 'since + mốc thời gian.' },
        { stem: 'Air pollution can ____ serious health problems.', options: ['prevent', 'stop', 'cause', 'avoid'], answer: 2, explanation: 'cause = gây ra (≈ result in).' },
        { stem: 'If it had not rained, we ____ have gone out.', options: ['will', 'would', 'can', 'must'], answer: 1, explanation: 'Điều kiện loại 3: would have + V3.' },
      ],
    },
  ],
};

const Exams = {
  list(code) { return EXAMS[code] || []; },
  get(examId) {
    for (const code in EXAMS) {
      const e = EXAMS[code].find((x) => x.examId === examId);
      if (e) {
        // gán id cho từng câu để chấm
        return Object.assign({}, e, { questions: e.questions.map((q, i) => Object.assign({ questionId: examId + '-' + i, type: 'MCQ' }, q)) });
      }
    }
    return null;
  },
};
